Add support for Unsubscribe message
moq-wg/moq-transport pull request #235
Opened 2023-08-16 21:07 UTC by suhasHere

This PR adds support for subscribers to issue unsubscribe requests to express its interest in not receiving media for a given track. This reflects discussions from #203 

The high level call flow is

```mermaid
sequenceDiagram
  Bob->>Relay: SUBSCRIBE( webex.com/alice/hd-video)
  Bob->>Relay: SUBSCRIBE( webex.com/alice/audio)
  loop media
        Relay-->Bob: Media Exchange (audio, hd-video)
   end
   Note left of Bob: Not interested in hd-video anymore
   Bob->>Relay: UNSUBSCRIBE(webex.com/alice/hd-video)
   Relay->>Bob: UNSUBSCRIBE OK (webex.com/alice/hd-video)
   loop media
        Relay-->Bob: Media Exchange continues unaltered for audio
   end
```

2023-08-17 16:04 UTC, afrind reviewed
Individual review

2023-08-17 16:04 UTC, afrind commented on draft-ietf-moq-transport.md
> +| 0x6   | UNSUBSCRIBE REQUEST ({{message-unsubscribe-req}})|
Renumbering will cause interop problems, but I agree that by the final rev we should have the messages in some reasonable ordering.  We could

1) Keep it like this, and assume there's not much interop happening yet, so this is a freebie.
2) keep all the numbers the same for now, add UNSUBSCRIBE and friends at the end, then renumber the messages later when version negotiation is better settled

2023-08-17 16:04 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Full Track Name (...),
You can also do this with the track ID, since you can only unsubscribe things that had an ID.  I might leave FTN in UNSUBSCRIBE_OK/ERROR though.

2023-08-17 16:40 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +| 0x6   | UNSUBSCRIBE REQUEST ({{message-unsubscribe-req}})|
@afrind  you are right. The same thought went through my mind too. Then it felt , if we are changing it is good to change before our interop meeting :-) 

I am fine with either options too

2023-08-17 17:45 UTC, kixelated requested changes

2023-08-17 17:45 UTC, kixelated commented on draft-ietf-moq-transport.md
> +| 0x8   | UNSUBSCRIBE ERROR ({{message-unsubscribe-error}})|
I don't think we need this message. Why would an UNSUBSCRIBE fail?

### The producer already terminated the subscription
This means the producer already sent a SUBSCRIBE_ERROR/SUBSCRIBE_RESET, so sending an UNSUBSCRIBE_ERROR is just redundant.

### The subscription does not exist
Which means the corresponding SUBSCRIBE was not received first. I think this is a protocol error and the connection can be closed instead. 

### Because I said so?
I don't want to support a producer to say: "no, I'm still going to keep sending this junk". An UNSUBSCRIBE should always succeed.

2023-08-17 17:45 UTC, kixelated commented on draft-ietf-moq-transport.md
> +| 0x7   | UNSUBSCRIBE OK ({{message-unsubscribe-ok}})      |
I don't think we need this message. I would have the producer reply with a SUBSCRIBE_RESET instead, mirroring how QUIC streams are reset. 

**SUBSCRIBE_RESET**: The subscription has ended and no further objects will be transmitted above the provided group/object sequence. Mirrors RESET_STREAM.

**UNSUBSCRIBE**: Please terminate the subscription (at a given group/object sequence?). Implicitly acknowledged by the receipt of a SUBSCRIBE_RESET. Mirrors STOP_SENDING.

Note: I think SUBSCRIBE_ERROR and SUBSCRIBE_RESET are the same message, but I'm splitting them here for sake of argument.

2023-08-17 17:45 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  Full Track Name (...),
Using the track ID isn't great in the current spec because you can't UNSUBSCRIBE prior to receiving a SUBSCRIBE_OK. 

However, that's fixed once the subscriber chooses the ID (#145), in which case all SUBSCRIBE messages should reference that ID instead of the full track name. There's no reason to use the full track name unless you're sending these control messages over separate streams, which will introduce a boat-load of race conditions.

2023-08-17 17:45 UTC, kixelated commented on draft-ietf-moq-transport.md
> +applicable in SUBSCRIBE REQUEST, UNSUBSCRIBE and ANNOUNCE messages.
Why do we need auth information in an UNSUBSCRIBE message? This seems like an invalid use-case.

2023-09-11 16:48 UTC, vasilvv approved these changes
We'll need to revisit using track name vs track ID for unsubscribe once we have an answer to #145, but for now, this LGTM.

2023-09-12 04:18 UTC, kixelated approved these changes
It might be useful to have an error code, but I'm not sure. LGTM.

2023-09-14 04:27 UTC, kixelated commented
Thinking about it some more, an error code doesn't seem necessary. 

publisher -> subscriber should have an error code.
subscriber -> publisher doesn't need an error code.

Even with an error code, it would get lost in the deduplication process.

2023-09-18 17:11 UTC, merged