Unannounce
moq-wg/moq-transport pull request #236
Opened 2023-08-17 03:35 UTC by suhasHere

2023-08-17 16:08 UTC, afrind reviewed
Individual Review

2023-08-17 16:08 UTC, afrind commented on draft-ietf-moq-transport.md
> +| 0x15  | GOAWAY ({{message-goaway}})                      |
Same question/comment here as in the UNSUB PR regarding code points changing.

2023-08-17 16:08 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Track Namespace,
Shouldn't this be 

`Track Namespace(...)` ?

2023-08-17 16:08 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Track Namespace,
`(...)`

2023-08-17 16:08 UTC, afrind commented on draft-ietf-moq-transport.md
> +The publisher MAY respond with `SUBSCRIBE ERROR` message ({{message-subscribe-error}}) with an appropriate error for any SUBSCRIBE REQUESTs received for track(s) matching the track namespace after se
We might want to give additional informational guidance that it's totally OK to continue serving existing SUBSCRIBEs too and it is up to the application to decide.

2023-08-17 16:08 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Track Namespace
`(...)`

2023-08-17 16:08 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Error Code (i),
The only code I can imagine here is "I've never heard of that namespace".  It's not like the peer can say "tough cookies, I'm going to keep routing SUBSCRIBE to you".

2023-08-17 16:41 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Track Namespace,
yes, my bad .. will fix it

2023-08-17 17:30 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +The publisher MAY respond with `SUBSCRIBE ERROR` message ({{message-subscribe-error}}) with an appropriate error for any SUBSCRIBE REQUESTs received for track(s) matching the track namespace after se
@afrind Is this along the lines of your thinking

The publisher MAY respond with `SUBSCRIBE ERROR` message ({{message-subscribe-error}}) with an appropriate error for new SUBSCRIBE REQUESTs received for track(s) matching the track namespace after sending the unannounce message. However for existing subscriptions, it is up to the application to either continue to serve media or 
terminate serving those subscriptions.

2023-08-17 18:21 UTC, kixelated requested changes

2023-09-11 16:49 UTC, kixelated commented on draft-ietf-moq-transport.md
> +| 0x9   | UNANNOUNCE  ({{message-unannounce}})             |
This collides with UNSUBSCRIBE if merged.

I would use 0x18 or 0xA

2023-09-11 16:49 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  Track Namespace(...),
Can we add the error code back? Maybe the string reason too, if just for initial interop.

2023-09-11 16:59 UTC, vasilvv approved these changes

2023-09-11 16:59 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +  Track Namespace(...),
Small thing: the RFC 9000 syntax is `(..)`, not `(...)`.

2023-09-11 17:08 UTC, ianswett commented on draft-ietf-moq-transport.md
> +| 0x9   | UNANNOUNCE  ({{message-unannounce}})             |
+1

2023-09-14 04:28 UTC, kixelated approved these changes

2023-09-18 17:00 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  Track Namespace(...),
```suggestion
  Track Namespace(..),
```

2023-09-18 17:01 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  Track Namespace(...),
```suggestion
  Track Namespace(..),
```

2023-09-18 17:02 UTC, merged