Parameter Reform
moq-wg/moq-transport pull request #256
Opened 2023-09-28 19:51 UTC by martinduke

Fixes #247, #251

- Removes "mandatory parameters" from the SETUP message and just puts them in the main part of the message (retaining the notion of parameters as an extension point)

- Unifies the two parameter namespaces into one (previously known as "Track Request Parameters")

- Resolves the inconsistency about receiver reaction to duplicate parameters as a "SHOULD" close, not MUST. (Tracking the appearance of unknown parameter types is relatively resource-intensive)

- Specifies that parameters that arrive in messages where they don't apply are ignored, without error.

2023-09-29 01:25 UTC, kixelated requested changes
SETUP needs to support arbitrary parameters for version negotiation. Version 00 might require role/path, but other versions might not. These fields would be deprecated pretty quickly as set to 0 much like some TLS headers before the switch was made to generic fields.

However if we used ALPN or equivalent in WebTransport for version negotiation, then I would love to used a fixed encoding. It makes life sooo much easier. I would like to use a fixed encoding in SUBSCRIBE/ANNOUNCE since the version has already been negotiated though.

2023-09-29 19:16 UTC, suhasHere commented
I generally like the direction of this PR. But would like to discuss this as part of or post interop.

2023-10-03 14:40 UTC, fluffy commented
Don't see this as big deal one way another but looks fine to me.

2023-10-04 15:06 UTC, huitema commented
Check the [transport parameter encoding in QUIC](https://www.rfc-editor.org/rfc/rfc9000.html#name-transport-parameter-encodin):
~~~
Transport Parameter {
  Transport Parameter ID (i),
  Transport Parameter Length (i),
  Transport Parameter Value (..),
}
~~~
I think this is solving the exact same problem as Setup parameters: transport parameters with unknown ID can just be skipped.

2023-10-04 19:04 UTC, martinduke commented
Major changes from Boston:
- There are SETUP parameters (which are constant across all versions) and version-specific parameters (which apply to all messages except SETUP-- SUBSCRIBE_REQUEST and ANNOUNCE).
- The LSB of the type indicates if the length is varint-encoded or the length is itself a varint.
- Editorial rearranging.
- Keeps the new rules about duplicate parameters and ignoring inapplicable parameters.

2023-10-05 01:42 UTC, afrind reviewed
Individual/Editorial Review

2023-10-05 01:42 UTC, afrind commented on draft-ietf-moq-transport.md
> +String Parameter format with a zero length.
Seems like they could also be represented as an Int param with value=0 or 1.  Is that allowed?

2023-10-05 01:42 UTC, afrind commented on draft-ietf-moq-transport.md
> +The GROUP SEQUENCE parameter (type 0x01) identifies the group within the
nit: Would GROUP START SEQUENCE or just GROUP START be a more apt name?  Particularly if we add GROUP END later.

2023-10-05 01:42 UTC, afrind commented on draft-ietf-moq-transport.md
> +omitted.
Editorial: with the `, when this param` reads awkwardly to me.  I think it's better without the comma, or start the sentence with the when clause?

2023-10-05 01:42 UTC, afrind commented on draft-ietf-moq-transport.md
> +
Did we put AUTH before OBJECT SEQUENCE because we're listing them numerically?  I think keeping GROUP and OBJECT next to each other will read better.

2023-10-05 01:42 UTC, afrind commented on draft-ietf-moq-transport.md
> +The OBJECT SEQUENCE parameter (key 0x03) identifies the object with the
nit: same name comment as with GROUP SEQUENCE

2023-10-05 01:42 UTC, afrind commented on draft-ietf-moq-transport.md
> +applicable to this message. All other parameters are ignored.
Maybe:

Authorization Info is applicable to this message, but is not mandatory.
.

2023-10-05 01:42 UTC, afrind commented on draft-ietf-moq-transport.md
> +applicable to this message. All other parameters are ignored.
Maybe:

Authorization Info is applicable to this message, but is not mandatory.
.

2023-10-05 01:42 UTC, afrind commented on draft-ietf-moq-transport.md
> +but valid for this message.
Maybe this is best captured with a small table like:

```
Param     | Mandatory / Optional / Invalid
-----------------
GROUP SEQ | Optional
OBJ SEQ   | Optional
AUTH INFO | Optional
```
 Similar for other messages with params

2023-10-05 01:42 UTC, afrind commented on draft-ietf-moq-transport.md
> +applicable to this message. All other parameters are ignored.
See above comment about a table.

2023-10-05 13:55 UTC, fluffy reviewed
I'd like to review this in more detail but initial reaction is mostly looks fine to me.

2023-10-05 13:55 UTC, fluffy commented on draft-ietf-moq-transport.md
> +0x01:
I would prefer to see these have an named value or label then an IANA table that mapped that name or label to the value 0x01

2023-10-05 14:39 UTC, huitema reviewed
The proposed syntax looks like early optimization, trying to save a few bytes of encoding by having two classes of identifiers. I would much rather have something like the QUIC transport parameters:

~~~
Parameter {
   Parameter Type (i),
   Parameter Length (i),
   Parameter Value (...)
}
~~~

My proposal would assume that parameter types are standardized, or at least registered, and that the registration specifies the encoding. That encoding will in many cases be "integer" or "string", but it does not have to be forever.

2023-10-05 17:19 UTC, martinduke commented on draft-ietf-moq-transport.md
> +0x01:
Well the issue with that is that you to have to extract the length if you don't know the parameter type.

2023-10-05 17:26 UTC, kixelated commented
Yeah, maybe we just copy QUIC... which is basically the current encoding. I didn't realize that QUIC transport parameters include a redundant size for varints.

I do like Cullen's suggestion that the encoding is specific to the ID. It means we can have other encodings other than string/int, kinda like `preferred_address` in QUIC. The cost is that we include the redundant size for varints, but whatever.

2023-10-05 17:34 UTC, martinduke commented
> The proposed syntax looks like early optimization, trying to save a few bytes of encoding by having two classes of identifiers. I would much rather have something like the QUIC transport parameters:
> 
> ```
> Parameter {
>    Parameter Type (i),
>    Parameter Length (i),
>    Parameter Value (...)
> }
> ```
> 
> My proposal would assume that parameter types are standardized, or at least registered, and that the registration specifies the encoding. That encoding will in many cases be "integer" or "string", but it does not have to be forever.

I agree that QUIC does this. It does create the error case where the varint length is different from the parameter length, and it's nice when encodings don't allow these kinds of errors

2023-10-05 17:37 UTC, suhasHere commented
Leaving a note for myself. I would love to review this post interim.

2023-10-09 16:01 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +to skip to the next parameter.
I would rather just say, "Receiver ignore unrecognized parameters".

2023-10-09 16:04 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +Transport versions. All other messages use a version-specific namespace. For
what is a namespace constant?

2023-10-09 16:05 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +and other message types.
but unclear on what it means different to other message types. May be more clarification is needed ?

2023-10-09 16:06 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +of the Parameter Value field in bytes.
May be this comment is not for this PR. The way it is defined today, will limit the lenghth of the string to 7 bytes. are we ok with that ?

2023-10-09 16:07 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +String Parameter format with a zero length.
I would rather define a Bool parameter type than overloading the meaning of the value.

2023-10-09 16:08 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
the role parameter needs to be optional or there should be a default value if not provided.

2023-10-09 16:12 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +The GROUP SEQUENCE parameter (type 0x01) identifies the group within the
Please add reference to to section defining groups

2023-10-09 16:12 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
@afrind  this comes due to integer/string encoding ;)

2023-10-09 16:13 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +The OBJECT SEQUENCE parameter (key 0x03) identifies the object with the
please add reference to section defining object sequence

2023-10-09 16:16 UTC, suhasHere requested changes
Thanks for the work Martin. I do have few nits and clarification questions. Overall i feel this is looking good.

2023-10-09 16:39 UTC, kixelated commented on draft-ietf-moq-transport.md
> +of the Parameter Value field in bytes.
I'm not sure I follow. The parameter length is a VarInt with a maximum size of 2^62

2023-10-09 16:39 UTC, kixelated commented on draft-ietf-moq-transport.md
> +
I think role is very useful, but kind of annoying as it is currently defined. The application has to know and specify the intention of the server, which also means there's no possible default. I would like to see the role describe the local endpoint's capability, not the server's intended behavior. See #151 

But this is out of scope of the PR.

2023-10-09 16:39 UTC, kixelated commented on draft-ietf-moq-transport.md
> +The GROUP SEQUENCE parameter (type 0x01) identifies the group within the
+1

2023-10-09 16:39 UTC, kixelated commented on draft-ietf-moq-transport.md
> +but valid for this message.
Yeah my concern is that we're going to have a full compatibility matrix when we add more params to more messages. I'd rather just define the parameters for each messages individually, instead of sharing one big parameter namespace.

2023-10-09 16:39 UTC, kixelated commented on draft-ietf-moq-transport.md
> +String Parameter format with a zero length.
Maybe remove this line? I think using both a `string` and `int` are valid ways to encode a boolean, and it's up to the parameter to specify the encoding.

I'm not sure you want to use a string though. Do you just put arbitrary data if it's a truthy value, zero bytes if it's falsy, and missing if it's undefined?

2023-10-09 17:24 UTC, martinduke commented on draft-ietf-moq-transport.md
> +String Parameter format with a zero length.
The model I had in mind was for extension negotiation, where presence of the parameter was an implied True. I think there's value of setting a norm for how this works. But since this seems to be creating a lot of trouble I'll just delete it.

2023-10-09 17:26 UTC, martinduke commented on draft-ietf-moq-transport.md
> +The GROUP SEQUENCE parameter (type 0x01) identifies the group within the
Added the reference. I don't mind the name change but I took this from the current draft and would prefer a separate issue/PR for parameter renaming.

2023-10-09 17:34 UTC, martinduke commented on draft-ietf-moq-transport.md
> +Transport versions. All other messages use a version-specific namespace. For
a namespace THAT IS constant across...

2023-10-09 17:34 UTC, martinduke commented on draft-ietf-moq-transport.md
> +and other message types.
and for all other message types...

2023-10-09 17:35 UTC, martinduke commented on draft-ietf-moq-transport.md
> +of the Parameter Value field in bytes.
yes, the limit is 2^62.

2023-10-09 17:36 UTC, martinduke commented on draft-ietf-moq-transport.md
> +
I agree that this is out of scope.  See #250

2023-10-09 18:24 UTC, martinduke commented
There are a couple of sub-issues where I'm not quite ready to surrender yet: length encoding, and the number of parameter registries/namespaces we're going to have. I sent an email to the list to discuss further.

2023-10-10 13:16 UTC, fluffy commented on draft-ietf-moq-transport.md
> +0x01:
no I did not mean that. I mean that in the text of the draft we in the role section we do not put 0x01, we put a name for that constant like SETUP_PAR_ROLE then later in the document we have an IANA table that defined SETUP_PAR_ROLE  as 0x01. This is only a change in the way the doc is organized, not anything on the wire. I really don't care about this very much but I find it an easy way to make sure that two different places in the doc did not accidentally use 0x01 for when they mean to have different code points.  It also helps with library API because then people end up definiing the constants in the API to match the spec and it makes it easier to figure out what the API does. Again, all way secondary benefits and we can do this way later in the spec development. Do not need to figure this out to merge this PR.

2023-10-10 18:02 UTC, martinduke commented on draft-ietf-moq-transport.md
> +0x01:
Ah, i see now that I massively misinterpreted your comment. I added a TODO since the IANA considerations section is not ready for this yet.

2023-10-18 04:41 UTC, kixelated commented
My ideal solution would be to keep flexible SETUP parameters for version/extension negotiation, but use fixed encodings for other messages. Or move optional parameters like `auth` to dedicated messages.

2023-10-25 17:17 UTC, afrind commented
Are we planning to rebase this on main for the remaining issues, or should we close it?

2023-10-25 17:18 UTC, martinduke commented
I think this is rapidly becoming OBE, closing.

2023-10-25 17:18 UTC, closed without merging