Track ID is now specified in SUBSCRIBE.
moq-wg/moq-transport pull request #258
Opened 2023-09-29 04:17 UTC by kixelated

Currently SUBSCRIBE_OK and OBJECT will race. If OBJECT wins, then the subscriber will receive an unknown OBJECT that should be buffered. Moving Track ID to SUBSCRIBE fixes this race and simplifies the flow. See #145

Track ID should be called Subscribe ID but we can always change that later.

2023-09-29 19:15 UTC, suhasHere requested changes

2023-09-29 19:15 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +* Track ID: The track identifier as specified in the SUBSCRIBE REQUEST {{message-subscribe-req}}.
This is fine as long as we have a way to let server propose a trackId in the SubscribeError or replace the one in here.

2023-09-29 19:53 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +* Track ID: The track identifier as specified in the SUBSCRIBE REQUEST {{message-subscribe-req}}.
I've still not seen documentation of a use case in which server-proposed ID is useful.  Can we have an example that we can work through?

2023-09-29 21:48 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* Track ID: The track identifier as specified in the SUBSCRIBE REQUEST {{message-subscribe-req}}.
Yeah, I just don't understand the use-case. 

You could still use the same ID within the CDN (ex. hash of the name). The only difference is that the ID is rewritten on egress instead of ingress. There's a tangible difference between the two because of fanout, but we're talking about encoding a VarInt; it will never show up on profiles.

Could you file an issue and really dive into the problem?

2023-11-04 13:54 UTC, fluffy requested changes
Proposed somethings that I think would allow us to get to consensus on this one.

2023-11-04 13:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  Track ID (i),
I would propose add a subscribe ID

2023-11-04 13:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  Track ID (i),
change to subscribe ID

2023-11-04 13:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  Track ID (i),
change to subscribe ID

2023-11-04 13:54 UTC, fluffy commented on draft-ietf-moq-transport.md
>    Reason Phrase (...),
Add an error code for, use differnt track-id and add a field of proposed track-id

2023-11-04 13:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  Track ID (i),
change to subscribe id

2023-11-04 13:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* Track ID: The track identifier as specified in the SUBSCRIBE REQUEST {{message-subscribe-req}}.
sure simple use case that is given over and over again, eliminate the need to keep track of per hop rewrite information and do the rewrites.

2023-11-04 15:37 UTC, kixelated commented
@fluffy @suhasHere I think #305 should immediately follow and split Track ID into Subscription ID and Track Alias.

2023-11-04 16:00 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +* New Track ID: When not equal to Track ID, the subscriber SHOULD re-issue the SUBSCRIBE with this Track ID instead if possible.
nit, if possible is redundant

2023-11-04 16:00 UTC, suhasHere approved these changes

2023-11-04 16:15 UTC, fluffy approved these changes
This looks good and I really hope we can agree on this compromise. It's not perfect for everyone but I think it is the best we can get to now.

2023-11-06 02:27 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  If this Track ID is already in use, the receiver MUST close the connection with a Duplicate Track ID error ({{session-termination}}).
@fluffy @suhasHere is this okay with you? There could be a race where:

subscriber:
```
send SUBSCRIBE id=69 name=foo
send SUBSCRIBE id=420 name=bar
```

publisher:
```
recv SUBSCRIBE id=69 name=foo
send SUBSCRIBE_ERROR id=69 new_id=420 # publisher remap from 69 -> 420
recv SUBSCRIBE id=420 name=bar
send SUBSCRIBE_ERROR id=420 new_id=1234 # publisher rename from 420 -> 1234
```

subscriber:
```
recv SUBSCRIBE_ERROR id=69 new_id=420
# invalid!: SUBSCRIBE id=420 name=foo
```

The subscriber could wait until it receives the anticipated `SUBSCRIBE_ERROR id=420`. However, I doubt anybody would ever implement this, and you would still need throw an error if you ever receive `SUBSCRIBE_OK id=420`. 

You can avoid this race by sharding publisher/subscriber IDs. Or the publisher can use an unguessable track ID (ex. hash) and it's virtually impossible to ever encounter this, which I think is gud enough.

2023-11-06 02:28 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  If the Track ID is already in use, the receiver MUST close the session with a Duplicate Track ID error ({{session-termination}}).
I added this line. We actually didn't throw an error if you received a SUBSCRIBE for two different tracks using the same ID. I think we can share the error code instead of making a new one.

2023-11-06 03:14 UTC, vasilvv approved these changes
LGTM on the basis of this being an improvement over the current text in the draft.

2023-11-06 09:09 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  If this Track ID is already in use, the receiver MUST close the connection with a Duplicate Track ID error ({{session-termination}}).
It seems like once we have separate the subscribe-id and track-id, this problem goes away ? Perhaps I misunderstand but agree on if a publisher ever suggests reusing a track-id that is already in use for a different track, that is totally borked and the connection should be closed with an error.

2023-11-07 03:54 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  If this Track ID is already in use, the receiver MUST close the connection with a Duplicate Track ID error ({{session-termination}}).
I think the problem still exists when subscribe-id and track-id are split.

The problem is that there's an RTT chasm between the publisher and subscriber. The publisher may send `SUBSCRIBE_ERROR id=1 new_alias=420`, but there was a whole RTT where the subscriber MAY have decided to `SUBSCRIBE id=2 alias=420` for some completely different track (collision). The subscriber can't send `SUBSCRIBE id=2 alias=420` like the publisher is requesting until the existing `SUBSCRIBE id=1 alias=420` in flight has been rejected. 

I think maybe the subscriber could `UNSUBSCRIBE id=1` and then immediately `SUBSCRIBE id=2 alias=420` though thanks to the split. It would still be absolutely fatal if the subscriber receives `SUBSCRIBE_OK id=1`, even after the unsubscribe was sent, because it would be impossible to disambiguate `OBJECT alias=420`.

2023-11-07 16:18 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  If the Track ID is already in use, the receiver MUST close the session with a Duplicate Track ID error ({{session-termination}}).
I'd like to nuance this.  I think a common implementation will be to hash the full track name to get the track id and what we need to say here is that it is only an error if the track-id is reused *and* it does not refer to the same full track name. So if I had two differnt subscribes both to the same track, they could use the same track-id

2023-12-11 00:15 UTC, ianswett commented on draft-ietf-moq-transport.md
> +the subscriber SHOULD specify a Track Alias that is equal to the Subscribe ID.
```suggestion
the subscriber MUST specify a Track Alias that is equal to the Subscribe ID.
```

2023-12-11 18:31 UTC, afrind commented on draft-ietf-moq-transport.md
> +
I think you need to change the condition here.  

C->S: Subscribe (sub-id 1, track alias 1)
S->C: Subscribe Error (sub-id 1, track alias 19, error code=try new id) 
C->S: Subscribe (sub-id 2, track alias 19)
S->C: Subscribe Error (sub-id 2, track alias 19, error code=bad auth)  # sub-id != track alias, but server isn't asking for a resubscribe with new id

2023-12-13 19:47 UTC, suhasHere requested changes

2023-12-13 19:47 UTC, suhasHere commented on draft-ietf-moq-transport.md
"The Track Alias as specified in the SUBSCRIBE message {{message-subscribe-req}}"

2023-12-13 19:47 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +Unless the publisher responsds with a different Track Alias in SUBSCRIBE_ERROR,
s/responsds/responds

2023-12-13 19:47 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
I don't see the need for ``` subscriber MUST specify a Track Alias that is equal to the Subscribe ID ```.

2023-12-13 19:47 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
May be all we need to say is .. 

"Unless the publisher responds with a different Track Alias in SUBSCRIBE_ERROR for the subscriber to retry the SUBSCRIBE with publisher chosen Track Alias"

2023-12-13 19:47 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
I am not understanding why a track alias value must match subscribe id.

2023-12-14 19:40 UTC, ianswett commented on draft-ietf-moq-transport.md
> +that was already in use.
```suggestion
  that was already in use.
```

2023-12-14 19:41 UTC, ianswett commented on draft-ietf-moq-transport.md
> +Unless the publisher responsds with a different Track Alias in SUBSCRIBE_ERROR,
```suggestion
Unless the publisher responds with a different Track Alias in SUBSCRIBE_ERROR,
```

2023-12-15 02:50 UTC, ianswett commented on draft-ietf-moq-transport.md
> +the subscriber MUST specify a Track Alias that is equal to the Subscribe ID.
```suggestion
the subscriber can specify a Track Alias that is equal to the Subscribe ID.
```

2023-12-15 02:51 UTC, ianswett commented on draft-ietf-moq-transport.md
> +
I changed it to a 'can' from a MUST

2023-12-15 02:53 UTC, ianswett commented on draft-ietf-moq-transport.md
> +
The idea would be to prevent some sort of loop where the server keeps coming back with a new subscribe ID, but the text also assumes the MUST I just removed.

2024-01-07 00:06 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
SubscribeId and Track Alias are semantically different concepts. Former is per transaction (subscription) and latter is a short name for Full Track Name. we should remove the last sentence above.

2024-01-07 03:38 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
> S->C: Subscribe Error (sub-id 2, track alias 19, error code=bad auth) # sub-id != track alias, but server isn't asking for a resubscribe with new id

I don't see why this is an error. 

I expected the flow to be something like:

```
C->S: Subscribe (sub-id 1, track alias 1)
S->C: Subscribe Error (sub-id 1, track alias 19, error code=try new track alias)
C->S: Subscribe (sub-id 2, track alias 19)
S->C: Sub Ok 
```

2024-01-10 16:38 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  SUBSCRIBE request {{message-subscribe-req}}.
```suggestion
  SUBSCRIBE message {{message-subscribe-req}}.
```

2024-01-10 17:16 UTC, ianswett commented on draft-ietf-moq-transport.md
> +
```suggestion

```

2024-01-10 17:17 UTC, suhasHere approved these changes

2024-01-10 17:24 UTC, merged