Add subscribe hints
moq-wg/moq-transport pull request #289
Opened 2023-10-17 23:18 UTC by suhasHere

This is a initial PR to get some basic definition of subscription hints. I would like to get us to an agreement for the basic proposal and then discuss further on error codes, edge cases and impacts/interactions with other messages (Sub Fin, RST, UPD)

2023-10-17 23:52 UTC, huitema reviewed
Overall, that's a complicated syntax. You have optional elements, but the TLS1.3 syntax that we use limits how we can specify optional elements. For example, when you write:
~~~
StartPoint Payload {
  Mode (i),
  [GroupCount (i)]
}
~~~
the decoder has an issue. If there are bytes in the message following the encoding of encoding of "mode", do those bytes encode the `GroupCount`, or do they belong to the encoding of the next element in the subscribe command? Your description of "now" says that "The optional parameter `GroupCount`, if specified, MUST be ignored" -- but there the decoder is really in a bind.

This is a problem throughout. You allow extension points, but the syntax is not designed to "skip over" unknown extensions. To be on the safe side, I would change the syntax of the subscription hint to be:
~~~
SUBSCRIPTION HINT {
  HintType (i),
  HintLength(i),
  Payload (...)
}
~~~
If you do that, then you can have optional elements for each payload type. (I would rename "payload" to "hint parameters" or "hintValue".)

Regarding the `HintType`, how is this defined? Suppose that I want to define a new hint type, what do I do? Will there be an IANA registry? Will there be a range of numbers reserved for experimentation?

2023-10-17 23:52 UTC, huitema commented on draft-ietf-moq-transport.md
> +
What has value 0x1? The groupcount parameter?

2023-10-17 23:52 UTC, huitema commented on draft-ietf-moq-transport.md
> +
What has value 0x2? The groupcount parameter?

2023-10-17 23:52 UTC, huitema commented on draft-ietf-moq-transport.md
> +
What has value 0x3? The groupcount parameter?

2023-10-17 23:52 UTC, huitema commented on draft-ietf-moq-transport.md
> +
Why a fixed 8 bits field? we are using varint everywhere.

2023-10-17 23:53 UTC, afrind reviewed
Individual Review

Thanks for this PR, I think it's directionally right but needs a few tweaks for parseability.

2023-10-17 23:53 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Subscription Hints (..) ...
Should it be a separate field or track request parameter?  Track Request Params has group/object sequence already which can maybe be collapsed here one way or another.

2023-10-17 23:53 UTC, afrind commented on draft-ietf-moq-transport.md
> +  HintType (8),
Someone will say "varint", I just wanted to be first.

2023-10-17 23:53 UTC, afrind commented on draft-ietf-moq-transport.md
> +* NOW: Start point for object delivery is set to most recent obect from the current group. The optional parameter `GroupCount`, if specified, MUST be ignored when processing the hint. It has value of
I don't think you can have it be optional and ignored, since there's no flag indicating it's presence or absence other than `mode`.  PREVIOUS and NEXT mean there is a GroupCount and CURRENT and NOW mean there is not.

2023-10-17 23:53 UTC, afrind commented on draft-ietf-moq-transport.md
> +* NOW: Start point for object delivery is set to most recent obect from the current group. The optional parameter `GroupCount`, if specified, MUST be ignored when processing the hint. It has value of
s/obect/object/

2023-10-17 23:53 UTC, afrind commented on draft-ietf-moq-transport.md
> +Additionally subscribers can include only the `StartGroupSequence` and `StartObjectSequence` parameters to indicate "open/unbounded interval" requests, wherin only the absolute start point for object
I think this is not parseable as written - I don't know when there is or isn't an EndGroupSequence or EndGroupObject. 

Maybe something like the following

```
TrackOffset {
  Type (i),  // 0 = Group, 1 = Group and Object
  Group (i),
  [Object (i)]
}

Hint Types = RelativeStart, AbsoluteStart, AbsoluteInterval
RelativeStartPayload {
  Mode (i),
  [GroupCount(i)]
}
Modes = Previous, Next, Current, Now
// Previous and Next have a GroupCount, Current and Now do not have GroupCount.

AbsoluteStartPayload {
  TrackOffset start
}
This would replace the track request params for GROUP SEQUENCE / OBJECT SEQUENCE

AbsoluteIntervalPayload {
  TrackOffset start,
  TrackOffset end
}
```

2023-10-18 00:04 UTC, afrind commented
Can you mark this as Fixes: #245 so it shows as having a PR attached (also possibly 111 and 260)?  Also recommend closing #246 as this replaces it.

2023-10-18 00:09 UTC, afrind commented on draft-ietf-moq-transport.md
> +Additionally subscribers can include only the `StartGroupSequence` and `StartObjectSequence` parameters to indicate "open/unbounded interval" requests, wherin only the absolute start point for object
You can also spell it a little differently, like:

```
Hint Types = Current, Now, RelativeStartPrevious, RelativeStartNext, AbsoluteStart, AbsoluteInterval

CurrentPayload = Empty

NowPayload = Empty

RelativeStartPreviousPayload {
  GroupCount(i)
}

RelativeStartNextPayload {
  GroupCount(i)
}

AbsoluteStartPayload {
  TrackOffset start
}

AbsoluteIntervalPayload {
  TrackOffset start,
  TrackOffset end
}
```

2023-10-18 02:05 UTC, kixelated reviewed
It's really a complicated encoding and yet not flexible. I don't like modes that can't be generalized; we'll end up with spaghetti.

Here's my proposal: https://github.com/moq-wg/moq-transport/issues/245#issuecomment-1767492853

2023-10-18 02:11 UTC, kixelated requested changes

2023-10-18 02:11 UTC, kixelated commented on draft-ietf-moq-transport.md
> +
+1 a registry/table would be clearer.

2023-10-18 02:11 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* NOW: Start point for object delivery is set to most recent obect from the current group. The optional parameter `GroupCount`, if specified, MUST be ignored when processing the hint. It has value of
Good catch.

2023-10-18 03:33 UTC, suhasHere commented
> Here's my proposal: [#245 (comment)](https://github.com/moq-wg/moq-transport/issues/245#issuecomment-1767492853)

I feel #245 proposal is more ambiguous though.  I agree we can make the proposed ending in this PR to make it easier to encode/decode.

I have to get higher level idea agreed upon

1. There are subscription hints. 2 hints are defined in this PR  a) StartPoint b) Interval
2. There may be hints we might want to add in future and hence a Hint structure identifies a type and value
3. StartPoint hint can support 4 modes. These modes are only applicable when the HintType is StartPoint 
4. Interval hint is totally separate hintType that defines ranges of groups/objects

2023-10-18 03:34 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Mode (i),
this is a not a mode in a mode. Its mode in a given hintType called StartPoint

2023-10-18 03:35 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
0x1 correspond to Mode and not the groupCount. I can clarify the same.

2023-10-18 03:35 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
0x2 correspond to Mode and not the groupCount. I can clarify the same.

2023-10-18 03:35 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
0x3 correspond to Mode and not the groupCount. I can clarify the same.

2023-10-18 03:36 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
I am fine with varint. I didn't see it being needed in this case.

2023-10-18 03:37 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Subscription Hints (..) ...
yes , once we get the hints agreed upon, i will do a follow up PR to change Track Params. Trying to keep the PR focussed.

2023-10-18 03:39 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +* NOW: Start point for object delivery is set to most recent obect from the current group. The optional parameter `GroupCount`, if specified, MUST be ignored when processing the hint. It has value of
Mode is the flag that defined the presence and absence. The text is trying to say that, if for mode "Now", some one encodes GroupCount, don't process that param than treating it as error.

I am not sure its ambiguous, but happy to take suggestions on how to make it clear.

2023-10-18 03:45 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +- If the GroupCount cannot be satisfied, the publisher MUST send SUBSCRIBE ERROR message with an appropriate error code (TODO: need to define this).
yes , agree with the analysis. I did had it written originally aligning so, but not able to remember why i decided to go otherway.

But, i will update it.

2023-10-18 03:51 UTC, suhasHere commented
> Regarding the `HintType`, how is this defined? Suppose that I want to define a new hint type, what do I do? Will there be an IANA registry? Will there be a range of numbers reserved for experimentation?

Having a registry is the idea and I was thinking once we get to agreement of Hint strucutres , then we can follow with defining error codes, registries for types and  cleaning up track request params

2023-10-18 03:54 UTC, suhasHere commented
> SUBSCRIPTION HINT {
>   HintType (i),
>   HintLength(i),
>   Payload (...)
> }

Payload(b) is defined to have len and value .  Here is the definition as defined in the draft today 
**x (b): : Indicates that x consists of a variable length integer, followed by that many bytes of binary data.**

2023-10-18 04:53 UTC, kixelated requested changes

2023-10-18 04:53 UTC, kixelated commented on draft-ietf-moq-transport.md
> +
It's the same encoding for values < 2^6 , so you might as well specify a varint.

2023-10-18 04:53 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  Mode (i),
What I'm suggesting is that you merge `Mode` and `HintType`. So there would be 5 possible values, instead of 4+1. The parameters for each would be based on the type; there would be a `group` for PREVIOUS/NEXT and a start/end pair for INTERVAL.

2023-10-18 04:53 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* NOW: Start point for object delivery is set to most recent obect from the current group. The optional parameter `GroupCount`, if specified, MUST be ignored when processing the hint. It has value of
What Alan is trying to say is that there's no way to specify "GroupCount" when mode=CURRENT or NOW. The field is optional and the mode determines if the field is present, or at least that's our interpretation. If the field is always present and MUST be ignored like this text specifies, then `[GroupCount (i)]` shouldn't be wrapped in brackets.

2023-10-18 04:53 UTC, kixelated commented on draft-ietf-moq-transport.md
> +Additionally subscribers can include only the `StartGroupSequence` and `StartObjectSequence` parameters to indicate "open/unbounded interval" requests, wherin only the absolute start point for object
Yeah, the bracket notation that QUIC uses doesn't encode if a field is present.

```
[EndGroupSequence(i)]
```

Needs to be written as something like:

```
EndGroupPresent (i) // 1 or 0
[EndGroupSequence(i)]
```

This is quite wasteful, which is why you generally have flags or modes to specify if multiple fields are present. Or a special meaning for 0.

2023-10-18 04:53 UTC, kixelated commented on draft-ietf-moq-transport.md
> +| 0x2        | Interval                |
nit: `Range` instead of `Interval`

2023-10-18 05:28 UTC, suhasHere commented
So pushed few more commits cleaning up somethings and considering suggestion from Alan on TrackOffset and removing text on error.  

Would love to hear feedback on the whole text.

2023-10-18 15:10 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Mode (i),
Yeah, this comment I left from the previous draft shows one possible way to merge Mode and HintType - https://github.com/moq-wg/moq-transport/pull/289#discussion_r1362945991.  I think I like that slightly better because it has only one extension axis, and it's more compact, but I can live with this too.

2023-10-18 15:45 UTC, huitema reviewed
This is progressing. Apart from the comments below, I would take a hard look at the extension points. Do we need them, or can we just say that "a future version of this spec may define more hint types"?

This would be in line with only having extensions by version number, negotiated during the connection.

2023-10-18 15:45 UTC, huitema commented on draft-ietf-moq-transport.md
> +  Mode (i),
I was going to make the same suggestion. We can certainly collapse these two layers. We would end up with Hints being a choice of "Now, Current, Previous, Next, Absolute, Range".

2023-10-18 15:45 UTC, huitema commented on draft-ietf-moq-transport.md
> +~~~
The syntax seems uselessly complicated. I would remove the type, just define:
~~~
TrackOffset {
  GroupSequence (i),
  ObjectSequence (i)
}
~~~
And set Object to 0 if the range shall include the whole group.

You also need to specify whether the end is inclusive or exclusive. I like exclusive, because it allows to set the end to "Group=N+1, Object=0", which would mean "until the end of Group N" without knowing in advance how many objects there are in group N.

2023-10-18 16:12 UTC, afrind commented on draft-ietf-moq-transport.md
> +~~~
> And set Object to 0 if the range shall include the whole group.

Thanks @huitema for this suggestion, it makes much more sense.

`group=7, object=0` vs `type=0, group=7`
`group=9, object=17` vs `type=1, group=9, object=17`

2023-10-18 18:18 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +The `RelativeStartPoint` subscription hint identifies a starting point relative to publisher's view of the ongoing state of the track for delivering objects. A publisher's current state of the track
I wonder there is any way a subscriber can know this info. Whatever publisher says in the OBJECT message is considered to be the start for all relative requests. isn't it ?

2023-10-18 18:21 UTC, afrind commented on draft-ietf-moq-transport.md
> +The `RelativeStartPoint` subscription hint identifies a starting point relative to publisher's view of the ongoing state of the track for delivering objects. A publisher's current state of the track
My thought was that the first object received might not be the first object sent by the publisher (due to out of order delivery, congestion, etc), hence it might be good for the publisher to indicate to the subscriber what they are going to get.

2023-10-18 20:03 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +The `RelativeStartPoint` subscription hint identifies a starting point relative to publisher's view of the ongoing state of the track for delivering objects. A publisher's current state of the track
the thing is , when you send subscribe , there might not be any publisher started publishing .. so info in OK is not sufficient .. 
May be we need a bit in the object header, that if set means its the first object in the track

2023-10-18 21:57 UTC, afrind commented on draft-ietf-moq-transport.md
> +The `RelativeStartPoint` subscription hint identifies a starting point relative to publisher's view of the ongoing state of the track for delivering objects. A publisher's current state of the track
> the thing is , when you send subscribe , there might not be any publisher started publishing .. so info in OK is not sufficient ..

This makes sense too. Optional flag in SUBSCRIBE OK?   I could live with punting this feature also for now.

2023-10-18 22:19 UTC, huitema approved these changes
Just one minor comment. I think this is pretty much ready.

2023-10-18 22:19 UTC, huitema commented on draft-ietf-moq-transport.md
> +
I would think that `ObjectSequence` set to 0x0 implies ~until the end~ *from the beginning* of the group identified in `GroupSequence`.

2023-10-18 22:26 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +  Number of Hints (i),
Could you explain what does it mean to have multiple hints?  Like, semantically, if I supply both a relative and an absolute offset, what should happen?

2023-10-18 22:26 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +{: #moq-transport-relative-start-next-hint format title="MOQT RelativeStartNext Hint"}
What is the relationship between Current, RelativeStartPrevious with count 0, and RelativeStartNext with count 0?  Are they identical? Is count 0 disallowed by the protocol?

2023-10-18 22:26 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +The `AbsoluteStart` subscription hint allows subscribers to specify an absolute point in the track to start delivering objects, as indicated by the `TrackOffset` hint attribute.
Can `TrackOffset` be in the future? If so, please document the expected behavior.

2023-10-18 22:26 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +| 0x3 - 0xFF | Reserved for future use |
(ignore this, somehow submitted outdated comment)

2023-10-18 22:34 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +The `RelativeStartPoint` subscription hint identifies a starting point relative to publisher's view of the ongoing state of the track for delivering objects. A publisher's current state of the track
yes, let's open an new issue to add  a flag to the OBJECT and also have some info on OK message

2023-10-18 22:49 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Number of Hints (i),
i was thinking if we define a new hint type that is not related to start point in future, allowing it to be useful.  OTOH i wonder if we can make a request that if there exists both relative and absolute start point, have absolute take preference always ?

I don't know why would one define, but we need to define what happens when one does so

2023-10-18 22:54 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +{: #moq-transport-relative-start-next-hint format title="MOQT RelativeStartNext Hint"}
my thinking is count of 0 for RelativeStartPrevious gives the current group. Do you see if there is any issues with that ? We can have GroupCount > 0 always too ..

2023-10-18 22:55 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +The `AbsoluteStart` subscription hint allows subscribers to specify an absolute point in the track to start delivering objects, as indicated by the `TrackOffset` hint attribute.
yes, it can be .. What were you thinking we should document ?

2023-10-18 23:47 UTC, afrind reviewed
Individual Review

2023-10-18 23:47 UTC, afrind commented on draft-ietf-moq-transport.md
> +OPEN QUESTION: Should we disallow multiple hints ?
My preference is for only a single hint.  The current hint set can be mixed in non-sensical ways.

2023-10-18 23:47 UTC, afrind commented on draft-ietf-moq-transport.md
> +  HintValueLength (i),
As currently defined, the length is not needed because the length of all hint types is known.

2023-10-18 23:47 UTC, afrind commented on draft-ietf-moq-transport.md
> +The end track offset of the range is exclusive.
So that's:

[0, 0], to [2, 0] = all of groups 0 and 1
[0, 0], to [2, 1] = all of groups 0 and 1, and group 2, object 0, 

etc?

2023-10-18 23:47 UTC, afrind commented on draft-ietf-moq-transport.md
> +The `AbsoluteStart` subscription hint allows subscribers to specify an absolute point in the track to start delivering objects, as indicated by the `TrackOffset` hint attribute.
Maybe - 1) state that it is intended that subscribers can ask for a future offset (similar to RelativeStartNext with a positive number), and then specify if the publisher needs to wait for those objects to be available to issue SUBSCRIBE OK, or it issues a SUBSCRIBE OK immediately?  What if those objects never materialize?

2023-10-19 02:49 UTC, kixelated requested changes
I wanted to +1 Alan's comment but I think it got buried in changes. We will eventually need the selected start/end group/object echoed in SUBSCRIBE_OK. Otherwise I don't think you can actually use these relative hints; there's a bunch of edge cases and races.

2023-10-19 02:49 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  Number of Hints (i),
I really don't want multiple hints. It's not clear how overlapping hints are supposed to interact, which makes it implementation specific.

2023-10-19 02:49 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  HintValueLength (i),
Yeah, you only need the length if you want to support unknown HintTypes. However, I think it should just be a protocol violation if you use an unknown type, so you don't need the length.

2023-10-19 02:49 UTC, kixelated commented on draft-ietf-moq-transport.md
> +`Now` subscription hint specifies the start point for object delivery from the most recent object of the current group.  Now hint type defines no further hint attributes.
Does this include the most recent object? If so, the latest object could have been generated hours ago, so "now" is a little misleading.

I would rename:

| old | new |
|-|-|
| Current | CurrentGroup |
| Now | CurrentObject |

2023-10-19 02:49 UTC, kixelated commented on draft-ietf-moq-transport.md
> +`RelativeStartPrevious` subscription hint specifies the start point for object delivery from an earlier group relative to the current group. The  `GroupCount` hint attribute specifies the number of g
Would `RelativeStartPrevious GroupCount = 0` be identical to `Current`?

Can you clarify if this is the case, and give an example?

2023-10-19 02:49 UTC, kixelated commented on draft-ietf-moq-transport.md
> +`RelativeStartNext` subscription hint specifies the start point for object delivery to a future group relative to the current group. The `GroupCount` hint attribute specifies the number of groups to
Would `RelativeStartNext GroupCount = 0` be identical to `Current`?

Can you clarify if this is the case, and give an example?

2023-10-19 02:49 UTC, kixelated commented on draft-ietf-moq-transport.md
> +{: #moq-transport-relative-start-next-hint format title="MOQT RelativeStartNext Hint"}
It's just confusing and you need to clarify at least. This is a classic off-by-one bug waiting to happen. It also might make caching more difficult because there's 3 different ways to request the latest group.

IMO
`RelativeStartPrevious` is relative to `current`
`RelativeStartNext` is relative to `current+1`
`Current` is removed in favor of `RelativeStartPrevious count=0`

2023-10-19 02:49 UTC, kixelated commented on draft-ietf-moq-transport.md
> +
+100

How are you supposed to request the first object from a group otherwise? What is even the use-case of requesting the max object from an old group?

2023-10-19 03:56 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +{: #moq-transport-relative-start-next-hint format title="MOQT RelativeStartNext Hint"}
I don't see it causes implementation confusion or off-by-one bug. The semantics are clear and yes, more text can be added, if needed.  

```
                          5  4  3  2  1                           5  4  3  2  1
<--------Previous -------> CURRENT (0) <-------- Next ---------->

```

2023-10-19 04:01 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +`RelativeStartNext` subscription hint specifies the start point for object delivery to a future group relative to the current group. The `GroupCount` hint attribute specifies the number of groups to
The existing text does say the count needs to be happen from the current group as anchor. That seems pretty clear though.

2023-10-19 04:02 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +`Now` subscription hint specifies the start point for object delivery from the most recent object of the current group.  Now hint type defines no further hint attributes.
I tend to like Now better than CurrentObject since it feels more suited when used with subscribe. CurrentObject makes me wonder if it is more befitting to Fetch/Get semantics (#111 )

2023-10-19 05:15 UTC, huitema commented on draft-ietf-moq-transport.md
> +The end track offset of the range is exclusive.
Yes, seems right. The problem is that if you want inclusive, you have to write:

[0, 0], to [1, 7563] = all of groups 0 and 1

But you can only do that if you know in advance that group 1 has exactly 7563 objects -- and that's no obvious.

2023-10-19 05:22 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +The end track offset of the range is exclusive.
that's true ..  as a mental model, it helps me build nice breakpoints between end of one range and start of new range in a easier way ..

2023-10-19 21:42 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +The `RelativeStartPoint` subscription hint identifies a starting point relative to publisher's view of the ongoing state of the track for delivering objects. A publisher's current state of the track
TO DISCUSS LIVE

2023-10-19 21:42 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
DISCUSS LIVE

2023-10-19 21:42 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Number of Hints (i),
DISCUSS LIVE

2023-10-19 21:42 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +{: #moq-transport-relative-start-next-hint format title="MOQT RelativeStartNext Hint"}
DISCUSS LIVE

2023-10-19 21:43 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +The `AbsoluteStart` subscription hint allows subscribers to specify an absolute point in the track to start delivering objects, as indicated by the `TrackOffset` hint attribute.
DISCUSS LIVE

2023-10-19 21:43 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +`RelativeStartNext` subscription hint specifies the start point for object delivery to a future group relative to the current group. The `GroupCount` hint attribute specifies the number of groups to
DISCUSS LIVE

2023-10-20 02:00 UTC, afrind reviewed
Trying to summarize what we need to discuss live:

1. Do the use cases mentioned by Luke in 245 need to be covered now?
2. One hint or multiple hints?
3. Is RelativeStart(Next/Prev), Group=0 the same as Current?
3a. If so, should those be disallowed?
4. How should a publisher respond to a hint in the future?
5. Does TrackOffset ObjectSequence=0 mean "from the beginning" or "til the end" of the group?

Anything else?

2023-10-20 03:50 UTC, suhasHere commented
> 1. Do the use cases mentioned by Luke in 245 need to be covered now?

This is very vague given the length of 245. Could you please summarize the use-cases to help focus the discussion.

In the order of small to big, my suggestion of the order would be "3, 4, 5, 3,  2, 1 "

2023-10-20 05:00 UTC, afrind commented
> Given the length of 245. Could you please summarize the use-cases to help focus the discussion.

There are 4 examples right at the end of 245, I copied them in this review comment:

https://github.com/moq-wg/moq-transport/pull/289#pullrequestreview-1685348042

We can discuss tomorrow.

2023-10-20 17:36 UTC, fluffy commented
Alan proposed we use 6 parameters.

Start Object
Start Group
Start relative / absolute flag 

End Object
End Group 
End relative / absolute flag 

Preference for not two ways to say same thing. Use 0 to indicate current. Offset encoding. 

You can subscribe to the track twice with two different hints if that is what you want. 

Seems good consensus on call for this.

2023-10-20 18:10 UTC, kixelated commented
My proposal is 4 parameters, combining the flag with the value:

- Start Group + Relative/Absolute Flag
- Start Object + Relative/Absolute Flag
- End Group + Relative/Absolute Flag
- End Object + Relative/Absolute Flag

I'm using the lower bits of the VarInt to save some bytes and make parsing easier. Otherwise you have to deal with missing the corresponding sequence/mode parameter.

I think it's even easier if these 4 VarInts are just encoded as part of SUBSCRIBE instead of being parameters. There would be a None flag if you don't want an end group and/or object.

2023-10-20 18:38 UTC, suhasHere commented
> My proposal is 4 parameters, combining the flag with the value:
> 
> * Start Group + Relative/Absolute Flag
> * Start Object + Relative/Absolute Flag
> * End Group + Relative/Absolute Flag
> * End Object + Relative/Absolute Flag
> 
> I'm using the lower bits of the VarInt to save some bytes and make parsing easier. Otherwise you have to deal with missing the corresponding sequence/mode parameter.
> 

Even with flags embedded, the logic is exactly same. Either you need to handle missing parameter or a flag bits set to a certain value. May be we can add this optimization later too ?

> I think it's even easier if these 4 VarInts are just encoded as part of SUBSCRIBE instead of being parameters. There would be a None flag if you don't want an end group and/or object.

+1 on making it part of Subscribe.

2023-10-20 18:47 UTC, kixelated commented
Regardless of the approach, I think these are the use-cases we MUST support:

| start group | start object | end group | end object | notes |
|-|-|-|-|-|
| absolute | 0 | fin | fin | start at timestamp in catalog |
| absolute | absolute | fin | fin | reconnect from max object |
| absolute | 0 | absolute | fin | repopulate group cache (unknown end) |
| absolute | absolute | absolute | absolute | repopulate object cache (known end) |
| latest-N | 0 | fin | fin | live with initial buffer of at most N groups |
| latest | latest-N | fin | fin | live with initial buffer of at most N objects  |
| latest+1 | 0 | fin | fin | wait for next sync point |

I think these are use-cases worth considering:

| start group | start object | end group | end object | notes |
|-|-|-|-|-|
| latest-N | 0 | latest-M | fin | fetch the latest M-N groups (ex. clip) |
| latest+N | 0 | fin | fin | start at a group further in the future |
| latest-N | 0 | latest+M | fin | subscribe for M-N groups pending a resubscribe (keep-alive) |
| absolute | absolute | latest | latest | fetch the track as it currently exists (live unsupported)  |

And not mentioned in this PR, but I do think we need UNSUBSCRIBE hints.

| end group | end object | notes |
|-|-|-|
| latest | latest | end immediately |
| latest | fin | end after current group |
| absolute | fin | end after target group (session migration) |
| latest+M | fin | end after future group (session migration) |
| start group | start object | end before next SUBSCRIBE starts (deduplication?) |

2023-10-20 18:53 UTC, kixelated commented
New proposal:

```
SUBSCRIBE {
  Start Group + Absolute/Relative/Future (i)
  Start Object + Absolute/Relative/Future (i)
}

UNSUBSCRIBE {
  End Group + Absolute/Relative/Future (i)
  End Object + Absolute/Relative/Future (i)
}
```

We'll need to handle multiple subscribes and unsubscribes though, probably with a subscription ID. ex. You might want to cancel a future UNSUBSCRIBE, replacing it with a later future UNSUBSCRIBE or perhaps an immediate one.

2023-10-20 19:46 UTC, huitema commented
In addition to what is summarized above, we had a discussion about the way to express relative ranges. In the case of the start hint, the well understood scenarios that I heard are:

* start at the current point (current group, current object)
* start at the beginning of the current group (e.g., because the receiver needs all the frames from the beginning of the current group to synchronize its decoder)
* start at the beginning of the next group (e.g., because the receiver does not want to process old frames, and would rather start clean on a group start)

We can make it more complicated, and we have proposals such as:

* start N (groups, objects) before the current one (in the past)
* start N (groups, objects) after the current one (in the future).

I think that these relative offsets bring a lot of complexity, and a lot of corner cases. They are somewhat undefined, because the subscriber does not know what the current group or object is. If it knew, it could just ask for a specific start point. The combination of groups and objects is a bit weird, because the subscriber does not know how many objects there are in the past groups. The syntax allows for silly requests, like "start 1,000,000 groups in the past", or requests that are latent DOS attack like "start 1,000,000 groups in the future", which means "keep state in memory forever". There is a potential simplification there...

2023-10-21 03:32 UTC, suhasHere commented
I want to keep the scope simple and focussed. When i presented on Subscription hints, there were few real use-cases that had a need for hints 
   - User joining a mid cal
   - User reconnecting and joining at a known point
   - User want to buffer a few seconds from past to keep the player go smoothly
   - User asking for range of frames and be done with it as catch up
   
Can we define a system that works for all possible combinations ever - Oh YEAH .. But do we really need it - I DOUBT IT

I am waiting on Alan's proposal for the promised simplification. @afrind  no pressure :-)

2023-10-21 03:43 UTC, afrind commented
I was pretty busy today but have been written up what we discussed during the call - using 6 track request parameters offering the full range of options that are available in this PR as is.  By using defaults when a param is omitted, there was only one invalid combination, which I like.  The logic to determine what group and object to actually start serving is about 20 lines of pseudo code, which I added as an appendix.

I'm not sure what to make of the discussion on this PR.  I'll write a second PR that is simpler and just includes the 4 basic modes, and maybe something for range.  Stay tuned.

Would it be better to submit both as separate PR's, and leave this proposal as is, or should I push what we discussed this morning here?

2023-10-21 03:58 UTC, suhasHere commented
> I'm not sure what to make of the discussion on this PR. I'll write a second PR that is simpler and just includes the 4 basic modes, and maybe something for range. Stay tuned.
> 
> Would it be better to submit both as separate PR's, and leave this proposal as is, or should I push what we discussed this morning here?

Can't both the merged into 1 commit ?

2023-10-21 19:53 UTC, ianswett reviewed
I prefer Proposal 2, but I can live with Proposal 1 as well.

2023-10-21 19:53 UTC, ianswett commented on draft-ietf-moq-transport.md
> +RelativeNext (0x2): The specified group is an index relative to the `Current
I thought we decided it wasn't clear we needed this, except maybe there was interest in the 0 case when you want to start at the next group.

2023-10-21 19:53 UTC, ianswett commented on draft-ietf-moq-transport.md
> +PROPOSAL 2: Simpler, trying to follow discussion on the PR through the day.
Overall, I prefer this, because I think it's easier to reason about and there are fewer edge cases.

2023-10-21 20:01 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  End Group Sequence(i),
If one makes both of these the max value, does that indicate an open ended subscription?

2023-10-21 20:35 UTC, fluffy commented
Commenting on Luke's table of use cases:

Love this way of enumerating and sorting the use cases. Thanks. All the use case I think are critical are covered in the first table and nothing that I did not care about seemed like it was going to complicated implementations so my first reaction was YES. But looking at it, we were getting close to covering 100% of all the cases and since relays are likely to upgrade slower than clients, I just came down to we should just support all the possible combinations even if it is not clear  there is s use case for it today - that will actually make implementations simpler. I think the proposed solutions are starting to look like they do all the cases anyways. By all the cases, I mean a subscribe can 

Start at absolute or relative for both group and object. Relative can have delta to current.  

Start at absolute or relative or fin for both group and object. Relative can have delta to current.

2023-10-21 20:40 UTC, fluffy commented
On the topic of do we need unsubscribe hints .... 

How I think of it is subscribe installs some state on the relay or publisher telling it what to do. It can say what the first and last object is that should be forwarded. However, I think as unsubscribe as the message that removes all that state. 

If we start making unsubscribe be "forward until you see object X" then remove all the state, we get into questions like what happens if object X-1 arrives after X. 

That said, I do agree with the use case that Luke is getting at of things like. Client was subscribed to something forever, but now I only want to be subscribe up to the end of the current group so that the client can do a clean switch over to some different subscription at the group boundary

2023-10-21 21:28 UTC, fluffy requested changes
Both of these proposals don't meet the requirement Luke had in his MUST table of starting at latest group and latest-N object.

2023-10-21 21:28 UTC, fluffy commented on draft-ietf-moq-transport.md
> +START/END_OBJECT defaults to `Current Object` + 1 if not specified.  In all
I think the "+1" on current object here is a problem. For audio where you don't send packets, you often want the last packet even so that you can see things are in VAD ( Voice Activity Detection ) mode where you are not sending audio. It's only a small tweek to proposal but given there no is way to specify the relative object, I would want therelative object to be the current, not the current+1.

2023-10-21 21:28 UTC, fluffy commented on draft-ietf-moq-transport.md
> +| Now       | 0x1   | Current     | Current + 1  |
Again, I think I would want current  , not current +1 in object. We could add another enum value to have both 

Recent | 0xXXX| Current | Current 
and 
Now | 0xXXX | Current | Current + 1

2023-10-21 21:28 UTC, fluffy commented on draft-ietf-moq-transport.md
> +
I'm not keen on adding code like to the draft. If the design is so hard to explain in text that we need code like this, then the design is too complicated. 

A big part of why I don't like code like this is inevitably over time it gets slightly out of sync with the normative code in the draft but lots of people use it and then you have huge conflicts on what the normative specification is and that makes interoperability worse.

2023-10-21 21:28 UTC, fluffy commented on draft-ietf-moq-transport.md
> +START/END_OBJECT defaults to `Current Object` + 1 if not specified.  In all
One not huge change to fix this would be to say that if start/end_object was zero or a positive number, then it was the the absolute object number. If it was negative, then it is a delta applied to the current object +1. ( So a value of -1 gives you the current object, -2 the object before that, and so on ). 

This all feels like it is getting too clever and too complicated.  Not sure I like it.

2023-10-21 21:39 UTC, fluffy commented
I was thinking about use case for things like text media some of the stuff with the game moves draft that are not audio and video.  It is pretty common to  want to be able to get the last N things in a group first then later go get the earlier things in a group. The usual rest style pagination type thing where. Imagine you had a group where each object was a message in a chat, you might only want the most recent 10 messages but then when user scrolled back, to get the rest. 

The more I thought about this, I think we have a requirement for 

start group | start object | end group | end object | notes
-- | -- | -- | -- | --
absolute | latest-N | absolute | latest | Get last N object in a given group

2023-10-21 21:45 UTC, kixelated commented
> On the topic of do we need unsubscribe hints ....

Yeah, I'm thinking we should use RESUBSCRIBE instead of adding hints to UNSUBSCRIBE. UNSUBSCRIBE would always be an immediate and cleanup any state, while RESUBSCRIBE would be used to update the start/end bounds.

2023-10-21 22:08 UTC, fluffy commented
I took the liberty of adding a 3rd proposal to the PR but did not change anything else in the PR.

2023-10-21 22:09 UTC, fluffy commented
> > On the topic of do we need unsubscribe hints ....
> 
> Yeah, I'm thinking we should use RESUBSCRIBE instead of adding hints to UNSUBSCRIBE. UNSUBSCRIBE would always be an immediate and cleanup any state, while RESUBSCRIBE would be used to update the start/end bounds.

+1 - that does seem like it will be a very good way to deal with it

2023-10-21 22:28 UTC, kixelated commented
@fluffy I wrote this up on my phone before noticing your commit. It's basically your proposal 3, but not using optional parameters.

It would be encoded as:

```
SUBSCRIBE {
  ...
  start_group_hint: (i)
  start_object_hint: (i)
  end_group_hint (i)
  end_object_hint (i)
  ...
}
```

I really like that Alan wrote some pseudo-code, although I agree that it shouldn't be in the final draft. The devil is in the details with this encoding, and I think this scheme is both the simplest and the most powerful.

```python
# Each hint is a VarInt, where the lower two bits specify the mode
def resolve_hint(hint, latest):
  match hint & 0x3:
    case 0x0: # absolute
      return hint >> 2
    case 0x1: # relative
      return max(latest - hint >> 2, 0)
    case 0x2: # future
      return latest + hint >> 2 + 1
    case 0x3: # none
      return Infinity
    
# Convert subscribe hints on the wire into absolute subscribes
def subscribe_hint(start_group, start_object, end_group, end_object): 
  # latest_group: returns max group in cache
  # latest_object: returns max object in cache for given group
  # both will be async when relay has no active subscription 
  start_group = resolve(start_group, latest_group())
  start_object = resolve(start_object, latest_object(start_group))
  end_group = resolve(end_group, latest_group())
  end_object = resolve(end_object, latest_object(end_group))

  # now they can be used with should_serve
  return ( start_group, start_object, end_group, end_object )

# Called for each object (same for all proposals)
def should_serve(obj, start_group, start_object, end_group, end_object)
  if obj.group < start_group or obj.group > end_group:
    return false
  elif obj.group == start_group and obj.sequence < start_object:
    return false
  elif obj.group == end_group and obj.sequence > end_object:
    return false
  else:
    return true 

```

2023-10-21 22:41 UTC, kixelated commented
And I thought it would be a bug to specify start_object=none with my encoding, but it actually seems like a valid use-case.

start group | start object | end group | end object | notes
-- | -- | -- | -- | --
none | 0 | none | none | Check if a track exists

You would get a SUBSCRIBE_OK if the track exists, but the subscription won't actually do anything. It kinda seems useful for specifying intent to, like for pre-warming the cache.

2023-10-21 22:44 UTC, afrind reviewed
Thanks for the feedback and the additional proposal. I think there's a few details that need to be filled in if that's the direction folks want to take.

2023-10-21 22:44 UTC, afrind commented on draft-ietf-moq-transport.md
> +START/END_OBJECT defaults to `Current Object` + 1 if not specified.  In all
I added the +1 because `Current Object` implies that every hop needs to cache the latest object, or refetch it on subscribe, and I wasn't sure if that was the intention. So "Now" was intended to mean - I'm subscribed and don't need any old objects, just give me the new ones.

> If it was negative

varints are non-negative

> This all feels like it is getting too clever and too complicated. Not sure I like it.

That's also where I ended up when I finished the PR.

2023-10-21 22:44 UTC, afrind commented on draft-ietf-moq-transport.md
> +  End Group Sequence(i),
I think that's the net effect, but it's preferred to not use RANGE to issue open ended subscriptions.

2023-10-21 22:44 UTC, afrind commented on draft-ietf-moq-transport.md
> +
I wrote the code before I wrote the PR, so I thought I would include it to help illustrate.  It doesn't have to stay.  The design might be too complicated.

2023-10-21 22:44 UTC, afrind commented on draft-ietf-moq-transport.md
> +| START_GROUP_MODE   | 0x1   | No       | Relative   |
Looks like you are using just two modes (relative and absolute), with a signed delta.

2023-10-21 22:44 UTC, afrind commented on draft-ietf-moq-transport.md
> +delta.
We need to express a signed integer encoding since varints don't have one, but maybe this is easier.

2023-10-21 22:44 UTC, afrind commented on draft-ietf-moq-transport.md
> +| END_GROUP    | 0x6   | No       | Inf                 |
I assume you intended the start and end group parameters to be consistently named (either START_GROUP/END_GROUP or START_GROUP_DELAT/END_GROUP_DELTA)?

2023-10-21 22:44 UTC, afrind commented on draft-ietf-moq-transport.md
> +| START_OBJECT_DELTA | 0x4   | No       | 0 |
I had gone on the assumption that I tried to validate in the meeting, which is that relative objects only make sense in the current group, relative to the current object.  I'm a bit surprised to see we need "Nth from end" of a group, given that at least one of the functions of group is a join point.

This encoding also allows some invalid things to be specified, like starting at future objects in old groups: 

START_MODE=Relative, START_GROUP_DELTA=-100, START_OBJECT_MODE=Relative, START_OBJECT_DELTA=100  ==> Start 100 objects after the end of a group that ended a long time ago.

2023-10-22 00:07 UTC, suhasHere commented
> Yeah, I'm thinking we should use RESUBSCRIBE instead of adding hints to UNSUBSCRIBE. UNSUBSCRIBE would always be an immediate and cleanup any state, while RESUBSCRIBE would be used to update the start/end bounds.

My proposal in one of the authors call was Subscribe Update message.

2023-10-22 00:16 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +~~~
My least favorite right now is proposal -1 .. This basically looks like original proposal is (which is one varint encdoding 6 values) expanded into 6 different parameters.

2023-10-22 00:21 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +PROPOSAL 3: More explicit
thing i like about this proposal is having just 2 dimensions to define the combinations of things. This also seems pretty flexible.

I feel we don't need signed value but rather a  direction  indicator instead to compute the resultign object/group -  Increasing/Decreasing Delta 

Having thought about it a bit more , I seem to agree with @fluffy  on Relay update cycles and thus supporting flexibility is a good way to move.

2023-10-22 00:22 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +| START_OBJECT_DELTA | 0x4   | No       | 0 |
START_MODE=Relative, START_GROUP_DELTA=-100, START_OBJECT_MODE=Relative, START_OBJECT_DELTA=100

The way I read it as
Go back 100 groups from the current group, then start at the 100th   from the beginning of the group

2023-10-22 00:25 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +PROPOSAL 3: More explicit
One clarification needed in the text is ,

One should compute target group index first  and then compute the object index. 
If the start_group mode is relative, then either use +ve or -ve delta from the current group to compute the target group
if the start_group mode is absolute, then target group is the group in the request

Same thing is one for target object index.


if

2023-10-22 01:11 UTC, huitema commented on draft-ietf-moq-transport.md
> +| Now       | 0x1   | Current     | Current + 1  |
I think that the real "relative" cases for video are:

- current group, current object (now)
- current group, first object of current group (previous)
- next group, first object (next)

There might be a specific problem for audio, in which receiving N packets before the current one allows for fast re-synchronization of the audio codec. Whether that requires asking for "group N-1" is debatable, but the syntax would be "N objects before current", and treated really like an optional hint.

The option "125 groups in the future" feels like a foot gun, not sure that we need it.

2023-10-22 01:21 UTC, fluffy commented on draft-ietf-moq-transport.md
> +START/END_OBJECT defaults to `Current Object` + 1 if not specified.  In all
True but we can make  a SignedVarInt if we need one. Just about everywhere but QUIC VarInts are signed and UnsignedVarInts are not :-)

2023-10-22 01:22 UTC, fluffy commented on draft-ietf-moq-transport.md
> +
It did help me understand the definition of how it works.

2023-10-22 01:41 UTC, fluffy commented
So @kixelated proposal in the thread above that is similar to mine just seems better than what I proposed.  It covers all the cases, it is easy to describe and validate work and does not have a bunch of uses cases. 

I would put in a very weak argument for instead of taking the bottom two bits to encode the (absolute, relative, future, none ) , instead just put that into it's own VarInt. I would not argue very much for that because this is all going to get put in 5 lines of code I will never look at again and it's does not turn up on the wire in something that has to be small. Probably the worst part of is is someone looking at network dump might be confused but that just means the wireshark dissector needs to know about how to the >>2 works. I'd be totally fine with proposal as is. 

Some strong points I see for this:
1) we could merge it by Monday 
2) It covers all the uses case we can imagine now plus has a high chance of  covering the future cases we can not imagine now
3) It is simple to understand, think about, and test

2023-10-22 01:45 UTC, fluffy commented on draft-ietf-moq-transport.md
> +delta.
it had not really occurred to me we would not end up having a signed but yes, make sense how you had the mode help express the direction.  I see Luke's proposal does the same which I like better than option 3

2023-10-22 01:46 UTC, fluffy commented on draft-ietf-moq-transport.md
> +| END_GROUP    | 0x6   | No       | Inf                 |
Oh, crap, yes, mean to have that all be name the same way. SOrry

2023-10-22 01:50 UTC, fluffy commented on draft-ietf-moq-transport.md
> +| START_OBJECT_DELTA | 0x4   | No       | 0 |
In the meeting I was just thinking about real time interactive audio and video - and I don't see where it would need it. But later I started thinking about a text chat client where each "chat room" was a track, and each thread was a group, and each message was in an object. MIMI would be better with MoQ.  Regardless of if this use case is bogus or not, it does make you think there might be future uses cases were flexibility was good as long as it did not make the current implementations way more complicated.

2023-10-22 05:47 UTC, afrind reviewed
Per Luke's proposal:

> It would be encoded as:
>
>SUBSCRIBE {
>  ...
>  start_group_hint: (i)
>  start_object_hint: (i)
>  end_group_hint (i)
>  end_object_hint (i)
>  ...
>}

I think I would also use a separate varint for the mode for each param rather that the LSBs.  Keep in mind that taking 2 bits from a varint means only 0-15 can be encoded in a single byte, and we shouldn't be trying to squeeze bytes out of this control message.

```
Hint {
  Mode (i),
  [Value (i)]
}
Modes = None, Relative, Next, Absolute
Value is not present when Mode is None

SUBSCRIBE {
  ...
  start_group_hint: Hint
  start_object_hint: Hint
  end_group_hint: Hint
  end_object_hint: Hint
  ...
}
```
Start Group and Start Object cannot be None.  End Group and Object must either both be None (Closed Range), or Neither (Open Subscribe).

Also bikeshed on whether this is a Hint or a Parameter (not to be confused with Track Request Parameter).  Hint implies that it's ok if the publisher ignores it.

2023-10-22 05:47 UTC, afrind commented on draft-ietf-moq-transport.md
> +| START_OBJECT_DELTA | 0x4   | No       | 0 |
> Go back 100 groups from the current group, then start at the 100th from the beginning of the group

I think that would be 

```
START_GROUP_MODE=relative
START_GROUP=-100
START_OBJECT_MODE=*absolute*
START_OBJECT=100
```

> But later I started thinking about a text chat client where each "chat room" was a track, and each thread was a group, and each message was in an object.

This implies a track with multiple active groups.  I guess the current draft doesn't prohibit that, but I'm not sure we're thought through the implications completely.  

I guess I can see "give me the N previous objects from Now (current group)", but struggling to see why I would want N previous objects from the largest one you have in some previous group.  That said, the simplicity of the Luke's proposal is alluring, even if it allows you do request some bizarre things.

2023-10-22 10:41 UTC, kixelated commented
> I think I would also use a separate varint for the mode for each param rather that the LSBs. Keep in mind that taking 2 bits from a varint means only 0-15 can be encoded in a single byte, and we shouldn't be trying to squeeze bytes out of this control message.

A 0-16 range would work for the majority of relative/future hints, so it would definitely save that byte. But I'm fine keeping it verbose for now; the important part is the reusable `Hint` encoding.

> Start Group and Start Object cannot be None. End Group and Object must either both be None (Closed Range), or Neither (Open Subscribe).

Start group = none would be useful for checking track existence. But I'm okay ruling it out for now because it would mean a subscription that matches zero objects.

End object is None to specify the fin of a group. ex. end at the last object of group 69.

> Also bikeshed on whether this is a Hint or a Parameter (not to be confused with Track Request Parameter). Hint implies that it's ok if the publisher ignores it.

I think it's a hint, since the publisher can choose to drop objects/groups on a whim. Even if you ask to start at group 3, you might never get it for congestion control reasons.

But the bigger issue is that a subscriber doesn't know the upstream's expiration time. A publisher may only cache the last 3 groups, so a subscriber can't just ask for the the last 8 groups and expect to receive them all. I think the publisher should signal the (absolute) start/end range in SUBSCRIBE_OK, which may be a subset of the requested range.

2023-10-22 16:14 UTC, fluffy commented on draft-ietf-moq-transport.md
> +| START_GROUP_MODE   | 0x1   | No       | Relative   |
I'm also totally fine taking the signed relative and using unhinged and replacing relative with two modes of  future and past.

2023-10-22 16:17 UTC, fluffy commented on draft-ietf-moq-transport.md
> +| START_OBJECT_DELTA | 0x4   | No       | 0 |
Active groups from way back might not happen, but getting the last objects of group N slightly after the first objects of group N+1 seems like it will happen often.  Luke's proposal relies on that working for prioritization

2023-10-22 16:30 UTC, fluffy commented
I like the direction that Alan has take Lukes stuff. 

To bikeshed the Hint. I think "Location" would be a better name than "Hint". I think this is not really a hint but more a filter that relay will not send me objects on this subscription before the Start location or after the end Location. So if you want my bikeshedy 0.000002 cents, I would define 

Location {
  GroupMode (i),
  GroupValue (i),
  ObjectMode (i),
  ObjectValue (i)
}
ObjectModes = None, Absolute, Past, Future 
GroupModes = None, Absolute, Past, Future 

The the subscribe would have a Start and End  Location.

Location become a clean way to specify a specific a specific object in a track and may turn out to be useful in other parts of the spec.

2023-10-22 16:42 UTC, fluffy commented
<rant> 
I'd like to take a moment to reflect that the notation we are using for is both shitty and bad. 

Take
Hint {
  Mode (i),
  [Value (i)]
}
Modes = None, Relative, Next, Absolute

By shitty, I mean super non intuitive. What does (i) mean? Is [X] optional or an array? But no, that would be ... Can I have more than one X?  If I had Mode(2) followed by [Value(i)], would it be bit packed or would the Mode be padded out to a byte? And what type is Mode. Or if Mode is a type what is then encoding of all that crap. Most schema languages are fairly intuitive to read and guess what they might mean. This is not. 

Then there is the bad. Say I want to define a type called Mode then have two fields in a record called ObjectMode and GroupMode both of type Mode. What do I do?

Location {
GroupMode (i),
ObjectMode (i)
}
ObjectModes = None, Absolute, Past, Future
GroupModes = None, Absolute, Past, Future

This can not possibly be the right way to do it. I mean now that Mode is not reusable and repeats itself. 

If only we had a well defined language for expressing this. Oh wait we do https://datatracker.ietf.org/doc/html/rfc5234

2023-10-22 18:13 UTC, ianswett reviewed
Option 3 looks good, but I'm unsure why we might want different modes for the group and object.  I guess it depends upon how you define how the group modes affects the object?

2023-10-22 18:22 UTC, ianswett commented on draft-ietf-moq-transport.md
> +| START_GROUP_MODE   | 0x1   | No       | Relative   |
Do we really need future?  Except for 'next group', I thought we didn't have a clear use case, so that'd just be a matter of defining 0 to be the next group.

I also think it'd be useful to have a 3rd mode for 'Head/Latest Group'.  If that was present, then I don't think we'd need a mode for Group?  It could always be absolute.

2023-10-22 21:48 UTC, kixelated commented
> Option 3 looks good, but I'm unsure why we might want different modes for the group and object. I guess it depends upon how you define how the group modes affects the object?

I went ahead and enumerated the permutations

group | object | useful | notes
-|-|-|-
absolute | absolute | yes | range request 
absolute | relative | audio* | fetch tail of group 
absolute | future | no | 
absolute | none | yes | receive full group 
relative | absolute | yes | fetch head of group
relative | relative | audio* | fetch tail of live group 
relative | future | audio* | fetch next audio sample(s) 
relative | none | yes | receive full group 
future | absolute | yes | fetch head of group
future | relative | no |  
future | future | no |
future | none | yes | fetch future group 
none | * | empty subscribe

The ones labeled with audio* are only when you have partially independent samples.  For example, each audio GROUP is 2s long and each audio OBJECT is 21ms. 

```
SUBSCRIBE audio start_group=relative/0 start_object=relative/5
```

This would get you the last 105ms of audio (target initial buffer) most of the time. However, you could get unlucky and a new group could have started with less than that available, but it doesn't really matter if the target buffer is small because the player will just wait.

Personally, I want to remove this use-case. If objects can be independent, then they should be separate groups IMO. So each audio frame would be a group of size 21ms. You could then combine the group/object mode since object boundaries can either be absolute, or none (continue until FIN).

2023-10-23 03:51 UTC, afrind commented
I pushed a new commit with PROPOSAL 4, which we have been discussing, pulling the "best of" text and examples from the other proposals.  I deleted the PROPOSAL 1 sample code and didn't add code for 4.

There's one DISCUSS, whether we should allow Start/EndObject to be None and have defaults, or require them to be specified.

🤞

2023-10-23 05:14 UTC, kixelated commented on draft-ietf-moq-transport.md
> +NOT be None if EndGroup's Mode is NOT None.
> EndObject's Mode MUST NOT be None if EndGroup's Mode is NOT None.

I don't think this is true. `end_object=none` means you want the entire group. 

For example, this would request the subscription end once all objects in group 69 have been transmitted:
```
end_group=absolute/69
end_object=none
```

In my head and likely in many implementations, `none` means infinity. `end_object=infinity` means there's no end object.

2023-10-23 05:14 UTC, kixelated commented on draft-ietf-moq-transport.md
> +1. Now
This is technically `Now+1` because the object doesn't exist yet. But yeah I understand it's meant to align with the other proposals.

2023-10-23 13:48 UTC, ianswett reviewed
4 looks good, though I think there are a lot of cases RelativeNext and RelativePrevious don't make much sense for StartGroup and EndGroup.

2023-10-23 13:48 UTC, ianswett commented on draft-ietf-moq-transport.md
> +A location value may be an absolute group or object sequence, or it may be a
This is pre-existing nomenclature, but the use of the word sequence is awkward to me.  Is it shorthand for sequence number?

2023-10-23 13:48 UTC, ianswett commented on draft-ietf-moq-transport.md
> +Mode MAY be None if it is an open-ended subscription.
SHOULD be None for an open-ended subscription?

Or just "is None for an open-ended subscription."

2023-10-23 13:48 UTC, ianswett commented on draft-ietf-moq-transport.md
> +NOT be None if EndGroup's Mode is NOT None.
I would agree.

2023-10-23 13:48 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* StartObject: The Location of the requested object.  StartObject's Mode MUST NOT
I think None means you want the whole group, but I guess that's identical to absolute/0 and I'm ok with being explicit.

If I specify a StartGroup of absolute or RelativePrevious/1, then the entire group is available.  What does RelativePrevious or RelativeNext for StartObject in those cases?

2023-10-23 17:02 UTC, fluffy approved these changes
Merge it :-)

2023-10-23 17:43 UTC, ianswett approved these changes

2023-10-23 17:47 UTC, ianswett commented on draft-ietf-moq-transport.md
> +MAY send a SUBSCRIBE_ERROR with code TBD.
```suggestion
MAY send a SUBSCRIBE_ERROR with code TBD. A publisher MUST NOT send objects
from outside the requested start and end.
```

2023-10-23 17:47 UTC, ianswett commented on draft-ietf-moq-transport.md
> +TODO: Security Considerations related to these hints
```suggestion

```

2023-10-23 18:16 UTC, ianswett commented on draft-ietf-moq-transport.md
> +
```suggestion
```

2023-10-23 18:17 UTC, ianswett commented on draft-ietf-moq-transport.md
```suggestion


```

2023-10-23 18:19 UTC, merged