Describe how to use datagrams
moq-wg/moq-transport pull request #316
Opened 2023-10-30 23:23 UTC by ianswett

Fixes #35

2023-10-30 23:49 UTC, afrind reviewed
Individual Review: 

Should we provide more guidance for publishers about the tradeoffs for sending an object on a stream vs a datagram?

2023-10-30 23:49 UTC, afrind commented on draft-ietf-moq-transport.md
> +a single datagram.  For larger objects, a stream needs to be used.
I think we need more specificity of how the maximum size is determined.  QUIC datagrams can have different maximum sizes (including 0 = disabled) at different hops.

2023-10-30 23:49 UTC, afrind commented on draft-ietf-moq-transport.md
> +a single datagram.  For larger objects, a stream needs to be used.
`a stream needs to ` or `a stream MUST` ?

2023-10-30 23:49 UTC, afrind commented on draft-ietf-moq-transport.md
> +Streams are by default reliable and datagrams are by default unreliable,
Should we mention that streams are subject to limits and datagrams are not?

2023-10-31 00:07 UTC, ianswett reviewed
Thanks @afrind PTAL

2023-10-31 00:07 UTC, ianswett commented on draft-ietf-moq-transport.md
> +a single datagram.  For larger objects, a stream needs to be used.
If it doesn't fit, what might the alternatives be?  We can use a MUST if you feel strongly.

2023-10-31 02:29 UTC, kixelated commented
+1 to providing more guidance. Using datagrams instead of streams is the wrong approach unless you really know what you're doing. I'm worried about the ecosystem treating them as interchangeable.

I think we need to be more prescriptive. Streams are the default approach while datagrams are an extension, viable only in very specific circumstances:

1. An OBJECT is below the MTU.
2. Both endpoints have negotiated datagram support in SETUP.
3. Some form of congestion is anticipated, otherwise QUIC datagrams are kind of pointless.
4. A relay that received a stream needs to provide comparable reliability when sending as datagram instead.
5. Datagrams are prioritized like streams, otherwise sending audio as datagrams (and video as streams) might produce the opposite effect.

Personally, I think vanilla QUIC datagrams are always the wrong approach:

- QUIC datagrams with a negotiated FEC/reliability scheme make sense.
- UDP datagrams within a CDN make sense. (lower overhead or multicast?)
- TCP streams within a CDN make sense. (cost savings)
 
But I don't quite understand why you would use a QUIC `DATAGRAM` frame as opposed to a QUIC `STREAM` frame. They're almost identical on the wire except for an incrementing (stream) ID the aforementioned lack of flow control. What's your envisioned use-case @ianswett ?

2023-10-31 02:41 UTC, kixelated commented
Also another gotcha: DATAGRAM frames MAY be coalesced together depending on the QUIC implementation. Any application that uses datagrams with the expectation that datagram 1 has independent reliability from datagram 2 will be incorrect without tight QUIC bindings.

I think this is why any sort of FEC and custom reliability should happen at the QUIC layer. If you want to send OBJECTs over datagrams for custom reliability, then it really needs to be done at the QUIC frame level, and you could just use STREAM_FIN instead of DATAGRAM.

2023-10-31 16:43 UTC, afrind commented
Maybe move this discussion to an issue rather than a PR so we avoid another unicorn PR.

2023-11-04 16:28 UTC, fluffy approved these changes
LGTM. 

I think this will make a significant difference for applications doing interactive audio on networks with significant amount of loss.

2023-11-04 16:36 UTC, suhasHere commented
this PR is right starting point. We will refine the text once we have more experience with implementation.

2023-11-04 16:36 UTC, suhasHere approved these changes

2023-11-14 01:07 UTC, kixelated requested changes
Forgot to leave a -1. I think we need `datagram in == datagram out`.

This PR allows arbitrarily converting between streams and datagrams, but they have different reliability characteristics and it's not clear why you would do this. The text "implementations can provide equivalent levels of reliability" doesn't hold true because of [#15](https://github.com/quicwg/datagram/issues/15); datagram acknowledgements can't quuiiiite be used to provide reliability.

The bigger issue is that an application that sends datagrams to a relay expects to receive datagrams on the other side. This depends on the stream mapping discussion of course, but clearly the current abtraction of "send objects via any mechanism" is not a useful one.

Of course a service is allowed to do whatever it wants inside of their network (including not using QUIC), but we don't need to specify that.

2024-01-22 03:18 UTC, closed without merging