Remove Full Track Name
moq-wg/moq-transport pull request #331
Opened 2023-11-07 13:40 UTC by ianswett

It's only used a few times and now that Namespace and Name are an opaque sequence of bytes, it's even less compelling.

Fixes #328

2023-11-07 14:25 UTC, kixelated approved these changes
love it

2023-11-07 16:32 UTC, suhasHere requested changes

2023-11-07 16:32 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +same Track Name and Track Namespace results in the subscriber receiving
s/  subscribing to the same Track Name and Track Namespace are guaranteed/  

  ==> subscribing to the same tuple of Track Name and its Namespace results in ...

It is important to know the combination of these 2 (as a tuple) is what identifies a track and just track name, since they are no unique even within a moq scope

2023-12-11 00:25 UTC, ianswett commented on draft-ietf-moq-transport.md
> +within a given MOQT scope and is used as cache key.
```suggestion
Because the tuple of Track Namespace and Track Name are unique within an
MOQT scope, they can be used as a cache key.
```

2023-12-11 00:28 UTC, ianswett commented on draft-ietf-moq-transport.md
> +same Track Name and Track Namespace results in the subscriber receiving
Thanks Suhas, I clarified this and shortened the text.

2023-12-11 00:28 UTC, merged