Object Model to Transport Mapping
moq-wg/moq-transport pull request #333
Opened 2023-11-08 14:34 UTC by suhasHere

This PR brings in currently active proposals for supporting explicit indicators of mapping object model to quic transport.

2023-11-08 14:56 UTC, afrind commented
Please keep discussion of the concepts on the issue #244

2023-11-08 16:19 UTC, fluffy commented
If there are any other proposed solutions to this, would be great to have them documented as additional proposal in this PR.

2023-11-08 16:32 UTC, kixelated requested changes

2023-11-08 16:32 UTC, kixelated commented on draft-ietf-moq-transport.md
> +#### Proposal 2 - Object Placement Mode
It's so verbose to put this mode in every OBJECT. There's also a plethora of collisions that make it almost impossible to use multiple modes.

What about a single mode per track in SUBSCRIBE_OK instead?

2023-11-08 16:32 UTC, kixelated commented on draft-ietf-moq-transport.md
> +##### Mode: StreamPerObject
If I set this mode for an OBJECT that would then prohibit:

- any OBJECT in the group from using StreamPerGroup
- any OBJECT in the track from using StreamPerTrack
- any OBJECT in the priority from using StreamPerPriority

2023-11-08 16:32 UTC, kixelated commented on draft-ietf-moq-transport.md
> +The mode `StreamPerGroup` specifies that all the objects for a given group
All OBJECTs in the specific group MUST also use mode StreamPerGroup.

2023-11-08 16:32 UTC, kixelated commented on draft-ietf-moq-transport.md
> +The mode `StreamPerTrack` specifies that all the groups and objects for a
All OBJECTs in the specified track MUST also use mode StreamPerTrack

2023-11-08 16:46 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +##### Mode: StreamPerGroup
Stream per group, every object that belongs to Group 1, send it on the stream that is assigned for Group 1.  So where is the out of order scenario coming from ? 

Gaps has nothing to do with the transport mode mapping. A gap can be created due to object being dropped by a node on the path and if there exists an object for a group, it gets sent on the stream associated with the group

2023-11-08 16:46 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +The mode `StreamPerPriority` specifies that objects marked with a
that's right

2023-11-08 16:48 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +##### Mode: StreamPerObject
If you want send all the objects for a track over single stream , you set the mode as StreamPerTrack,
if you want to send all the objects in a group together, you set StreamPerGroup,
if you want to send objects on independent streams, you mark them as StreamPerObject.

2023-11-08 16:49 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +The mode `StreamPerGroup` specifies that all the objects for a given group
that's the intention with the existing statement

2023-11-08 16:55 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +#### Proposal 1 - Stream Placement Indicator (Victor's Proposal and Text)
Could you please clarify the major problems that you see ? also what do you see the concerns with different hops having different mappings ( not that I am proposing we allow that , but curious to understand more)

2023-11-08 17:25 UTC, kixelated commented on draft-ietf-moq-transport.md
> +#### Proposal 1 - Stream Placement Indicator (Victor's Proposal and Text)
As Cullen said at the mic, it's just a bug if the relay doesn't forward streams as they were intended.

Packet loss will delay the delivery of a stream relative to others. This algorithm is quite stateful and works based on the most recently received object (regardless of stream) so it will race like crazy and produce wildly unexpected results.

2023-11-08 17:25 UTC, kixelated commented on draft-ietf-moq-transport.md
> +##### Mode: StreamPerGroup
> Stream per group, every object that belongs to Group 1, send it on the stream that is assigned for Group 1. So where is the out of order scenario coming from ?

If objects arrive on different streams then they can arrive out of intended order. If we force implicit == explicit then this isn't an issue, but the text should mention that.

> Gaps has nothing to do with the transport mode mapping. A gap can be created due to object being dropped by a node on the path and if there exists an object for a group, it gets sent on the stream associated with the group

That's fair, but then we need another mode with no gaps. An application that uses delta updates cannot tolerate an arbitrary hole in the middle.

2023-11-08 17:25 UTC, kixelated commented on draft-ietf-moq-transport.md
> +The mode `StreamPerGroup` specifies that all the objects for a given group
Yeah sorry I was suggesting that you add it.

2023-11-08 17:25 UTC, kixelated commented on draft-ietf-moq-transport.md
> +##### Mode: StreamPerObject
To clarify, I'm talking about when OBJECTs could have different modes. If you want ALL objects to use the same mode then that shouldn't be encoded per-OBJECT, it could be in SUBSCRIBE_OK instead.

2023-11-08 17:25 UTC, kixelated commented on draft-ietf-moq-transport.md
> +The mode `StreamPerPriority` specifies that objects marked with a
Sorry, is this a stream...

- per priority per track?
- per priority per namespace?
- per priority (per session)?

The last one is my interpretation of the text and it's impossible because some other namespace/track will definitely want to use another mode.

2023-11-08 17:28 UTC, afrind commented
My recommendation is to pause a bit on this PR. We need more normative language, explanatory prose, and examples to help readers understand and evaluate the proposals without breaking github with a long chain of questions and comments. 

The outcome from Monday's meeting was that the chairs were going to designate a small group to put the proposal forward.  I'll circle with Ian and Ted.

2023-11-09 10:14 UTC, fluffy commented
> The outcome from Monday's meeting was that the chairs were going to designate a small group to put the proposal forward. I'll circle with Ian and Ted.

OK - will wait for that

2023-12-01 04:24 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +An `OBJECT_STREAM` message carries a single object on a stream.  There is no
s/on a stream/on a QUIC stream

2023-12-01 04:26 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +`OBJECT_STREAM` message MUST be the first message on a unidirectional stream.
I think we should also say , there MUST be only occurrence of `OBJECT_STREAM` message else its an protocol error.

2023-12-01 15:44 UTC, afrind commented on draft-ietf-moq-transport.md
> +An `OBJECT_STREAM` message carries a single object on a stream.  There is no
I left out QUIC to account for WebTransport or QUIC.  I think this matches elsewhere now?  In an earlier draft I said "transport stream".

2023-12-01 15:44 UTC, afrind commented on draft-ietf-moq-transport.md
> +`OBJECT_STREAM` message MUST be the first message on a unidirectional stream.
Is that not implied by saying that the payload length is determined by the length of the stream?

2023-12-06 16:42 UTC, kixcord commented
This is all just so confused. The number of messages, modes, and permutations are exploding. Some ideas are in the right direction (ex. stream header) but the hodgepodge of modes/messages is not.

I'd like to explicitly add proposal 4: a relay forwards data streams.

- when a relay receives an upstream stream, it creates a downstream stream (for each subscriber)
- when a relay reads an OBJECT from an upstream, it writes it to the corresponding downstream if it matches the SUBSCRIBE criteria.
- when the upstream is closed, the corresponding downstreams are closed with the same error code or FIN.
- when a relay receives an upstream DATAGRAM, it sends it downstream if it matches the SUBSCRIBE criteria.

No wire changes. I would like a stream header eventually but it's more for compression and to prevent foot guns (ex. prioritization).

This unlocks experimentation as the application can perform any stream mapping. The relay doesn't care and remains simple. The important part is the guarantee that the relay (middlebox) won't rearrange or reorder shit.

2023-12-06 16:59 UTC, afrind commented
> I'd like to explicitly add proposal 4: a relay forwards data streams.
> ...
> No wire changes. I would like a stream header eventually but it's more for compression and to prevent foot guns (ex. prioritization).

The consensus in Prague was to move forward with a proposal that uses explicit signals for now, get more implementation experience and data, and revisit. Proposal 4 only uses implicit signals from the QUIC layer rather than explicit signals from the MoQ layer.  I think you can achieve similar outcomes with proposal 3 by adding the appropriate STREAM_HEADER at the beginning of each stream?

2023-12-06 17:26 UTC, suhasHere commented
+1 to @afrind's proposal. Let's clean it up and get it ready to merge.

2023-12-11 01:17 UTC, ianswett commented on draft-ietf-moq-transport.md
> +`OBJECT_STREAM` message MUST be the first message on a unidirectional stream.
```suggestion
`OBJECT_STREAM` message MUST be the first and only message on a unidirectional stream.
```

2023-12-11 01:54 UTC, ianswett reviewed
3 LGTM overall, but I had some comments on the details.

2023-12-11 01:54 UTC, ianswett commented on draft-ietf-moq-transport.md
> +OBJECT_STREAM Message {
Don't we need a type value so if we receive a stream, we know what type of stream it is?

2023-12-11 01:54 UTC, ianswett commented on draft-ietf-moq-transport.md
> +the fields and payload, and compare the serialized size with the maximum
```suggestion
To send an Object with `Object Forwarding Preference` = `Datagram`, determine
the length of the fields and payload, and compare the length with the maximum
```

2023-12-11 01:54 UTC, ianswett commented on draft-ietf-moq-transport.md
> +stream, send the serialized data and terminate the stream.  An implementation
```suggestion
datagram size of the session.  If the object size is less than or equal maximum
datagram size, send the serialized data as a datagram.  Otherwise, the object on a
unidirectional stream as you would an OBJECT_STREAM message.  An implementation
```

2023-12-11 01:54 UTC, ianswett commented on draft-ietf-moq-transport.md
> +If a stream ends in the middle of a serialized Object, terminate the session
What if the stream is reset?

2023-12-11 01:54 UTC, ianswett commented on draft-ietf-moq-transport.md
> +All Objects received on a stream opened with STREAM_HEADER_TRACK have an `Object
TRACK_STREAM or just TRACK would be simpler to me.

2023-12-11 01:54 UTC, ianswett commented on draft-ietf-moq-transport.md
> +When a stream begins with `STREAM_HEADER_GROUP`, all objects on the stream
How about GROUP?  Also, it'd be more natural to put this above TRACK in terms of ordering.

2023-12-11 01:54 UTC, ianswett commented on draft-ietf-moq-transport.md
> +`STREAM_HEADER_TRACK` if needed, then serialize the the following object fields.
How do I know if they're needed?

Do we have one Object message at the beginning of the stream after the 'type' is serialized and then omit the duplicate fields on subsequent Object messages?

Or do we have a 'message' that starts the stream that could be only the type, followed by the shared values, and then a sequence of objects?  They're fairly equivalent, but we should pick one.

2023-12-11 01:54 UTC, ianswett commented on draft-ietf-moq-transport.md
> +STREAM_HEADER_PRIORITY Message {
I don't think we need this.  I'd rather have every stream have a single priority.  If we want to do that later we can, but we all agree that mixing priorities on a single stream is problematic at best.

2023-12-11 17:21 UTC, afrind commented on draft-ietf-moq-transport.md
> +`STREAM_HEADER_TRACK` if needed, then serialize the the following object fields.
> How do I know if they're needed?

If you have to open a stream for this, then you need to send a header.

> Or do we have a 'message' that starts the stream that could be only the type, followed by the shared values, and then a sequence of objects?

This one.

2023-12-11 17:21 UTC, afrind commented on draft-ietf-moq-transport.md
> +When a stream begins with `STREAM_HEADER_GROUP`, all objects on the stream
Ok

2023-12-11 17:21 UTC, afrind commented on draft-ietf-moq-transport.md
> +STREAM_HEADER_PRIORITY Message {
> I'd rather have every stream have a single priority. 

If that's the case, I think you want this message and remove the GROUP one that allows a different send order per object.

2023-12-11 17:33 UTC, kixelated commented on draft-ietf-moq-transport.md
> +STREAM_HEADER_PRIORITY Message {
+1 priority should definitely be hoisted to the stream header.

There's an argument that a relay could perform application-level prioritization by reordering objects on a stream, but that suffers from head-of-line blocking and contradicts the ordering/reliability that QUIC streams are supposed to provide.

2023-12-11 18:37 UTC, kixcord reviewed
Sorry for the earlier outburst. Alan's proposal is definitely in the right direction and is starting to align with my vision. I think I just need an outlet to write that vision down because I'm getting overwhelmed by leaving piecewise opinions on Github.

I think we should:
- delete `OBJECT_STREAM`, unless somebody wants it.
- delete `STREAM_HEADER_PRIORITY`, moving priority to the stream header.
- add `OBJECT_DATAGRAM`, but we should discuss datagrams more in general.

2023-12-11 18:37 UTC, kixcord commented on draft-ietf-moq-transport.md
> +explicit length of the payload; it is determined by the end of the stream.  An
I would actually be in favor of removing this message type.

I'm using objects with an unbounded length to get around the lack of stream mapping in the current draft. The idea is that an OBJECT_STREAM can't be moved or combined with other streams, so it's a way to actually enforce stream mapping across relays.

However we don't need it any longer if there's explicit stream mapping and ordering/reliability. I would be fine with each OBJECT having a specified length (like HTTP/3 DATA frames) provided the relay can't rearrange them. It does mean that we have to buffer each frame to determine the length but that's often unavoidable.

2023-12-11 18:37 UTC, kixcord commented on draft-ietf-moq-transport.md
> +stream, send the serialized data and terminate the stream.  An implementation
We do need to send RESET_STREAM for flow control reasons. What error code do we use? Do we need to indicate why the datagram was dropped (ex. flow control)?

Does the receiver also reply with a STOP_SENDING?

2023-12-11 18:37 UTC, kixcord commented on draft-ietf-moq-transport.md
> +OBJECT_DATAGRAM_PREFERRED Message {
I think this is a footgun. It has the same downsides as IP fragmentation.

The application want specific behavior from datagrams, namely that they are independent. If a relay converts a datagram a stream, it will be split across IP packets and may even share packets with other datagram fragments. This makes implementing something like FEC basically impossible.

In my opinion, we should require the datagram extension and that all OBJECT_DATAGRAM messages are smaller than 1.2kB.

2023-12-11 18:37 UTC, kixcord commented on draft-ietf-moq-transport.md
> +OBJECT_DATAGRAM_PREFERRED Message {
Also, is a relay expected to cache datagrams or does it require timely delivery? I feel like the intent of datagrams is for transient data, but currently it only disables retransmissions. That feels like the wrong behavior, especially with datagrams that span multiple MTU because it only serves to amplify loss.

2023-12-11 18:53 UTC, kixcord commented
Oh and we should be some text:

> A relay MUST NOT reorder or drop OBJECTs within a stream.

Otherwise we don't fix the core issue, which is that relays can arbitrarily change how OBJECTs are delivered. Stream mapping is useless if it's not enforced.

2023-12-13 05:08 UTC, vasilvv commented
3 is a nice refactor of approach in 1. I like it, expect for two things:
- I don't think we need to support track-per-stream, and I don't remember if we ever actually got consensus for supporting it (we might need to discuss this separately).
- Priority/send order should be a stream-global, since that's the level at which those are determined in QUIC.

The text is not entirely clear to me: is it still legal to have two open streams for the same group with STREAM_HEADER_GROUP (with understanding that they will get merged at the relay)?

I think we could make approach 4 that does to 2 the same things that 3 does to 1. Canonical objects would have two fields:
- 'Object Placement Preference' that says that object is either (1) to be placed on a new stream, or (2) to be placed on the same stream as object N.
- 'Object Placement Close Bit' indicates whether there will be objects after this one on the stream or not (i.e. whether there is a FIN or not)

There's one OBJECT_STREAM frame with Track Alias, Group Sequence, Priority / Send Order as headers. You can trivially figure out how to backfill those fields (you only need to remember the most recent object for each stream); the placement when retrieving from cache is similarly easy (you do need a map for "most recent object -> stream").

I think this fits in with the "implicit-explicit" approach that Luke has mentioned before. It also has a nice property that there are no cases in which what's on the wire can mismatch with what's in the canonical object (unless streams get randomly reset).

2023-12-13 08:15 UTC, wilaw commented
> I don't think we need to support track-per-stream, and I don't remember if we ever actually got consensus for supporting it (we might need to discuss this separately).

Track-per-stream would be the preferred delivery mode for VOD files. I'd very much like to ensure that we keep support for that use case open, even if most current implementations are focused on live.

2023-12-13 16:07 UTC, kixelated commented
> The text is not entirely clear to me: is it still legal to have two open streams for the same group with STREAM_HEADER_GROUP (with understanding that they will get merged at the relay)?

I think it should be illegal as it breaks `implicit=explicit`. The broadcaster uses stream mapping A but wants downstream relays to use stream mapping B, assuming there even is a relay involved. I don't think there's a use-case for this special treatment of the first-hop. 

The only use-case that I've heard is a broadcast client that is smart enough to detect group/object boundaries (ie. frames or key frames) to annotate each OBJECT with the correct stream mapping, but doesn't want to open multiple streams? That's a very poor reason, especially if the first hop may be congested, and the broadcast client should just use the indicated stream mapping.

IMO a relay should not split or merge streams. It increases complexity and hurts performance. There's no need for your proposal 4 then.

2023-12-13 16:36 UTC, kixelated commented
> > I don't think we need to support track-per-stream, and I don't remember if we ever actually got consensus for supporting it (we might need to discuss this separately).
> 
> Track-per-stream would be the preferred delivery mode for VOD files. I'd very much like to ensure that we keep support for that use case open, even if most current implementations are focused on live.

Maybe.

The assumption is a track-per-stream would allow you to write a simple VOD-only client. It wouldn't need to reorder or reassemble objects because they're all delivered in order on a single stream. That's optimistic, as it will still need to support potentially unordered/unreliable objects (like a live client) due to seeking and gaps in the recording.

But I think we need to explore VOD and DVR more. I definitely don't want to require the server to modify the stream mapping at rest in order to serve VOD traffic, and it's not clear how that would even work for DVR.

At the very least we should first support VOD with the original stream mapping. Much like how HLS can use the same segments for live, DVR, and VOD.

2023-12-13 17:01 UTC, wilaw commented
> That's optimistic, as it will still need to support potentially unordered/unreliable objects (like a live client) due to seeking and gaps in the recording.

This assumes LIVE-TO-VOD workflow. When I speak of VOD, its for pure VOD, which has no gaps, and was never live. The track-per-stream would would mean the client would never have to deal with out-of-order or lost objects, as the single stream would deliver them reliably and in order. Like you, I really like the appeal of the simple client interface for this. All I need is more space in my cache and I have a new market segment to address.

2023-12-13 17:09 UTC, vasilvv commented
> IMO a relay should not split or merge streams. It increases complexity and hurts performance. There's no need for your proposal 4 then.

I'm confused. Proposal 4 does not allow merging or splitting streams.

> Track-per-stream would be the preferred delivery mode for VOD files. I'd very much like to ensure that we keep support for that use case open, even if most current implementations are focused on live.

That is true, but VOD requires different delivery mechanism from what live does (e.g. live cares about catching up to the live state, but for VOD, you usually just want to show everything in order).

2023-12-13 21:07 UTC, jordicenzano reviewed
Overall I like the proposal the explicitly map objects to quic streams. I left few comments

2023-12-13 21:07 UTC, jordicenzano commented on draft-ietf-moq-transport.md
> +Object MUST be sent according to its `Object Forwarding Preference`, described
If the "Object *MUST* be sent according to its `Object Forwarding Preference`", should we remove the word "Preference". It seems contradictory with MUST

2023-12-13 21:07 UTC, jordicenzano commented on draft-ietf-moq-transport.md
> +* Object Forwarding Preference: An enumeration indicating how a sender sends an
We need a way to tell the publisher how to map QUIC streams and this seems like a good proposal to me. Perhaps we should add something about relay implementation, perhaps: The relay would need remember how those objects were received on the subscriber side and replicate that in the publisher side

2023-12-13 21:07 UTC, jordicenzano commented on draft-ietf-moq-transport.md
> +STREAM_HEADER_TRACK Message {
I assume we can send 1 track (ex: video track) in mutiple Streams with STREAM_HEADER_TRACK, can I or that would be a protocol violation?

2023-12-14 04:35 UTC, afrind reviewed
Individual Review

2023-12-14 04:35 UTC, afrind commented on draft-ietf-moq-transport.md
> +* Object Forwarding Preference: An enumeration indicating how a sender sends an
I tried to capture this in the sections below describing how to determine the preference when receiving an object and how to send an object with a given preference.  I'm also going to add a normative bit to the relay section.

2023-12-14 04:35 UTC, afrind commented on draft-ietf-moq-transport.md
> +Object MUST be sent according to its `Object Forwarding Preference`, described
Do we like "Object forwarding mode" better than preference?  I'm neutral.

2023-12-14 04:35 UTC, afrind commented on draft-ietf-moq-transport.md
> +OBJECT_STREAM Message {
Jordi is right -- it's the same.

2023-12-14 04:35 UTC, afrind commented on draft-ietf-moq-transport.md
> +the fields and payload, and compare the serialized size with the maximum
I'm going to remove datagram for now.

2023-12-14 04:35 UTC, afrind commented on draft-ietf-moq-transport.md
> +stream, send the serialized data and terminate the stream.  An implementation
same as above.

2023-12-14 04:35 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Object Send Order (i),
This field is to convey the priority signal to the next hop, which might be using an API that allows setting priority on datagrams.

2023-12-14 04:35 UTC, afrind commented on draft-ietf-moq-transport.md
> +If a stream ends in the middle of a serialized Object, terminate the session
You can terminate it cleanly on an object boundary, or reset it, but you can't fin in the middle of an object.

2023-12-14 04:35 UTC, afrind commented on draft-ietf-moq-transport.md
> +STREAM_HEADER_TRACK Message {
I'm going to add that a sender SHOULD only have one stream open with the exact same STREAM_HEADER.  It's not all that enforceable at the receiver though because of reordering.

2024-01-10 13:23 UTC, wilaw commented on draft-ietf-moq-transport.md
> +##### Mode: StreamPerObject
Binding the transport mode to the subscription seems like a reasonable constraint. Once a publisher is producing a track, I can't find an obvious use-case as to why they would need to alter the object-to-transport mapping. If there was one in the future, the publisher could work around it by terminating the track and advertising a new one with the new mapping. Binding the mapping to the subscription means, as kixelated points out, that the mapping info can be sent just once in SUSBCRIBE_OK. For compactness, anything that doesn't change over the life of a subscription (such as track alias, subscribe ID and now mapping) should be communicated via SUBSCRIBE_OK.

2024-01-10 17:39 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  Subscribe ID (i),
I think this should be track alias not subscribe ID

2024-01-12 04:06 UTC, suhasHere reviewed
Thanks @afrind  .. this is coming pretty close. I left few comments.

2024-01-12 04:06 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +Send Order`, or open a new one and send the `STREAM_HEADER_GROUP` if needed,
I really don't see a need to have a match on the SendOrder here. StreamPerGroup sends all the objects with the same groupId. if the application wants to send each priority in its own group, then it arranges that way.

2024-01-12 04:06 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Object Sequence = 0
sequence to Id

2024-01-12 04:06 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +~~~
May be we should have this example to extended as 
{Stream_Header_Track}{g1, o0}{g1, o1} ... {g2,o0}, {g2,o1}, ....

2024-01-12 04:06 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Group Sequence = 0
sequence to Id

2024-01-12 04:06 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
the unordered object example is confusing here and I prefer not to include and create a new example for OBJECT_STREAM

2024-01-12 04:28 UTC, afrind reviewed
Thanks for the quick review. I have addressed some, left some responses/suggestions for the others.

For examples, let's wait til all the feedback is in and we can make another pass.

2024-01-12 04:28 UTC, afrind commented on draft-ietf-moq-transport.md
> +forwarding to subscribers.
I think we said in a previous author's call that we would relax this when we formally add concepts like TTL or drop preference, which give relay instructions about which objects are droppable.  I can update to "A relay MUST not reorder or drop objects *without application specific information*" - or something like that?

2024-01-12 04:28 UTC, afrind commented on draft-ietf-moq-transport.md
> +have the same `Object Send Order`.
The intent is to tell the receiver how to populate the canonical 'Object Send Order'.  I can say "have the `Object Send Order` specified in the stream header" ?

2024-01-12 04:28 UTC, afrind commented on draft-ietf-moq-transport.md
> +Send Order`, or open a new one and send the `STREAM_HEADER_GROUP` if needed,
The intent was to allow more flexibility than strictly stream-per-group.  With this design, the publisher can split a group into multiple streams with different priorities.  The original proposal 3 had both kinds of streams and the feedback was to combine them.

2024-01-12 23:07 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +forwarding to subscribers.
works for me. Thanks

2024-01-16 22:15 UTC, kixelated requested changes
It's almost there. This is exponentially easier for a relay and receiver than prior proposals.

2024-01-16 22:15 UTC, kixelated commented on draft-ietf-moq-transport.md
> +stream that is associated with the subscription, or open a new one and send the
I'm confused by this sentence. This seems like an implementation detail depending on the API?

Personally, I wouldn't lazy initialize the stream because then the MoQ library won't know when to close it. I think you can safely remove this sentence and just say that multiple objects follow.

2024-01-16 22:15 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  Object ID (i),
Can we add the constraint that both of these must be increasing over the life of the stream? Otherwise dropping and subsequent gap detection becomes very difficult.

2024-01-16 22:15 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  Object ID (i),
Same thing, can we make this increasing only?

2024-01-17 00:07 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +stream that is associated with the subscription, or open a new one and send the
i think this needs to caoture the intent as " all the objects for a given track is sent on the same stream" .

2024-01-17 00:10 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Object ID (i),
groupId and object Id are monotonically increasing integers.

2024-01-17 00:25 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +TODO: figure out how a relay closes these streams
agree we need to get to this , but I feel this can be done in a separate PR>

2024-01-17 01:15 UTC, afrind reviewed
Individual comments

2024-01-17 01:15 UTC, afrind commented on draft-ietf-moq-transport.md
> +TODO: figure out how a relay closes these streams
> I don't think a relay can implement the draft until this is specified.

I agree.

> agree we need to get to this , but I feel this can be done in a separate PR

I'm inclined to take the consensus we have, merge it and build on it, rather than keeping this PR open.

I don't think we want to take it from the QUIC layer and we do need an MoQ layer signal.  Is the stream carrying the track data even sufficient or could it be reset?  The stream termination messages may need to go on the control stream?

2024-01-17 01:15 UTC, afrind commented on draft-ietf-moq-transport.md
> +stream that is associated with the subscription, or open a new one and send the
The intent was to explain how relays send outgoing objects, but make it generic for publishers too.  Similar language was used for other multi-object stream formats.

I don't think it conflicts with your plan to not-lazy-initialize, that would fit in "find the open stream...", but I'm open to different language too.

2024-01-17 01:15 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Object ID = 1
Yes, I think I meant for this to be Object ID=2.

2024-01-17 01:15 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Object ID (i),
I'm ok adding an explicit restriction here.  Does anyone object?

2024-01-17 01:15 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Object ID (i),
I'm ok adding an explicit restriction here.  Does anyone object?

2024-01-17 01:15 UTC, afrind commented on draft-ietf-moq-transport.md
> +explicit length of the payload; it is determined by the end of the stream.  An
> A relay could still convert single object streams into multi object streams that by buffering until EOF.

I don't think so.  The rules for sending objects say

```
To send an Object with `Object Forwarding Preference` = `Object`, open a stream,
serialize object fields below, and terminate the stream.
```

2024-01-17 17:08 UTC, ianswett approved these changes

2024-01-17 17:15 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  Object ID (i),
> groupId and object Id are monotonically increasing integers.

Are they monotonically increasing? I thought the use-case was two streams with objects interlaced, in which case they wouldn't be.

2024-01-17 17:59 UTC, kixelated approved these changes

2024-01-18 15:45 UTC, ianswett approved these changes

2024-01-18 15:45 UTC, ianswett commented on draft-ietf-moq-transport.md
> +The Track Namespace and Track Name identified by the Track Alias is different
```suggestion
If the Track Namespace and Track Name identified by the Track Alias is different
```

2024-01-18 15:45 UTC, ianswett commented on draft-ietf-moq-transport.md
> +The Track Namespace and Track Name identified by the Track Alias is different
Also, this applies to all types of mappings, so maybe move it up to the end of the previous section?

2024-01-22 03:03 UTC, merged