Add support for end message.
moq-wg/moq-transport pull request #334
Opened 2023-11-08 15:09 UTC by suhasHere

This PR attempts to support the requirements needed for #318 and #244

2023-11-14 00:41 UTC, afrind reviewed
Individual Review:

If SUBSCRIBE_FIN works for END(Track), then the main missing use-case is group.  Maybe we can morph this to END_GROUP { Track Alias, Group, Object } for now?

2023-11-14 00:41 UTC, afrind commented on draft-ietf-moq-transport.md
> +sent on the control stream.
I'm somewhat concerned about including END on OBJECT streams.  In the case where the peer sends a STOP_SENDING, the original sender may not know if the receiver has received the END message.  Instead, I'm inclined to say that END must appear on a non-resettable stream.  This could be a track-specific control stream, or the sender can just open a stream, send END and close it.

2023-11-14 00:41 UTC, afrind commented on draft-ietf-moq-transport.md
> +* Track (0x0) : The `END` message corresponds to completion of a track. The
How is this different from SUBSCRIBE_FIN?

2023-11-14 00:41 UTC, afrind commented on draft-ietf-moq-transport.md
> +* Object (0x2) : The `END` message corresponds to completion of an object,
I'm unsure when I would send this.  If I'm using OBJECT_WITH_LENGTH, the end is well known - it's over when you receive the terminal byte of payload.  If I'm using OBJECT_WITHOUT_LENGTH, there isn't a place to put END in the same stream, and presumably the end of the stream marks the end.

Do you have another use-case in mind?

2023-11-14 00:58 UTC, kixelated requested changes
As the protocol currently stands, we need a way to mark the end of a group, but we also need a way to mark when individual objects have been dropped. Otherwise, a subscriber waiting for an END object as signaled by this message may never unblock. I don't think this end group is useful otherwise, and perhaps misleading.

2023-11-14 00:58 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* Group (0x1) : The `END` message corresponds to completion of a group
This use-case is useful without stream mapping. I still want a stream per group, where the stream FIN signals the end of a group, instead of this (noisy) message on the control stream.

2023-11-14 00:58 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* Object (0x2) : The `END` message corresponds to completion of an object,
+1 There's no use-case here.

2023-11-14 00:58 UTC, kixelated commented on draft-ietf-moq-transport.md
> +END Message {
You also need to to include the last group/object like `SUBSCRIBE_RST/FIN`. Sending a boolean `END` message without them is extremely racey.

2023-11-14 00:58 UTC, kixelated commented on draft-ietf-moq-transport.md
> +Sending `END` message is optional for cases where the completion
We should remove the object mode because like this paragraph outlines, it provides duplicate functionality.

However the `END` message MUST/SHOULD be sent for the end of each track/group, otherwise a receiver can't rely on it.

2024-02-29 17:10 UTC, fluffy requested changes

2024-02-29 17:10 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* Track (0x0) : The `END` message corresponds to completion of a track. The
This is in the data plane and does not change the subscription. That allows it to indicate the end of each group as well as the end of track. But even when using it for end of track, imagine a care where things are out of order. Lets say group 100 is the last one, group 99 may still arriver after the END object. The END object just tells you what the publisher is saying is the last object in the group or track. We could do this with flags in the object but that has other problems.

2024-02-29 17:10 UTC, fluffy commented on draft-ietf-moq-transport.md
> +A publisher can optionally send `END` message to indicate the completion of
This needs more information to explain how this is differnt than what is happening with SUBSCRIBES and that relays need to cache this information and deliver it. I feel like it might be better done as as a special type of object.

2024-02-29 17:10 UTC, fluffy commented on draft-ietf-moq-transport.md
> +Sending `END` message is optional for cases where the completion
I agree with Luke on this should not be optional

2024-02-29 17:24 UTC, wilaw commented on draft-ietf-moq-transport.md
> +Sending `END` message is optional for cases where the completion
I think we should signal the end of publication of a track, but it should not apply at the GROUP level otherwise we have a very chatty. 

Furthermore, END can be scoped at multiple different layers. It think this should apply specifically to tracks and that it should look like this:

TRACK_END
{
   Track Namespace (b),
   Track Name (b),
   LastGroup (Location),
   LastObject (Location),
}

2024-03-04 17:04 UTC, fluffy commented
As a wY of making progress on this, lets first focus on how we know about the end of group, then jump into the end of track.

2024-04-28 15:53 UTC, closed without merging