Add largest Group ID and Object ID to SUBSCRIBE_OK
moq-wg/moq-transport pull request #343
Opened 2024-01-22 14:19 UTC by wilaw

Fixes https://github.com/moq-wg/moq-transport/issues/337

2024-01-22 15:09 UTC, suhasHere requested changes

2024-01-22 15:22 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
same comments as above applies here i think

2024-01-22 16:41 UTC, ianswett reviewed
I was thinking we would add the start group and Object ID for the requested subscription.  Even for an absolute subscription, I can imagine cases the requested start values can't be served, so newer ones have to be served instead?

It'd also be nice to make these optional, but I think that's a detail that depends upon what fields we end up wanting here.

2024-02-04 22:01 UTC, fluffy requested changes
This seems like it will have many race conditions. It seems like it would be better to transfer this in the STREAM_HEADER_TRACK and equivalent.  Thoughts on that ?

I also worry about how long a subscribe would wait to find out this information - that seems like it could be problematic for the client knowing when to give up on a subscribe. 

Hopefully we can discuss in Denver

2024-02-14 18:52 UTC, wilaw commented on draft-ietf-moq-transport.md
> +
This has now been resolved with the addition of the ContentExists flag.

2024-02-14 18:53 UTC, wilaw commented on draft-ietf-moq-transport.md
> +
Same resolution.

2024-02-14 19:02 UTC, afrind commented
nit: can you wrap the lines at 80 chars?

2024-02-14 19:51 UTC, suhasHere requested changes
Small nits. Thanks for the change.s

2024-02-14 19:51 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +* Largest Group ID: the largest Group ID available for this track. This Group ID corresponds to the Group that would be returned with a {{subscribe-locations}} RelativePrevious value of 0. It represe
I don't see a need to include text on locations here.

2024-02-14 19:51 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +* Largest Group ID: the largest Group ID available for this track. This Group ID corresponds to the Group that would be returned with a {{subscribe-locations}} RelativePrevious value of 0. It represe
Also , this seems uneccesary "Note that the Group may not be complete when this value is returned.".

2024-02-14 19:51 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
same comments as above, Let's just indicate largest object Id os the largest known object under the group indicated by "LargestGroupId".

2024-02-14 20:48 UTC, wilaw commented on draft-ietf-moq-transport.md
> +* Largest Group ID: the largest Group ID available for this track. This Group ID corresponds to the Group that would be returned with a {{subscribe-locations}} RelativePrevious value of 0. It represe
> I don't see a need to include text on locations here.

I think we need to cleanly define what "largest" means in the context of groups and how this maps precisely to the Location description. Simply saying its the "largest group" doesn't tie in to how an subscriber would actually request that object. 

> Also , this seems unnecessary "Note that the Group may not be complete when this value is returned.".

This was added because there was some ambiguity as to whether this was the largest fully complete group available for the track, or just the largest group for which at least one object has started publishing. It's the latter, but thats not obvious if the language above is omitted.

2024-02-14 22:12 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +* Largest Group ID: the largest Group ID available for this track. This Group ID corresponds to the Group that would be returned with a {{subscribe-locations}} RelativePrevious value of 0. It represe
Largest is the largest know groupId and objectId for a given track seen so far or available. I think we are making it less clear by adding location information. Locations are filters and the answer one gets doesn't have to match it since the state of publisher may have very well moved out. 

I sitll feel if the group being full or not doesn't need to be specified here.

2024-02-15 00:34 UTC, afrind commented on draft-ietf-moq-transport.md
> +
Individual Comment: 

I recommend we keep the text here very simple, and reference the Locations section for a definition of what Largest Group and Largest Object mean, since they are used throughout that section.  Right now, isn't a good definition of Largest Group and Largest Object there, but we can add that in a follow-up PR?

2024-02-18 21:05 UTC, ianswett approved these changes

2024-02-18 21:10 UTC, ianswett commented on draft-ietf-moq-transport.md
> +
I shortened the descriptions some, though we could probably make them even shorter.

2024-02-18 21:12 UTC, ianswett commented
In the call last Wednesday, we agreed this design was the correct approach, so merging even though there are some reviews outstanding requesting changes.

2024-02-18 21:12 UTC, merged