One forwarding preference per subscription
moq-wg/moq-transport pull request #375
Opened 2024-02-09 18:43 UTC by martinduke

Fixes #351.

There could stand to be (1) a section on a subscriptions, and (2) rearranging the sections here to pull objects out of the message section. But I think it would be easier to review if cut-and-paste happens in a separate PR.

There are other issues (e.g. explicit payload length all the time) that are not addressed in this PR.

2024-02-09 18:51 UTC, martinduke commented
It's subscription-level rather than track-level because

(1) the only convenient place to communicate forwarding preference is SUBSCRIBE_OK
(2) as it currently stands, objects are sent once per subscription
(3) I am not a Use Case Haver, but I can see that an archival subscribe might want a single track stream while the live edge probably would not, even for the same track.

2024-02-09 23:41 UTC, suhasHere requested changes
This changes the direction of the original intent with the forwarding preference. Originally it was one preferred producer's intent that applies uniformly to all the subscribers. With the current proposal, it seems like it can vary across subscribers IIUC.

Am i understanding the proposal properly ?

2024-02-10 01:26 UTC, martinduke commented
@suhasHere yes, see the comment immediately before your question. If this is really objectionable, we can change it, but it would require an error condition check if two SUBSCRIBE_OKs had different preferences for the same track_alias.

I have no strong opinion on this, but this is way easier. When I write a server, it will probably always use one preference for a track.

If we change objects to be sent once per track, instead of once per subscription, this would have to change.

2024-02-10 22:23 UTC, fluffy requested changes
Lets talk about this but I don't think this reflect what was said in the meeting and I don't think it will work. We said we could move to one forwarding preference per track, not per subscription. 

As this is not, I a very much against merging it.

2024-02-11 02:49 UTC, ianswett commented
I expect this will be a straightforward PR once we figure out the FETCH/SUBSCRIBE work, but in the meantime it's caught up in #350

2024-02-12 16:50 UTC, martinduke commented
No one seemed to like subscription scope, so I changed it.

I think we can merge this before the FETCH/SUBSCRIBE stuff. The bulk of the changes are in the Object message.

2024-02-12 17:15 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Forwarding Preference (8),
i personally feel that all the track level information can be learnt from catalog.  I wonder if we should have anything in Subscribe OK ?

2024-02-12 17:25 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  Forwarding Preference (8),
But relays need to know the forwarding preference and they can't read the catalog, so SUBSCRIBE_OK is a good location to carry subscription-scoped metadata.

2024-02-12 17:33 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Forwarding Preference (8),
Out encoding has all the necessary information to know the object forwarding preference. my implementation uses that info and sets up the needed forwarding preference today.

2024-02-12 17:46 UTC, martinduke commented on draft-ietf-moq-transport.md
> +  Forwarding Preference (8),
The PR eliminates that encoding to save a byte on objects, since it's extraneous.

2024-02-12 17:46 UTC, kixelated requested changes
I think we just need some text to say it's a protocol violation (connection closed) if you do dumb like have two streams cover the same object/group/track twice. This PR prevents some instances of that, but at the cost of making decoding more annoying.

Frankly, I don't even want the relay to know about forwarding preference. It should just receive a stream, apply the subscription as a filter, send the stream. The stream headers are only meant to remove redundant encoding.

2024-02-12 22:00 UTC, afrind commented
> Frankly, I don't even want the relay to know about forwarding preference. It should just receive a stream, apply the subscription as a filter, send the stream. The stream headers are only meant to remove redundant encoding.

Chair Comment:

The WG agreed to have an explicit encoding of the forwarding preference for now and revisit that based on experimental data at a later date.  The current signal serves dual purpose with object property compression.

Individual Comment:

The publisher should be able to communicate immutable Track properties in Subscribe OK without those being properties of the Subscribe.  Using HTTP as an example, response headers contain immutable properties of the requested resource (Content-Length) and variable properties (Date, Server).

2024-02-13 03:28 UTC, suhasHere commented
> The publisher should be able to communicate immutable Track properties in Subscribe OK without those being properties of the Subscribe. Using HTTP as an example, response headers contain immutable properties of the requested resource (Content-Length) and variable properties (Date, Server).

In HTTP the request is between the client and the Origin server, but in MOQT the subscribe req/resp is a hop-by-hop property.  Also we have catalog that lists track level immutable properties anyways.  

There are 3  kinds of information that would be good to learn and we need to separate architectural constraints for the same


- Static track level properties like track info, preferences -> this can go in catalog and hence served over control plane/slow path.

- Dynamic properties reflecting the current state of objects like live/expiry edge, last object/group info --> this would be best served on data plane/fast path along with data. 

- Data that relay doesn't usually have access to but it needs to make decision on per object basis. this includes  object properties like priority, its preferences, alias (some of which can be inherited from track level settings and set by the original producer endpoint when publishing) --> this would be best served on the fast path as well.

2024-02-14 17:30 UTC, ianswett commented
After discussion at today's meeting, the conclusion was that we'd like to do the minimal change of saying you can't have different forwarding preferences for a given track and if a subscriber receives different ones, close the session with an error.

2024-02-18 20:28 UTC, closed without merging