Objects are identical
moq-wg/moq-transport pull request #376
Opened 2024-02-11 03:09 UTC by ianswett

Regardless of where they're retrieved from.

Fixes #361

2024-02-11 15:21 UTC, suhasHere approved these changes

2024-02-11 15:32 UTC, fluffy requested changes

2024-02-11 15:32 UTC, fluffy commented on draft-ietf-moq-transport.md
> +its namespace, name, group ID and object ID, and must be an identical
perhaps "track namespace" and "track name".

2024-02-11 15:32 UTC, fluffy commented on draft-ietf-moq-transport.md
> +sequence of bytes regardless of how or where it is retrieved.
So if it has expired, or gets an error, you don't get the bytes. I wonder if it is better to say something more like they contents of an object can never be changed and if it is retried, will always have the same bit wise exact data in it.

2024-02-11 15:34 UTC, fluffy commented
I put a two very small nit comments but don't care either way. They do not change the substance of the PR and +1 on the overall thing this is saying.

2024-02-18 21:00 UTC, ianswett commented on draft-ietf-moq-transport.md
> +sequence of bytes regardless of how or where it is retrieved.
I tried to capture the idea that it doesn't change over time, but I couldn't figure out a good rephrase for the rest, so I left it as is for now.  Feel free to write an editorial PR to improve the text after it is merged if you'd like.

2024-02-18 21:02 UTC, merged