Replace UNSUBSCRIBE with SUBSCRIBE_UPDATE
moq-wg/moq-transport pull request #385
Opened 2024-02-19 19:05 UTC by ianswett

Fixes #363 and #269

2024-02-19 19:12 UTC, ianswett commented on draft-ietf-moq-transport.md
> +A subscriber issues a `SUBSCRIBE_UPDATE` message to a publisher requesting a
```suggestion
A subscriber issues a `SUBSCRIBE_UPDATE` message to a publisher to request a
```

2024-02-19 19:14 UTC, ianswett commented on draft-ietf-moq-transport.md
> +If an update cannot be completed by the relay, it replies with a 'SUBSCRIBE_ERROR'
```suggestion
If an update cannot be completed by the relay, it replies with a SUBSCRIBE_ERROR
```

2024-02-19 19:37 UTC, ianswett commented on draft-ietf-moq-transport.md
> +already been received.
```suggestion
A SUBSCRIBE_UPDATE MUST NOT fail if the specified EndGroup and EndObject are
earlier than the current values.
```

2024-02-19 19:38 UTC, ianswett commented on draft-ietf-moq-transport.md
> +earlier than the current values.
```suggestion
A SUBSCRIBE_UPDATE MUST NOT fail if the specified EndGroup and EndObject are
earlier than the current values for the subscription.
```

2024-02-20 04:26 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  EndObject (Location),
This needs to be optional and only set if the subscription needs to be ended.

2024-02-20 04:28 UTC, suhasHere requested changes

2024-02-20 04:28 UTC, suhasHere commented on draft-ietf-moq-transport.md
>  |-------|-----------------------------------------------------|
I feel Unsubscribe makes more sense if one wants to end the subscription.
We don;t need a new message to update an existing subscription. A subscriber can update an existing subscription by sending `SUBSCRIBE` message with SubscribeId that matches an existing subscription.

2024-02-20 08:22 UTC, kixelated requested changes

2024-02-20 08:22 UTC, kixelated commented on draft-ietf-moq-transport.md
> +If an update cannot be completed by the relay, it replies with a SUBSCRIBE_ERROR
But what about SUBSCRIBE_OK? We should send it too, especially if the end groups use relative offsets.

2024-02-20 08:22 UTC, kixelated commented on draft-ietf-moq-transport.md
> +with error code 'Update Failed' and the subscription is unchanged.
I don't like the subscription being unchanged. It causes a partial failure which is just really difficult to support.

2024-02-20 08:22 UTC, kixelated commented on draft-ietf-moq-transport.md
> +If an update cannot be completed by the relay, it replies with a SUBSCRIBE_ERROR
Also what if there are multiple SUBSCRIBE_UPDATES? Do the SUBSCRIBE_ERRORs have to be returned in order? With no OK, it's impossible to differentiate if the 1st or 2nd UPDATE failed.

2024-02-20 08:22 UTC, kixelated commented on draft-ietf-moq-transport.md
> +SUBSCRIBE_UPDATE Message {
Can we also update the start group/object? It would be super useful for relays to deal with:

viewer1: SUBSCRIBE start=-2
(pause)
viewer2: SUBSCRIBE start=-3

Currently, the relay would issue to origin:
SUBSCRIBE start=-2
(wait for SUBSCRIBE_OK -2=65)
SUBSCRIBE start=64 end=65

Which is complicated and incurs delay. But if we allow updating start ranges:
SUBSCRIBE start=-2
SUBSCRIBE_UPDATE start=-3

2024-02-26 18:13 UTC, afrind reviewed
Individual Review:

We should have a way to update the endpoint of a subscription (like subscribe update), and also a way to unsubscribe immediately when you don't know or care about the end.  I suppose we can do that by setting the new end-point to absolute 0/0.

2024-02-26 18:13 UTC, afrind commented on draft-ietf-moq-transport.md
> +SUBSCRIBE_UPDATE Message {
Updating the start point can mess with object mapping to streams, especially moving backwards.  In your example, if the track is stream-per-track, the publisher may open a stream and being publishing group=65.  In the current design, where subscription ID appears in objects, the second subscribe for group=64 will come on its own new stream.  If we allow updating the subscription start point backwards to 64, what should the publisher do? Should it close the open stream and open a new one, beginning at group=64, and resend objects from group=65?

2024-02-26 18:13 UTC, afrind commented on draft-ietf-moq-transport.md
> +  EndObject (Location),
In the context of this PR and the current draft, where the only thing you can change is the end, this message is OK.  However, if we add more parameters to subscribe (eg #381), then we need a way to update some of the parameters and not others.

We should also clarify what happens if you issue the SUBSCRIBE twice for the same ID - I expect in this PR as is, we would make that an error?

2024-02-28 17:03 UTC, ianswett commented on draft-ietf-moq-transport.md
> +SUBSCRIBE_UPDATE Message {
I do think updating the start is potentially interesting and useful.

Updates of the start should not be able to move the start point of the subscription earlier.  As you said, it's just too complex.  For similar reasons, I think updating the end to be farther in the future is error prone as well, though there may be use cases for that.

2024-02-29 16:55 UTC, fluffy requested changes
My main comment is I don't think we shoudl try and use UPDATE as the way we do UNSUSCRIBE

2024-02-29 16:55 UTC, fluffy commented on draft-ietf-moq-transport.md
> +modification to the end of an existing subscription.  One common type of
I think the "end of existing" should say the "end of the subscription range".

2024-02-29 16:55 UTC, fluffy commented on draft-ietf-moq-transport.md
> +modification is unsubscription.
I don't think this is right. The update should just be to change the metadata about the subscribe, not change the state of the subscribe. We should use some other message to cause the SUSBCRIBE to end and remove all the state about the SUBSCRIBE.

2024-02-29 16:55 UTC, fluffy commented on draft-ietf-moq-transport.md
>  |-------|-----------------------------------------------------|
I think we need both the UNSUBSCRIBE and UPDATE ( or whatever names we decide to call them ).

2024-02-29 16:55 UTC, fluffy commented on draft-ietf-moq-transport.md
> +If an update cannot be completed by the relay, it replies with a SUBSCRIBE_ERROR
I think this should be an UPDATE_OK/ERROR. Don't care if it is two message or not. But should be clear that if some part of the UPDATE can not be applied, then no part of the update is applied, subscribe stays with same meta data as before, and error returned. So an update is all or nothing.

2024-02-29 16:55 UTC, fluffy commented on draft-ietf-moq-transport.md
> +are received.
Uh, I think this needs to be UNSUBSCRIBE or whatever the  SUBSCRIBE CLOSE/STOP/FIN/RST/END is called

2024-02-29 16:55 UTC, fluffy commented on draft-ietf-moq-transport.md
> +SUBSCRIBE_UPDATE Message {
+1 on start can only be moved forward, end can only be moved backwards

2024-02-29 16:55 UTC, fluffy commented on draft-ietf-moq-transport.md
> +SUBSCRIBE_UPDATE Message {
As a side note where I don't really care ... I'm not sure the use case to move the start forward

2024-02-29 16:55 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  EndGroup (Location),
This is not a location this shoudl be an optional var int

2024-02-29 16:55 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  EndObject (Location),
This should be var int not Location

2024-02-29 16:55 UTC, fluffy commented on draft-ietf-moq-transport.md
> +Mode is None for an open-ended subscription.
I would prefer to make the end group / object optional in the update instead of having a None value. I think it makes a better patter for how to add future things to the update.

2024-04-27 16:04 UTC, afrind commented
Is this overtaken by #435 ?

2024-04-30 01:36 UTC, closed without merging