Remove 'Expires' from SUBSCRIBE_OK
moq-wg/moq-transport pull request #391
Opened 2024-02-19 20:37 UTC by ianswett

Fixes #390

2024-02-20 02:23 UTC, suhasHere requested changes

2024-02-20 02:23 UTC, suhasHere commented on draft-ietf-moq-transport.md
>    ContentExists (1),
I do feel expires is needed. This is a way for CDN/relay provider to indicate the subscriber to renew their interest in subscription.  I would think Hops within a CDN network might configure a different (larger) value for this compared to end point client subscribing to edge relay.

I might be convinced otherwise, but love to discuss this a bit.

2024-02-20 06:58 UTC, kixelated approved these changes
This change might be controversial but I'm all for it.

2024-02-20 16:51 UTC, afrind commented on draft-ietf-moq-transport.md
> -longer valid. A value of 0 indicates that the subscription stays active
Individual Comment:

That might be a nice middle ground -- `expires` is advisory to the client that it's going to get a SUBSCRIBE_RESET at that time.  It can avoid that (make before break) by resubscribing before that point.

2024-02-20 17:53 UTC, suhasHere commented on draft-ietf-moq-transport.md
> -longer valid. A value of 0 indicates that the subscription stays active
@afrind That's not just the middle ground. but  expected behavior for relay provider not to waste its resources if the susbcriber doesn't renew its interest in a given track.  Also good point on make before break scenario.

2024-02-20 18:17 UTC, vasilvv commented
I believe this PR is a step in the right direction, since the current subscription expiry mechanism feels underspecified; I can think of some cases in which that would be useful, but I'd rather have a `SUBSCRIBE_GOAWAY` message that tells the peer they should resubscribe rather than a timer.

2024-02-20 22:47 UTC, ianswett commented on draft-ietf-moq-transport.md
> -longer valid. A value of 0 indicates that the subscription stays active
What does renewing its interest mean?  It continues to ACK packets and supply flow control for streams to allow the data for the subscription to be delivered, so it's not completely passive.

I don't know what action to take based on this field a subscriber.  There's no guarantee the subscription will last as long as the expires indicates.  There's also no guarantee it won't last much longer, especially if we still require a SUBSCRIBE_RESET or FIN, which I think we should to ensure the state machine is simpler.

2024-02-21 17:07 UTC, fluffy reviewed
Lets talk about this but I think we need very long lasting session ( imagine weeks or years that are common with security cameras )  to periodically be reauthenticated and I had imagined this was the place to do it.

2024-03-05 19:41 UTC, ianswett commented
Closing this for now, we can always remove 'Expires' easily later on.

2024-03-05 19:41 UTC, closed without merging