Track Namespace is an exact match
moq-wg/moq-transport pull request #394
Opened 2024-02-19 21:45 UTC by ianswett

Fixes #252

2024-02-19 21:48 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +send subscriptions with a 'Track Namespace' that exactly match to
"Relays send" feels ambiguous to me, as in, I don't understand what is the actual normative requirement that we are trying to communicate here.

2024-02-20 06:19 UTC, kixelated requested changes

2024-02-20 06:19 UTC, kixelated commented on draft-ietf-moq-transport.md
> +send subscriptions with a 'Track Namespace' that exactly match to
Same, I don't understand this.

2024-02-20 22:51 UTC, ianswett commented on draft-ietf-moq-transport.md
> +send subscriptions with a 'Track Namespace' that exactly match to
Agreed, I was having a difficult time determining what text to add and where.  Suggestions or alternate PRs are welcome.

2024-02-21 17:04 UTC, fluffy approved these changes
I'm not sure how to wordsmith this but +1 to what it is saying.

2024-02-21 18:21 UTC, kixelated commented on draft-ietf-moq-transport.md
> +send subscriptions with a 'Track Namespace' that exactly match to
I think the text is trying to be too technical. Here's my suggestion:

A relay manages sessions from multiple publishers and subscribers, connecting them based on the track namespace. This SHOULD use a full string match unless otherwise negotiated by the application. For example, a `SUBSCRIBE namespace=foobar` message will be forwarded to the session that sent `ANNOUNCE namespace=foobar`.

I put a SHOULD instead of a MUST so we leave door open. Relays are going to rewriting the namespace, or using a portion of it based on the application, and it would be impossible to enforce anyway.

2024-02-21 22:33 UTC, ianswett commented on draft-ietf-moq-transport.md
> +send subscriptions with a 'Track Namespace' that exactly match to
Given you specify the unless, I'd prefer MUST unless, but otherwise LG.

2024-02-21 22:37 UTC, ianswett commented
PR updated, PTAL

2024-02-22 03:31 UTC, kixelated approved these changes

2024-02-22 15:29 UTC, suhasHere approved these changes
Thanks for the update

2024-02-23 18:01 UTC, merged