Merge RESET and FIN and unify naming
moq-wg/moq-transport pull request #401
Opened 2024-02-28 16:15 UTC by ianswett

This unifies on _CANCEL and _CLOSED.

Fixes #398 
Fixes #310

2024-02-28 16:23 UTC, kixelated approved these changes
I like it.

I would also like to merge ERROR with CLOSED, but we'll chat about that.

2024-02-28 16:57 UTC, martinduke commented on draft-ietf-moq-transport.md
> +* Error Code: Identifies an integer error code for subscription end.
So what are these error codes? It's important to identify what they are, and I don't think they're like the other error codes (because some of them are not really "errors" in the classic sense.

In fact, I'd prefer if we called them a "status code". As I commented in #356, I think there are numerous states the sender might wish to communicate:
1) You got all of the objects in the range;
2) You got almost all of the objects, but some were dropped for latency/bandwidth reasons
3) The track was truncated for some reason
and possibly, a relay might say:
4) You got everything I have but i'm not sure if that's everything

2024-02-28 16:58 UTC, martinduke approved these changes

2024-02-28 17:03 UTC, wilaw commented on draft-ietf-moq-transport.md
> +## SUBSCRIBE_CANCEL {#message-subscribe-cancel}
I agree with Martin on this. UNSUBSCRIBE is clearly the semantic negation of SUBSCRIBE, while SUBSCRIBE_CANCEL leaves me with no intuitive understanding as to what is happening.

2024-02-28 17:08 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +## SUBSCRIBE_CANCEL {#message-subscribe-cancel}
I am not pushing against the PR ,but slight preference on the names. But I can live with it 

My preference would be

Subscribe --> Unsubscribe (both sent by the subscriber)
SubscribeCancel -> Sent by the publisher after sending an OK to subscribe

2024-02-28 17:31 UTC, fluffy commented
So my notes from this discussion. CLOSE is confusing with QUIC layer.  People seemed to prefer UNSUBSCRIBE over SUBSCRIBE_CLOSE. I love the move aware from RST and FIN as naming.

2024-02-28 18:42 UTC, ianswett commented on draft-ietf-moq-transport.md
> +## SUBSCRIBE_CANCEL {#message-subscribe-cancel}
I renamed these back to UNSUBSCRIBE and UNANNOUNCE.

2024-02-29 06:13 UTC, suhasHere requested changes
Thanks Ian .. Overall it looks fine except for using SubscribeClosed as a response for Unsubsubscrib.
 
Also another nit, I preferred SubscribeEnded better than closed since it seems more easy to think when you read the name

2024-02-29 06:13 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +the final Object.
I don't think we need a response for Unsubscribe . The data path should carry the information on the final group/object.

2024-02-29 06:13 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +{: #moq-transport-subscribe-cancel-format title="MOQT UNSUBSCRIBE Message"}
I think this should be renamed to unsubscribe.

2024-02-29 15:12 UTC, suhasHere commented on draft-ietf-moq-transport.md
>    Subscribe ID (i),
s/SUBSCRIBE_CLOSED/SUBSCRIBE_END to have naming not to conflate with underlying transport usages

2024-02-29 15:58 UTC, ianswett commented on draft-ietf-moq-transport.md
> +the final Object.
Putting it in the data path makes sense if it's going to be cached and it's "Part of the track", but for state that's specific to a subscription, like the last Object sent, I think its makes more sense for it to be in subscription specific messages.

2024-02-29 15:58 UTC, ianswett commented on draft-ietf-moq-transport.md
> +{: #moq-transport-subscribe-cancel-format title="MOQT UNSUBSCRIBE Message"}
```suggestion
{: #moq-transport-unsubscribe-format title="MOQT UNSUBSCRIBE Message"}
```

2024-02-29 16:00 UTC, ianswett commented on draft-ietf-moq-transport.md
> +{: #moq-transport-subscribe-cancel-format title="MOQT UNSUBSCRIBE Message"}
Good catch, fixed.

2024-02-29 17:16 UTC, fluffy requested changes

2024-02-29 17:16 UTC, fluffy commented on draft-ietf-moq-transport.md
> +| 0x4  | Subscription Ended        |
I don't know what causes this one on a relay.

2024-02-29 17:16 UTC, fluffy commented on draft-ietf-moq-transport.md
> +| 0x3  | Track Ended               |
Just becasue a track has ended does not mean all the data has been delivered. I don't know how a relay would know when it could send this. I think it is better for the subscriber to just unsubscribe once it has the data. To put this more specifically, I don't know how a relay would be able to know when to send this.

2024-03-01 00:03 UTC, afrind commented on draft-ietf-moq-transport.md
> +| 0x3  | Track Ended               |
> I don't know how a relay would be able to know when to send this.

A relay could send it when it receives a SUBSCRIBE_CLOSE from the publisher with code=Track Ended?

2024-03-01 00:13 UTC, ianswett commented on draft-ietf-moq-transport.md
> +| 0x4  | Subscription Ended        |
You delivered all the requested data up to the end Object and Group.

2024-03-01 00:15 UTC, ianswett commented on draft-ietf-moq-transport.md
> +| 0x3  | Track Ended               |
I have mixed feelings about this one, so I'd be happy to remove it if we think the track end should be explicit in the Object model.  If so, we could just use Subscription Ended when the track ends.

2024-03-04 02:51 UTC, merged