Clarify Send Order
moq-wg/moq-transport pull request #417
Opened 2024-03-18 12:28 UTC by ianswett

Merges the two send order approaches because it appears they're very similar from the perspective of MoQ transport and removes text that is not relevant to MoQ Transport.

2024-03-18 21:53 UTC, fluffy commented
On my todo list to review but need to think about carefully on this one.

2024-03-19 07:10 UTC, fluffy commented on draft-ietf-moq-transport.md
> +{{send-order}}.
So the algorithm above refers to "priority". I agree we only need one integer but need to align names.

2024-03-19 07:17 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* Enable objects to be delivered in the order intended by the publisher
This sounds right for subscribe, I think it would be reasonable for Fetch to add an preference to deliver in order, or in reverse order.

2024-03-19 07:25 UTC, fluffy approved these changes
Few small comments on the text.  

At some level, I don't think this is enough. It does not deal with deciding what track to send next when there are objects from multiple tracks waiting to be sent to the same client.  But that said, I think we should merge this, start using it, then fix it and extend it as we learn more.

2024-03-19 08:19 UTC, suhasHere commented
+1 on the simplification and keep it focussed.

2024-03-19 08:20 UTC, suhasHere approved these changes
This PR is needed and is focussed.

2024-03-19 09:22 UTC, kixelated requested changes
I very much like the cleanup but there's some conflicts, hence being two separate sections in the first place.

2024-03-19 09:22 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* Within the same group, objects with a lower priority number (e.g. 1)
Priorities are applied to streams so this gets super confusing based on the stream mode. The object_id is not always known after the stream header (track/group mode); am I supposed to change the stream priority in the middle of a stream?

2024-03-19 09:22 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* Objects from later groups are sent before objects of previous groups.
What happens when a newer group has a higher send order?

I think it's a great recommendation to send newer groups first... unless you want head-of-line blocking for reliable live or VOD. This text makes it seem illegal?

2024-03-19 09:22 UTC, kixelated commented on draft-ietf-moq-transport.md
>  When nodes or relays have to choose which object to send next, they
I think this text could be salvaged by recommending how `send_order` is computed. Otherwise it just conflicts with the above paragraphs that just tell you to use send order.

```suggestion
When the publisher chooses which object to send next via `send_order`, they
```

2024-03-19 09:22 UTC, kixelated commented on draft-ietf-moq-transport.md
> -### Proposal - Ordering by Priorities {#ordering-by-priorities}
I feel like this proposal has been deprecated since implementing stream mapping, since the priority is in the stream header now. Relays are expected to respect it and forward streams as they were received.

2024-03-19 09:22 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* Within the same group and priority, objects with a lower object-id
Regardless of send order?

2024-03-19 16:39 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +* Within the same group, objects with a lower priority number (e.g. 1)
@kixelated can you please elaborate on what needs clarification here ?   Streaming modes naturally fit with priorities and we have implemented the same.

If stream per group is selected , all the objects with in a group have same priority.  So objects are delivered in the receive order at a relay within a stream.
if stream per object is selected and if the application marks all the objects with same priority within a group, then objects end up on the same priority queue level and are sent in the receive order.  If application marks each object with a different priorities, they end up on different levels in the queue and are sent according to the priority order.

The above text seems to cover all the cases if am reading it right.

2024-03-20 00:43 UTC, ianswett commented on draft-ietf-moq-transport.md
> +{{send-order}}.
Good point, personally I think I like "Object Priority" based on how it's discussed and used.  But suggestions are welcome.

2024-03-20 18:28 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* Within the same group, objects with a lower priority number (e.g. 1)
So in general this text needs some clarification on if it's normative or non-normative. I interpret it as normative, outlining the algorithm that each publisher uses to compute `send_order`.

If so, it breaks some use-cases, like using send order for head-of-line blocking. It also just makes the `send_order` redundant, as a publisher could compute the send order using `group_id`, `object_id` and these rules. 

And what happens when there's a mismatch? Is a relay supposed to error if `send_order` does not follow these rules?

I mean this was the crux of the debate way back then and why there are two sections. I thought the publisher should bake the rules into the send_order, while Christian thought we should have explicit rules. This PR is effectively doing both by merging the sections together; allowing publishers to choose the send order per stream but dictating the rules?

2024-03-23 12:31 UTC, kixelated commented
Also +1 to renaming `send order` to `priority`.

2024-03-23 18:14 UTC, suhasHere commented
> Also +1 to renaming `send order` to `priority`.

+1

2024-03-24 14:34 UTC, suhasHere commented on draft-ietf-moq-transport.md
> -### Proposal - Ordering by Priorities {#ordering-by-priorities}
Priority is saved as part of "Canonical Object" along with Object Forwarding preference . So that when they are served from  cache, regardless of stream mapping, right priority is applied and mapped to the right stream.

2024-03-24 22:21 UTC, afrind reviewed
Individual Review:

Overall this is an improvement over the text that we have.  I don't think it's the end of the story but it's probably a good incremental step for now?

2024-03-24 22:21 UTC, afrind commented on draft-ietf-moq-transport.md
> +contents of each object are still delivered in order.
s/still/always/ ?

2024-03-24 22:21 UTC, afrind commented on draft-ietf-moq-transport.md
> +* Within the same group, objects with a lower priority number (e.g. 1)
We've got text elsewhere that says that:

* when using stream-per-group, all objects have the same priority (sort of, see note)
* when using stream-per-group, the relay can't skip or reorder objects within the group

It might help clarify if this section referenced those bits, or explained the intersection of forwarding preferences and priorities.

Note: Our wire format allows the same group to be transmitted with different priorities if the group is carried on two or more streams (eg: disconnect in the middle of a group, objects 1-10 on stream 1, objects 11-20 on a different stream, or connection).

2024-03-24 22:21 UTC, afrind commented on draft-ietf-moq-transport.md
> +* Objects from later groups are sent before objects of previous groups.
I think this text should be scoped to tiebreakers:

"When objects from two or more groups have the same priority, send the objects from the more recent group first"

But for the "reliable live" case, you probably still want a subscriber side override to get groups in ascending order.

2024-03-24 22:21 UTC, afrind commented on draft-ietf-moq-transport.md
> +* Within the same group and priority, objects with a lower object-id
Here priority == send order, so the qualifier (within the same group and priority) is that these objects have identical send order.

2024-05-26 20:03 UTC, ianswett commented on draft-ietf-moq-transport.md
> +contents of each object are still delivered in order.
```suggestion
contents of each object are delivered in order.
```

2024-06-20 04:46 UTC, ianswett commented
At the interim, we arrived at a much clearer direction on priorities, so closing this.

2024-06-20 04:46 UTC, closed without merging