Split SUBSCRIBE into SUBSCRIBE and FETCH
moq-wg/moq-transport pull request #421
Opened 2024-03-19 06:11 UTC by ianswett

A PR corresponding to: https://datatracker.ietf.org/meeting/119/materials/slides-119-moq-subscribe-and-fetch

Fixes #269 
Fixes #296
Fixes #350 
Fixes #326
Fixes #377
Fixes #312 
Fixes #353

Also relevant to #396, #326

2024-03-19 06:22 UTC, hardie commented on draft-ietf-moq-transport.md
> +A subscriber MUST NOT subscribe to the same track twice within a session.
I thought we had agreed that a client could want multiple copies for different uses (e.g. storage vs. render).  If it did that, using two different start locations, why would that be forbidden in a single session?

2024-03-19 06:26 UTC, ianswett commented on draft-ietf-moq-transport.md
> +A subscriber MUST NOT subscribe to the same track twice within a session.
The cases one would want multiple copies are covered by FETCH.  Having multiple subscribes can add complexity in some cases and I'm not aware of a clear usecase.

2024-03-19 06:29 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +A subscriber MUST NOT subscribe to the same track twice within a session.
For use-case where i want to catch up last 5 mins, while i join the call live. I can see it implemented with subscribe , fetch combination ..

2024-03-19 06:29 UTC, ianswett commented on draft-ietf-moq-transport.md
> +TODO: Should these be the first Group being delivered?  If the previous group
```suggestion
TODO: Should these be the first Group being delivered?  If the last group
```

2024-03-19 06:30 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +to a HTTP HEAD request?
wonder if we should make it invalid to set its value as 0 to avoid ambiguities or make it optional field and if it is omitted it means as long as track is alive?

2024-03-19 06:31 UTC, ianswett commented on draft-ietf-moq-transport.md
> +{: #moq-transport-subscribe-format title="MOQT FETCH Message"}
```suggestion
{: #moq-transport-fetch-format title="MOQT FETCH Message"}
```

2024-03-19 06:32 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +Next Group (0x2): Start at the first Object from from the next group.
s/from from/from

2024-03-19 06:36 UTC, ianswett commented on draft-ietf-moq-transport.md
> +to a HTTP HEAD request?
I think we need a way to say that there is no limit on the number of groups.  We can encode that in a number of ways, ie: 6 modes instead of 3, etc.

2024-03-19 06:37 UTC, suhasHere approved these changes
Thanks @ianswett  This seems to be heading in the right direction. I do have few nits and clarification questions (posted)

2024-03-19 06:52 UTC, fluffy commented on draft-ietf-moq-transport.md
> +as Objects would be delivered with SUBSCRIBE.  When possible, earlier
slight tweak, instead of  earlier, I think it would be better to use lower object id because order of things were delivered in time could be different than that

2024-03-19 06:53 UTC, fluffy commented on draft-ietf-moq-transport.md
> +the publishers to identify a given subscription.
perhaps change "subscription" to "fetch"

2024-03-19 06:58 UTC, suhasHere commented on draft-ietf-moq-transport.md
>  STREAM_HEADER_GROUP Message {
STREAM_SUBSCRIBE_GROUP/STREAM_FETCH_GROUP

2024-03-19 07:02 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +ie: by making ContentExists an enum?
If the last group was cached , but TTL expired on it and got removed. Subscribe should start from the data it has..

2024-03-19 07:27 UTC, fluffy approved these changes

2024-03-19 07:27 UTC, fluffy commented on draft-ietf-moq-transport.md
> +}
This comment could be in a different PR, but I think it might be good to add an flag to the fetch that indicated the results should be delivered in reverse order.

2024-03-19 07:36 UTC, ianswett commented on draft-ietf-moq-transport.md
>  STREAM_HEADER_GROUP Message {
```suggestion
STREAM_SUBSCRIBE_GROUP/STREAM_FETCH_GROUP Message {
```

2024-03-19 07:37 UTC, ianswett commented on draft-ietf-moq-transport.md
> +Next Group (0x2): Start at the first Object from from the next group.
```suggestion
Next Group (0x2): Start at the first Object from the next group.
```

2024-03-19 08:04 UTC, ianswett commented on draft-ietf-moq-transport.md
> +}
Thanks, I would like to have that conversation along with the larger priorities conversation if possible, but it's a completely reasonable idea.

2024-03-19 08:06 UTC, ianswett commented on draft-ietf-moq-transport.md
> +ie: by making ContentExists an enum?
Agreed, my concern is that if last isn't available, how is that indicated?  If one finds out the largest group ID is 3, and it asked for last, it would expect to receive group 2, but if it's not available, it wouldn't.

2024-03-19 08:31 UTC, janaiyengar reviewed
Broadly looks good, follows the arc of what we discussed.

2024-03-19 08:31 UTC, janaiyengar commented on draft-ietf-moq-transport.md
> +A subscriber MUST NOT subscribe to the same track twice within a session.
@Ted: We had agreed on allowing this for FETCH, and explicitly disallowing dups for SUBSCRIBE, since FETCH is more like an HTTP GET.

2024-03-19 08:54 UTC, kixelated requested changes
I understand the desire to split the world into VOD and REALTIME via FETCH and SUBSCRIBE, but I think this proposal misses the nuances of live streams that startle between both worlds. I'd like some clarification in #419 as to how a player is supposed to use this API because it seems pretty terrible.

And I think the duplication between SUBSCRIBE/FETCH is just super messy. The justification is that now a relay doesn't need to implement relative ranges beyond +- 1 group. If that's a sticking point for folks, then I much rather add that restriction to the current SUBSCRIBE message along with `order=ASC|DESC` in #411.

2024-03-19 08:54 UTC, kixelated commented on draft-ietf-moq-transport.md
> +A subscriber MUST NOT subscribe to the same track twice within a session.
What's the benefit to adding this restriction, effectively mandating deduplication? I don't see what's the harm in allowing dumb proxies that don't deduplicate subscriptions.

2024-03-19 08:54 UTC, kixelated commented on draft-ietf-moq-transport.md
> +}
I'd like a flag too, see #411. We need it for SUBSCRIBE in the reliable live use-case.

2024-03-19 08:54 UTC, kixelated commented on draft-ietf-moq-transport.md
> +| 0x21  | FETCH_CANCEL ({{message-fetch-cancel}})             |
There needs to be a `FETCH_OK`/`FETCH_ERROR` message too. I don't see how you can signal stuff like 404 or unauthorized otherwise.

2024-03-19 08:54 UTC, kixelated commented on draft-ietf-moq-transport.md
> +| 0x50  | STREAM_SUBSCRIBE_TRACK ({{multi-object-streams}})   |
Can we shard the `id` (even/odd) based on if it's a FETCH/SUBSCRIBE?

Scratch that, why does it even matter? Why not have SUBSCRIBE and FETCH share the same ID space?

2024-03-19 09:00 UTC, kixelated requested changes
And I think this breaks ABR if I understand correctly?

2024-03-19 09:00 UTC, kixelated commented on draft-ietf-moq-transport.md
> +There are 3 modes to indicate where to start the subscription:
Doesn't this break seamless ABR, since you can't subscribe using an absolute group in the future? The best you can do is subscribe to next group and pray for no race condition.

2024-03-19 11:40 UTC, wilaw commented
How would a live player that wants to start 3 groups back from the live head use this combination of SUBSCRIBE and FETCH? It could issue the SUBSCRIBE, which would deliver the latest group and all future groups as well as information about the latest (largest) group number. However, since group numbers increase monotonically by a variable increment, the player cannot use this information to construct the appropriate FETCH, because it cannot predict the two prior group numbers.

2024-03-19 13:37 UTC, suhasHere commented
> However, since group numbers increase monotonically by a variable increment, the player cannot use this information to construct the appropriate FETCH, because it cannot predict the two prior group numbers.

Player needs to know how the group numbers increment.  Its the application and if it has no clue , then something is already wrong.

2024-03-19 16:43 UTC, suhasHere commented
> If that's a sticking point for folks, then I much rather add that restriction to the current SUBSCRIBE message along with `order=ASC|DESC` as proposed in #411.

Can you please answer my question on the open issue on how can relay make such decision upstream when there are conflicting subscriptions with respect to the order.  May be last mile subscribe has a utility, but I am not sure how to solve the open issue on this.

2024-03-19 18:38 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +A subscriber MUST NOT subscribe to the same track twice within a session.
Deduping multiple conflicting subscriptions is not straighforward, also it leads to weird edge cases when there is partial data . I think these were reflected during Denver interim discussions at some point.

2024-03-20 00:52 UTC, fluffy commented on draft-ietf-moq-transport.md
> +A subscriber MUST NOT subscribe to the same track twice within a session.
Is there an use that drives need for duplicate subscriptions

2024-03-20 17:15 UTC, kixelated commented on draft-ietf-moq-transport.md
> +A subscriber MUST NOT subscribe to the same track twice within a session.
> Is there an use that drives need for duplicate subscriptions

As of the current draft, AUTH is in the SUBSCRIBE message. A relay that doesn't know the auth scheme would have to forward each SUBSCRIBE upstream.

I strongly think we should decouple auth anyway. I'd like to see an AUTH_NAMESPACE message that could be used for subsequent ANNOUNCE and SUBSCRIBE messages on the control stream.

> Deduping multiple conflicting subscriptions is not straighforward, also it leads to weird edge cases when there is partial data . I think these were reflected during Denver interim discussions at some point.

Yeah that's my point. This restriction forces a relay to deduplicate, for example if two viewers issue:

```
viewer1 -> SUBSCRIBE start=next
...
viewer2 -> SUBSCRIBE start=prev
```

A relay SHOULD deduplicate these for the upstream subscribe, but this text makes it a MUST. Doing this is tricky much like the existing SUBSCRIBE message.

2024-03-20 17:21 UTC, kixelated commented on draft-ietf-moq-transport.md
> +A subscriber MUST NOT subscribe to the same track twice within a session.
As a side note.

> A subscriber MUST NOT subscribe to the same track twice within a session.

I think the intent is to prevent duplicate concurrent subscriptions. However, a literal interpretation is that you're never allowed to subscribe again even after an unsubscribe, which of course breaks many things.

2024-03-20 17:27 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  StartGroup (i),
What happens if the start group/object is in the future?

2024-03-20 17:27 UTC, kixelated commented on draft-ietf-moq-transport.md
> +| 0x21  | FETCH_CANCEL ({{message-fetch-cancel}})             |
Speaking of 404, what happens if some of the groups/objects in the range requested don't exist or have expired? Without a way of signaling that, the subscriber would wait indefinitely for the FETCH to complete.

ex. a DVR client that issues a FETCH for 60s ago to replay a highlight. However the start of the highlight may have been evicted from the LRU by then, and is no longer available on origin either.

2024-03-20 18:06 UTC, kixelated commented
> > If that's a sticking point for folks, then I much rather add that restriction to the current SUBSCRIBE message along with `order=ASC|DESC` as proposed in #411.
> 
> Can you please answer my question on the open issue on how can relay make such decision upstream when there are conflicting subscriptions with respect to the order. May be last mile subscribe has a utility, but I am not sure how to solve the open issue on this.

What about `order=ASC | DESC | DEFAULT`? The relay could let the publisher/upstream choose like it does today.

Note that FETCH is not immune to this. There could be a continuous SUBSCRIBE from broadcaster -> origin (ascending) and a FETCH from origin -> relay (descending). Or a viewer could SUBSCRIBE and later another viewer could FETCH, leveraging some of the existing subscription.

viewer1:
```
-> SUBSCRIBE 
<- SUBSCRIBE_OK start=420
<- OBJECT 420
(upstream congestion)
<- OBJECT 422
<- OBJECT 423
<- OBJECT 421
```

viewer2:
```
-> FETCH start=419 end=421
<- OBJECT 420
<- OBJECT 422
(blocked on 423)
<- OBJECT 421
```

But I dunno, I kind of feel like this is a non-issue. Viewers will either request the same order, or upstream congestion is rare, or defaulting to ORDER=desc is required for live and good enough for VOD and reliable live. We're talking about edge cases of a prioritization scheme, which historically don't have much impact.

2024-03-22 02:30 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +| 0x21  | FETCH_CANCEL ({{message-fetch-cancel}})             |
+1 on needing a way for the fetch response to identify gaps.  We need to add FETCH_OK to include something on the lines of

Say if FETCH request was for the range 100-200 and and let's say for whatever reasons 110-120, 190-200 are missing, the response should have

```
{
    Gaps {
    type-group 
    [110-120,  190-200]
  }
}
```

Nice thing about fetch is it is able to find answers

2024-03-23 15:33 UTC, suhasHere commented
> What about `order=ASC | DESC | DEFAULT`? The relay could let the publisher/upstream choose like it does today.

The challenge here is any recommendation we give here will not be appropriate for Relays. I have not seen a case where given an application, say that publishes oldest to newest, have some percentage of subscribers wanting oldest to newest and rest asking newest to oldest. Subscribers (endpoints) knows what application they are participating it and they know the right expectation. 

OTOH I can see fetch being independent request, can influence some form of control in the receive order. But even there I am yet to be convinced if there is a real use-case/requirement that few endpoints fetch in one order vs few in a different order for a given application. 

My main concern is we are pushing recommendations/suggestions on relays for applications and Relays can't make a informed decision under ambiguities.

2024-03-24 22:28 UTC, afrind commented
Individual Comment:

> I am unaware of cases where given an application, say that publishes oldest to newest, have some percentage of subscribers wanting oldest to newest and rest asking newest to oldest

Here's a use case: A live stream with a recording option.  Some subscribers are watching live, so want newest first.  Recording subscriber doesn't care about latency and would prefer oldest first.  I think the SUBSCRIBE verb is still the right one for both cases, rather than forcing the recorder to use FETCH in a loop?

2024-03-24 23:29 UTC, fluffy commented
The requirements for recording are usually record all the objects that were sent. If a object was lost and never sent, the recording system would not want to wait for it and not record future packets.  I'm pretty skeptical of any use case where latency does not matter being a core case for MoQ. That said, a recoding system that did a subscribe to the whole namespace to get all the objects as they were produced sounds like the most likely thing for recording systems to build.

2024-03-24 23:32 UTC, fluffy commented
Please see my related email on the the list. Thanks

2024-03-25 20:55 UTC, afrind commented on draft-ietf-moq-transport.md
> +Last Group (0x0): Start from the the largest group for which the relay
Individual comment:

> the largest group for which the relay has received the last object

I find this strange and hard to reason about.  

First, we don't yet have a mechanism for the relay to know the last object in the group (though we all assume we will eventually have one).  But if we really want this semantic, maybe we want to delay adding this mode to the draft until we can actually implement it.

What's strange to me is that if the relay has received [group 7: all objects] and [group 8: all object *except the last*], and [group 9, object 0], a request for `Last Group` would serve 7 instead of 8.  Is there an application where that's the desired behavior?  

I find it hard to reason about because I could ask 3 different relays and get 3 different groups relative to the live head, depending on what happens to be in their cache. 

There are two other ways to handle last that seem more straightforward to me:

1. Last is the largest group smaller than current for which the relay has *any* objects
2. Last is `current group - 1`

Option 1 suffers from the same potential relay inconsistency as the proposed text, but it seems more likely to be useful.

I prefer option 2 because it is *predictable* - I know exactly what group I am going to get relative to the live head.  I get the vibe that some folks have a specific use case in mind for discontiguous group ids, which would mean option 2 wouldn't work for them.  If there is a use-case, can we write it down (maybe mail to the list) so we can evaluate pros and cons? I think Luke has given a use case for making group IDs sequential: they can be used for gap detection, and would allow relays to do simple math to compute relative groups.

2024-03-25 21:05 UTC, kixelated commented on draft-ietf-moq-transport.md
> +Last Group (0x0): Start from the the largest group for which the relay
Oh yeah I didn't even read the full text. Any subscribe decision based on a relay's current cache is going to be problematic. 

`current-1` makes more sense. The wrinkle is that `group_ids` are apparently not sequential , so group-1 might not exist (hence why -N was more flexible).

I would remove this mode altogether.

2024-03-27 21:42 UTC, martinduke commented on draft-ietf-moq-transport.md
> +  EndObject (i),
Is there some way to express "give me all the objects in the group" if we don't know the max object ID?

2024-03-28 00:42 UTC, afrind commented on draft-ietf-moq-transport.md
> +  EndObject (i),
With SUBSCRIBE, the requested range was [Start, End), so you can request Start=X/0, End=X+1/0 to get all the objects in group X.

2024-03-28 20:08 UTC, afrind commented on draft-ietf-moq-transport.md
> +  EndObject (i),
Individual Comment:

What is the normative behavior if `end` is larger than `largest` for a live track?

Here are some possibilities:

1) Fail the request
2) return everything up to min(end, live) at the time of the request, indicate end in a fetch OK
3) return everything up to min(end, live) at the time of the response, indicate end in a fetch trailer
4) When the fetch catches up to live, continue offering FETCH semantics for new objects (all objects delivered or gap notification), until end is reached

1 and 2 are fairly easy to implement.  3 is a little trickier but accounts for live head moving in the time it takes to serve the beginning of the request.  4 feels the hardest, but maybe handles the "reliable live" use case the best?

Are the other options?

2024-03-28 20:39 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  EndObject (i),
I'd vote for 4 - `When the fetch catches up to live, continue offering FETCH semantics for new objects (all objects delivered or gap notification), until end is reached .`. As you state, this satisfies a "reliable live" use case with a start behind the live head. 

I'd also suggest that EndGroup and EndObject can be omitted, in which it defaults to the behavior [4]. This prevents the ugliness of people asking for group 99999999999999 when all they really want is delivery until end-of -track.

2024-07-15 22:02 UTC, ianswett commented
The draft has evolved substantially, so if we want to revisit SUBSCRIBE vs FETCH, we will need a new PR.

2024-07-15 22:02 UTC, closed without merging