END_OF_GROUP message
moq-wg/moq-transport pull request #426
Opened 2024-04-03 21:34 UTC by martinduke

Here's a explicit signal for missing objects.

2024-04-03 22:23 UTC, kixelated reviewed
What's the use-case behind this message?

I think it's meant to support reliable live when using a stream per object. The player will buffer until it receives the entire group, but it can't do that if it doesn't know the full size of the group.

However, I don't think this message accomplishes that by itself since there can be gaps within the group. The player might know the intended size of the group, but any RESET_STREAM will cause it to block awaiting the full group to arrive.

I think we need the group size in conjunction with #423. Both messages are so similar that maybe there could be some overlap; I'm not sure.

2024-04-03 22:23 UTC, kixelated commented on draft-ietf-moq-transport.md
> +When a track's forwarding preference is 'Datagram', END_OF_GROUP messages MUST
Why not?

2024-04-03 22:23 UTC, kixelated commented on draft-ietf-moq-transport.md
> +resets, a receiver may not observe an END_OF_GROUP message for all groups.
Can we eliminate this line and make this a reliable message? The point of this message is to remove the end group ambiguity due to unreliability, and we can't do that if this message itself is unreliable.

2024-04-03 22:23 UTC, kixelated commented on draft-ietf-moq-transport.md
> +When a track's forwarding preference is 'Group', the END_OF_GROUP message MUST
But I also like the existing behavior of using stream FIN to signal the end of a group. This END_OF_GROUP message feels like compliance, trying to address an issue that only impacts one delivery mode.

2024-04-03 22:23 UTC, kixelated commented on draft-ietf-moq-transport.md
> +group. A publisher SHOULD send an END_OF_GROUP message with a Next Object ID of
This `SHOULD` is a `MUST` imo, otherwise you'll break clients that actually use this message (ex. reliable live).

Also, this breaks being able to use the presentation timestamp as the group ID, as you would have to send a boatload of END_OF_GROUP messages. I'm all for that but I want to make sure we've discussed it.

2024-04-03 22:38 UTC, kixelated commented
Oh, and I'd like to only use this message when using a stream per object. It's not relevant for the other modes.

Alternatively, we could just make this a property of the mode itself. You don't know the final group size when using a stream per object, and it's probably just fine for the intended use-cases?

2024-04-04 16:15 UTC, martinduke commented on draft-ietf-moq-transport.md
> +cases, they may not arrive in time to be relayed in that order.
Imagine a case where an MoQ publisher is receiving objects via a different transport. Could it not happen? If not, I'm happy to make it a MUST.

2024-04-04 16:17 UTC, martinduke commented
> What's the use-case behind this message?
> 
> I think it's meant to support reliable live when using a stream per object. The player will block until it receives the entire group, but it can't do that if it doesn't know the full size of the group.

I don't know use cases, but people keep saying we need a way to identify missing objects in a group.

> 
> However, I don't think this message accomplishes that by itself since there can be gaps within the group. The player might know the intended size of the group, but any RESET_STREAM will cause it to block awaiting the full group to arrive.

The first part of the PR says that publishers MUST NOT skip Object IDs. So if you're missing an Object ID, either the sender didn't get it, or it chose not to send it.

> 
> I think we need the group size in conjunction with #423. Both messages are so similar that maybe there could be some overlap; I'm not sure.

2024-04-04 16:20 UTC, martinduke commented on draft-ietf-moq-transport.md
> +When a track's forwarding preference is 'Group', the END_OF_GROUP message MUST
Q: If a sender decides not to send all of the objects in a group, can it close with a FIN, or does it have to use RESET_STREAM?

2024-04-04 16:21 UTC, martinduke commented on draft-ietf-moq-transport.md
> +When a track's forwarding preference is 'Datagram', END_OF_GROUP messages MUST
We could just have it open a stream, but I figure if you're in Datagram mode you are not concerned about reliability.

2024-04-04 16:23 UTC, martinduke commented on draft-ietf-moq-transport.md
> +group. A publisher SHOULD send an END_OF_GROUP message with a Next Object ID of
SGTM, changed. 

I don't think it "breaks" anything, but if you're concerned about message bandwidth we could allow this to apply to a range of groups or invent a similar message.

2024-04-04 16:25 UTC, martinduke commented
> Oh, and I'd like to only use this message when using a stream per object. It's not relevant for the other modes.
> 
> Alternatively, we could just make this a property of the mode itself. You don't know the final group size when using a stream per object, and it's probably just fine for the intended use-cases?

I don't think that's right. If it's a track stream, and the sender has to omit some objects, this is very much relevant.

You are presupposing some restrictions on how the various forwarding preferences can be used in conjunction with various reliability and latency requirements. If those restrictions exist, we need to write those down somewhere.

2024-04-04 16:26 UTC, martinduke commented on draft-ietf-moq-transport.md
> +resets, a receiver may not observe an END_OF_GROUP message for all groups.
If a stream is reset, you a priori know you don't have everything. Don't reset a stream if getting all the objects is important!

2024-04-04 16:28 UTC, martinduke commented
> Oh, and I'd like to only use this message when using a stream per object. It's not relevant for the other modes.
> 
> Alternatively, we could just make this a property of the mode itself. You don't know the final group size when using a stream per object, and it's probably just fine for the intended use-cases?

But what if a track can be used in several use cases? It's stuck with one forwarding preference!

2024-04-04 22:07 UTC, suhasHere requested changes
some comments.

2024-04-04 22:07 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +range does not include the last object of a group.
END_OF_GROUP must be sent on the same unidirectional stream that sent the last object for the group.  This should be sent regardless of the request range/location.

2024-04-04 22:07 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +zero when it skips a Group ID.
where is Next Object ID defined ?

2024-04-04 22:07 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +|-------|-----------------------------------------------------|
There was another proposal  here: https://github.com/moq-wg/moq-transport/pull/334/files

Not saying we do one vs the other. But I feel we need to agree upon requirements on
  - what such message indicate
  - when and where will it be sent,

2024-04-04 22:07 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +separate unidirectional stream per group to deliver the END_OF_GROUP message.
It must be sent on the same stream. not sure why it should be on a new stream

2024-04-05 03:37 UTC, kixelated commented on draft-ietf-moq-transport.md
> +cases, they may not arrive in time to be relayed in that order.
Yeah, the purpose of a stream per track is to allow dumb decoders. All media is delivered in decode order so it's trivial to handle and there's no reassembly buffer required. That goes out the window if the encoder is allowed to emit out of order. It's meant to be a direct replacement for RTMP in that regard.

2024-04-05 03:39 UTC, kixelated commented on draft-ietf-moq-transport.md
> +When a track's forwarding preference is 'Group', the END_OF_GROUP message MUST
IMO `RESET_STREAM` combined with `STREAM_DROPPED` (#423). We don't want relays silently truncating streams and pretending like nothing happened.

2024-04-05 03:56 UTC, kixelated requested changes
Let's identify the use-cases that needs to know the group size and make sure this meets the requirements. I don't think it does.

2024-04-05 03:56 UTC, kixelated commented on draft-ietf-moq-transport.md
> +resets, a receiver may not observe an END_OF_GROUP message for all groups.
I think we need to focus on the use-case here. A player needs know the final group size (and any gaps) for reliable playback (live and VOD) when using a stream per object. 

If this message is optional in any way then the use-case does not work. I think it needs to be mandatory to send an END_OF_GROUP message for each group (when using an object per stream).

2024-04-05 03:56 UTC, kixelated commented on draft-ietf-moq-transport.md
> +publisher.
Yeah, I think this paragraph is awkward.

I think what you're trying to say is that there must be an `END_OF_GROUP` for each group within the subscription range, even if it's size 0.

2024-04-10 15:49 UTC, fluffy requested changes
I like the idea of a publisher being able to publish an object that indicates there will be no hither object in the group. Or not higher groups in the track. I think this should be allowed and explicit and on what I think of as the dataplane. I put in a similar proposal in #429. I like all these parts of this proposal. 

I do not like the relays needing to require that objects inside the group need to be produced in order or increment by one. I don't see that as needed for any of this to work int he relays work. Similarly I see no requirements for for oder that groups are produced or gaps between them. I can see how the catalog might indicate for a given track that the groups or object were sequential but does not seem to be a thing the relays should have to deal with. The reason I am concerned with this is moderne video codecs.

2024-04-10 18:55 UTC, martinduke commented
> I like the idea of a publisher being able to publish an object that indicates there will be no hither object in the group. Or not higher groups in the track. I think this should be allowed and explicit and on what I think of as the dataplane. I put in a similar proposal in #429. I like all these parts of this proposal.
> 
> I do not like the relays needing to require that objects inside the group need to be produced in order or increment by one. I don't see that as needed for any of this to work int he relays work. Similarly I see no requirements for for oder that groups are produced or gaps between them. I can see how the catalog might indicate for a given track that the groups or object were sequential but does not seem to be a thing the relays should have to deal with. The reason I am concerned with this is moderne video codecs.

The requirement for the publisher to not skip Object ID just makes the encoding more efficient. If you tell me there's a  use case for nonexistent object IDs, that's good enough for me, and we should probably do something closer to your PR.

2024-04-28 15:53 UTC, closed without merging