Add object status used to indicate lost or nonexistent objects
moq-wg/moq-transport pull request #429
Opened 2024-04-10 15:38 UTC by fluffy

This PR adds a status field to the object that allows an relay to indicate an object or group was lost or dropped. 
 
 It also allows a producer to indicate a object or group will not be produced including the cases for end of group and end of track. 
 
 The PR probably needs a bit more text on what what producers and relays do but I think this is close enough to get some initial discussion on this solution. 

Fixes #318
Fixes #427
Fixes most of #423 

Closes #334
Closes #426

2024-04-10 18:30 UTC, ianswett approved these changes
This feels like it solves a number of problems in a good way.

One quirk is that the Object status can change, but I believe the other object properties, like forwarding preference, do not change.  I don't have a problem with that, but it might be worth calling out?

2024-04-10 18:30 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* 0x1 := Object non existent at the publisher and has zero sized
Should we reference caching here?  It seems like both 1 and 2 are cacheable, because they won't change, but 3 and 4 are not?

2024-04-10 18:46 UTC, martinduke approved these changes
I think this fine. Like you, at this point I don't really care much how we spell it.

Compared with my proposal in #426, this is conceptually way simpler (no special rules for each forwarding preference) but is less byte-efficient. I'm happy to go with whatever the group decides.

2024-04-10 18:46 UTC, martinduke commented on draft-ietf-moq-transport.md
> +
"Any other value for status is a malformed message"

2024-04-10 19:00 UTC, ianswett commented
> I think this fine. Like you, at this point I don't really care much how we spell it.
> 
> Compared with my proposal in #426, this is conceptually way simpler (no special rules for each forwarding preference) but is less byte-efficient. I'm happy to go with whatever the group decides.

I think I'm happy to use a byte for this.  We can always optimize it later in a number of ways if we want.

2024-04-10 19:30 UTC, suhasHere approved these changes
This looks fine to me. Like the simplicity of the proposal
   - Data plane handles objects as usual regardless of their status when caching
   - Fetch like api, can reach to to status of the object/group to decide if they need to go upstream 
   This will enable some of the requirements of reliable live use-cases where the player needs to know if the producer dropped a given group/object.

2024-04-10 19:31 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
I think this needs to added in the canonical object definition as well. As this will be along with the object in the cache.

2024-04-10 19:32 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  indicates why data is missing.
s/ojects/objects.

2024-04-10 19:37 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +* 0x1 := Object non existent at the publisher and has zero sized
I think 3/4 are also cacheable esp when serving chain of relays. A downstream relay, if it has a knowledge of object status (as expired), can satisfy fetch request by requesting upstream.

2024-04-10 20:11 UTC, wilaw commented on draft-ietf-moq-transport.md
> +         be empty in this case.
We're signaling that we dropped an object by creating another object and sending that in its place. Is the belief that the removal of the payload will always ensure that this "message object" gets through, or need we deal with a condition in which this message object is delayed to the point that it is dropped too? At that point, do we send a placeholder object for the placeholder object for the real object?

2024-04-10 20:14 UTC, wilaw commented on draft-ietf-moq-transport.md
>  * Object Payload: An opaque payload intended for the consumer and SHOULD
Since most objects are not dropped or missing, the vast majority of the time we will be embedding a 0x0 byte for no reason. Since in all identified dropped or issuing situations the payload is 0, can we structure the header such that if a payload length of 0 is declared, then the next field carries the Object Status instead of the payload?

2024-04-10 20:49 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +* 0x1 := Object non existent at the publisher and has zero sized
I think we should either declare those non-cacheable, or have a flag in FETCH that says "refetch everything dropped at a relay", otherwise DVR/clipping use cases might not work.

2024-04-10 20:49 UTC, ianswett commented
> > I think this fine. Like you, at this point I don't really care much how we spell it.
> > Compared with my proposal in #426, this is conceptually way simpler (no special rules for each forwarding preference) but is less byte-efficient. I'm happy to go with whatever the group decides.
> 
> I think I'm happy to use a byte for this. We can always optimize it later in a number of ways if we want.

We can actually save a byte by omitting Object ID except for the first Object in the stream, because this allows the Objects to be sequential.  Similarly, we can omit GroupID if the delivery preference is track per stream.

2024-04-10 21:02 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +* 0x1 := Object non existent at the publisher and has zero sized
if this goes along with cached object and fetch happens for a object that has status other than 0x0, relay can issue fetch upstream.  Having it stored along with object be useful, isn't it ?

2024-04-10 21:10 UTC, vasilvv approved these changes
This is a dramatic improvement over the status quo, I think we should merge this without bikeshedding too much about the encoding for now.

2024-04-10 23:10 UTC, fluffy commented on draft-ietf-moq-transport.md
>  * Object Payload: An opaque payload intended for the consumer and SHOULD
I like that idea. For the control messages, I don't care about saving a byte but for the audio data, it makes a big difference.

2024-04-16 19:21 UTC, afrind reviewed
Individual Review:

Most of the statuses are not mutually exclusive (eg: an object can be available at the publisher, the end of a group, the end of track and dropped by the relay), though some are (an object can't be the end of track *without* being the end of a group, I think?).  I wonder if there's a different spelling that captures this?

The dropped/end/never-existed signals seem more important than other objects and we may need to be more specific about reliability properties and/or stream placement.

2024-04-16 19:21 UTC, afrind commented on draft-ietf-moq-transport.md
> +
The interaction with resetting the streams that carry these messages needs to be clarified.  Let's assume stream-per-group, and the sender has attempted to send several objects, but not all data is acked.  It then wants to drop the group, and cease retransmission of not-needed objects.  However, if it needs to write the drop marker into the same stream, it needs to continue retransmitting the objects in the group.

Also, we should specify what Object ID to use here in the case there is not a specific object ID when the relay wants to, say, tail drop the group.

2024-04-16 19:21 UTC, afrind commented on draft-ietf-moq-transport.md
> +         with this status for the group.
It's slightly awkward to use this wire encoding, since I might know object 10 is the last object in the group, and I send:

```
OBJECT g=x, id=10, status=0, payload
OBJECT g=x, id=10, status=END_OF_GROUP
```

2024-04-16 19:21 UTC, afrind commented on draft-ietf-moq-transport.md
> +         largest group and object produced in this track. This is sent
Does the end-of-track imply end-of-group?

2024-04-16 19:21 UTC, afrind commented on draft-ietf-moq-transport.md
> +         with this status for the group.
I think this is copypasta from above?

2024-04-16 19:21 UTC, afrind commented on draft-ietf-moq-transport.md
> +         largest group and object produced in this track. This is sent
This is an important message and we need to clarify the stream reset semantics here as well.

2024-04-17 05:09 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +* 0x0 := Object exists at the publisher and payload is non-null array of
i wonder if it helps to not have status 0x0 and having payload length of non-zero for the object in the cache is a proof of existence ??

We definitely need a way to mark if a publisher drops an object or decides not to produce at all ... which i believe are covered by other status values

2024-04-17 14:31 UTC, ianswett commented on draft-ietf-moq-transport.md
> +         with this status for the group.
It would be nice to be able to send:

`OBJECT` g=x, id=10, status=END_OF_GROUP, payload

2024-04-17 14:38 UTC, ianswett commented
> Individual Review:
> 
> Most of the statuses are not mutually exclusive (eg: an object can be available at the publisher, the end of a group, the end of track and dropped by the relay), though some are (an object can't be the end of track _without_ being the end of a group, I think?). I wonder if there's a different spelling that captures this?
> 
> The dropped/end/never-existed signals seem more important than other objects and we may need to be more specific about reliability properties and/or stream placement.

This is a good point.  Conceptually we need two enums: One to indicate if it's a Group Fin or Track Fin and one to indicate why there's no payload.

There are a lot of ways to encode that, but it's a bit nice, because the first enum is an immutable property of the Object and the latter is sort of a payload alternative.

2024-04-17 15:36 UTC, afrind commented on draft-ietf-moq-transport.md
> +         with this status for the group.
It's also possible the publisher doesn't know that object 10 is the end of the group when it's published.

2024-04-17 15:47 UTC, kixelated commented
I've only had a chance to glance, but how does this interact with RESET_STREAM?

Putting drop notifications within the OBJECT itself means that an object can only be dropped prior to being written to a stream. This is okay when used in conjunction with stream priorities, but it's not great. Ideally we can renege after committing data to a stream by resetting it.

IMO there should be a message indicating which objects were dropped upon a RESET_STREAM.

2024-04-17 16:42 UTC, fluffy commented on draft-ietf-moq-transport.md
> +         with this status for the group.
oops

2024-04-17 16:56 UTC, fluffy commented
Notes to myself:

Need text on reset. 
- could send object group drop on new stream 
- open an issue if we need this it 

Way to deal with sending zero length object 
- add an enum for this object is empty 

Way to indicate end track and I dropped it.
- perhaps better way than sending same object twice

2024-04-17 17:01 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +         with this status for the group.
My proposal is to remove status 0x0 .. since its redundant when payload length is > 0.
If we do that, then above will be simplified to following for marking end of the group
```
OBJECT g=x, id=10, status=END_OF_GROUP
```
where object id 10 is the largest group.

2024-04-17 17:02 UTC, fluffy commented on draft-ietf-moq-transport.md
> -{{send-order}} or priority {{ordering-by-priorities}} value.
Don't remove send order

2024-04-17 17:03 UTC, fluffy commented on draft-ietf-moq-transport.md
> -{{send-order}} or priority {{ordering-by-priorities}} value.
@kixelated - I will fix this not to remove it.

2024-04-17 17:22 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +         largest group and object produced in this track. This is sent
end of track must imply end of the last group in the track

2024-04-17 17:23 UTC, suhasHere commented
> Notes to myself:
> 
> Need text on reset.
> 
> * could send object group drop on new stream
> * open an issue if we need this it
> 
> Way to deal with sending zero length object
> 
> * add an enum for this object is empty
> 
> Way to indicate end track and I dropped it.
> 
> * perhaps better way than sending same object twice

@fluffy  i did leave the following comment https://github.com/moq-wg/moq-transport/pull/429#discussion_r1569172957

2024-04-17 17:28 UTC, kixelated requested changes

2024-04-17 17:28 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* Object Status: As enumeration used for missing or dropped objects that
IMO this status would only be sent in `OBJECT_DROPPED` on a separate stream,

2024-04-17 17:28 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of group. ObjectId identifies the largest object
IMO this should be a separate flag/message. `TRACK_FIN` and/or `GROUP_FIN` maybe.

2024-04-17 17:28 UTC, kixelated commented on draft-ietf-moq-transport.md
> +         with this status for the group.
IMO this should be a separate flag. `OBJECT_FIN` perhaps. 

Otherwise yeah it's confusing to sometimes receive a second OBJECT on a stream. Also it currently can't be encoded because OBJECT doesn't contain an explicit size (when per-stream).

2024-04-17 17:28 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* 0x3 := Object dropped at the relay. Sent by a relay indicating the
Do we really care which hop dropped the object? A subscriber really only needs to know if it can retry.

There's currently no way of signaling that a publisher dropped an object due to flow control, but it's retryable.

2024-04-17 17:28 UTC, kixelated commented on draft-ietf-moq-transport.md
> +         payload. Sent by the media producer and sent to indicate that
What's the difference between status code = 0x1 and a payload of size 0? Do we need this status code at all?

2024-04-17 17:28 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* 0x0 := Object exists at the publisher and payload is non-null array of
"object exists" is very strange.

Doesn't this status code just mean that the message contains a payload? Can we just state that?

2024-04-17 17:28 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* 0x2 := Group non existent. Sent by a publisher and indicates the group
Why not send a group with a single (FIN) object of size 0?

2024-04-17 17:28 UTC, kixelated commented on draft-ietf-moq-transport.md
> +         preference.
(also the payload is empty in this case)

2024-04-17 17:28 UTC, kixelated commented on draft-ietf-moq-transport.md
> +         the reasons specific to the producer.
(also the payload is empty in this case)

2024-04-17 17:28 UTC, kixelated commented on draft-ietf-moq-transport.md
> +         with this status for the group.
But I do like using a second message, because it means you don't have to know if it's the last object prior to transmitting it. I would just put it on a separate (reliable) stream like drop messages.

For example, encoders spit out P-frames and we can immediately send it as an OBJECT. Only when an encoder crates an I-frame (not predictable) then we can end the current group. There's no latency added.

An alternative is to have the object contains a "last of group/track" flag, but 
that requires buffering 1 frame and adds additional latency.

2024-04-17 17:28 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  Object Status (i),
A lot of these end statuses become redundant when not using a stream per object. I think it's fine but needs to be called out.

2024-04-17 17:28 UTC, kixelated commented on draft-ietf-moq-transport.md
> -* Object Send Order: An integer indicating the object send order
pls keep

2024-04-17 18:14 UTC, kixelated commented
After reviewing fully, yeah I don't think we can decouple drops from resets.

When any publisher (including a relay) decides to drop an object, it will also reset the associated QUIC stream. Otherwise, the publisher either has to either delay writing to streams (TCP low watermark) or commit to delivering objects it wants to drop.

And the problem with TCP low watermark in MoQ is of course... _priorities_. Newer content is usually more important, so even if we already have N bytes queued in the QUIC layer, our new content needs to skip the queue. The only way to do that is to actually write to the QUIC stream marked at a higher priority... or reset streams currently queued.

2024-04-21 16:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +
made a protocol error in next version of PR

2024-04-21 17:02 UTC, fluffy commented on draft-ietf-moq-transport.md
>  * Object Payload: An opaque payload intended for the consumer and SHOULD
Added this in

2024-04-21 17:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* 0x0 := Object exists at the publisher and payload is non-null array of
changed this to "normal"  - perhaps there is a better name. I think we will do need the 00 code because in same cases you don't have an explicit payload length to decide to send this or not. Check it out in next version of PR.

2024-04-21 17:59 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* 0x2 := Group non existent. Sent by a publisher and indicates the group
Changed to be more or less what Luke suggest.

2024-04-21 18:41 UTC, fluffy commented on draft-ietf-moq-transport.md
> +         payload. Sent by the media producer and sent to indicate that
Tried to clarify this. Part of the issue was can a normal object ( status code 0 ) have a zero length payload. I do not see any reason not to allow this. It makes it clear it is not "missing" but it just has no data. I think Alan had a use case for this. Check out next version of PR and see if it seems clearer on all this.

2024-04-21 18:45 UTC, fluffy commented on draft-ietf-moq-transport.md
> +
I tried to make the cache or not very explicit in new version. I think it resolves this.

2024-04-22 18:41 UTC, kixelated commented
Sorry I left a PR review a little too fast between meetings and taking care of the newborn. I had a chance to think things through a bit more.

> I think there's a better way to signal drops though than to retransmit the same OBJECT but with a different status/payload after a RESET_STREAM.

I'm warming up to the status in OBJECT, however it needs to be a bitmask. An object can be both dropped, the end of a group, and the end of a track. It's a little annoying to have to process duplicate OBJECTs with different statuses but it's fine I guess.

An alternative would be a reliable SUBSCRIBE control stream that contains reliable messages GROUP_END, TRACK_END, OBJECT_DROPPED messages. There would be no need to retransmit anything on a RESET_STREAM but the overhead would be marginally higher. 

ex. GROUP_END would consist of the message type, the group_id VarInt, and a object_id VarInt only. The track would be inferred from the subscribe control stream.

2024-04-22 18:52 UTC, afrind commented
> An object can be both dropped, the end of a group, and the end of a track

I think Cullen's update addressed this by making "end of group" and "end of track" have *different object IDs* than the last actual object.  Should we further state that only objects with status 0 can be "dropped by a relay"?  All the other statuses may be needed by the subscriber, and all should be very small.

Would you be ok with moving this PR forward if we split out 0x5 and 0x6 for now?

2024-04-23 15:13 UTC, ianswett reviewed
LG, but some minor comments to clarify that all statuses besides 0x0 don't have a payload.

And I would prefer to remove 0x5 and 0x6 for now.

2024-04-23 15:13 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  Object Status (i),
I assumed we were doing that on a separate stream?

2024-04-23 15:13 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* 0x0 := Normal object. The payload is array of bytes and can by empty.
This is only a valid value for OBJECT_STREAM, correct?

2024-04-23 15:13 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* Object Status: As enumeration used for missing or dropped objects that
This it can also signal GROUP_END and TRACK_END.

2024-04-23 15:13 UTC, ianswett commented on draft-ietf-moq-transport.md
> +There is also a status field which help subscribers understand what
The status has a wider set of functionality than just drops and gaps.

Can you clarify that all status values except 0x0 do not have any payload?

2024-04-23 16:27 UTC, kixelated requested changes

2024-04-23 16:27 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  [Object Status (i)],
What happens if we get a stream FIN without status 0x3? Is that a fatal error or can we use it as an implicit signal?

2024-04-23 16:27 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  [Object Status (i)],
What happens if we get a stream FIN without status 0x4. Is that a fatal error or is it implicit?

2024-04-23 16:31 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  [Object Status (i)],
I'd like it to be implicit, or banned.

2024-04-24 16:14 UTC, fluffy commented
Note to cullen - remove the two codes. Clean up other comments. Ping Ian when done and ready to merge.

2024-04-25 11:15 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates Object was dropped at a relay. Sent by a relay
Removed in next version

2024-04-25 11:32 UTC, fluffy commented on draft-ietf-moq-transport.md
> +per object, the end of Group is redundant.
oops - changed as you sugested

2024-04-25 16:19 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  [Object Status (i)],
Actually can we remove this for now? Every status is redundant and confusing with this encoding.

0x1: Implies there can be gaps in group streams which I don't want to support. And if we did end up supporting it, intentional gaps can be detected via the sequence numbers.

0x2: Should be in the group stream header (or separate message). Using the first object to indicate the entire group is skipped is really confusing and error prone. Also I don't like intentional gaps in groups but that's a separate issue.

0x3: Conflicts with STREAM FIN. It can only create problems unless we allow multiple streams per group, but that's counterproductive.

0x4: Should be in the group header (or a separate message). Conflicts with SUBSCRIBE_END since it can indicate the end of the track too.

2024-04-25 16:23 UTC, kixelated reviewed
I removed my -1 so if others think it's fine, merge it.

2024-04-26 11:41 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* 0x0 := Normal object. The payload is array of bytes and can by empty.
I'm struggling how to phrase this.  I was thinking  of the obj formats could have an empty payload.

2024-04-26 11:43 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* 0x4 := Indicates end of Track and Group. GroupID is one greater than
Lets say group had three object 0 to 2. And 2 is dropped. I was thinking what is sent is 0, 1 , then message with status code that indicated 2 was dropped, then message with status code that indicates obj 3 would be end of group marker.

2024-04-26 11:45 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  Object Status (i),
I'm not following the problem here. There would be no change from what we have today in figuring out legth of message.

2024-04-26 11:47 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  [Object Status (i)],
I don't think this changes what a FIN means in any way and I would not want to use these group and end markers in all cases. For applications where they make sense ( like streaming video ) they can can be used. For applications where they make no sense ( like audio only ) the publisher would not bother.

2024-04-26 11:48 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  [Object Status (i)],
Sam thing, status 0x3 is optional, this PR does not change what a FIN does or does not mean.

2024-04-26 15:45 UTC, suhasHere commented
I did another read through and it looks good to me !! Thanks Cullen

2024-04-26 17:34 UTC, afrind commented
Individual Comment:

>  For applications where they make no sense ( like audio only ) the publisher would not bother.

This means a *relay* cannot assume the existence of these marker objects.  That's unfortunate, because I'd like the end-of-group marker to help my relay know when to close fanout streams.  I don't want to rely on QUIC FIN for this - a publisher may use a QUIC FIN to terminate a stream cleanly (delivering all written objects) as part of a graceful shutdown, without wanting to signal the end of group.  In this case, I explicitly *don't* want to close fanout streams, in case the publisher is reconnecting (make before break).

Would making end markers optional for DATAGRAM tracks sufficiently address the audio only use case?

2024-04-27 00:42 UTC, fluffy commented
> > For applications where they make no sense ( like audio only ) the publisher would not bother.
> 
> This means a _relay_ cannot assume the existence of these marker objects. That's unfortunate, because I'd like the end-of-group marker to help my relay know when to close fanout streams. I don't want to rely on QUIC FIN for this - a publisher may use a QUIC FIN to terminate a stream cleanly (delivering all written objects) as part of a graceful shutdown, without wanting to signal the end of group. In this case, I explicitly _don't_ want to close fanout streams, in case the publisher is reconnecting (make before break).
> 
> Would making end markers optional for DATAGRAM tracks sufficiently address the audio only use case?

I get your point and need to think about all of that a bit. Lets say the client did send them, would it be a problem if it just crashed without sending them. Would the relay also have a timer or some other way to clean up the state ? Or just wait for subscribe to end ? Just thinking through implications but you raise a good point.

2024-04-27 14:47 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* Object Status: As enumeration used to indicated missing or dropped
```suggestion
* Object Status: As enumeration used to indicated missing
```

2024-04-27 15:01 UTC, ianswett approved these changes

2024-04-27 19:24 UTC, ianswett commented on draft-ietf-moq-transport.md
> +         GroupID. This is sent right after the last object in the
Yes, I added a MUST about this below.

2024-04-27 21:33 UTC, afrind commented on draft-ietf-moq-transport.md
> +* Object Status: As enumeration used to indicated missing
indicate

2024-04-27 21:34 UTC, afrind commented on draft-ietf-moq-transport.md
> +  objects and as an marker of the end of group or track.
s/and as an marker/or mark/ ?

2024-04-27 21:34 UTC, afrind commented on draft-ietf-moq-transport.md
> +The Object Status lets subscribers understand what objects will not be received
s/lets subscribers understand/informs subscribers/

2024-04-27 21:35 UTC, afrind commented on draft-ietf-moq-transport.md
> +`Status` that can have following values:
remove 'that' ?

2024-04-27 21:37 UTC, afrind commented on draft-ietf-moq-transport.md
> +* 0x0 := Normal object. The payload is array of bytes and can be empty.
Given this is in the canonical object part, and payload has already been defined above, maybe it's more clear to define Status first, then in Object Payload state that this property is only present when Status is Normal Object.

2024-04-27 21:42 UTC, afrind commented on draft-ietf-moq-transport.md
> +         GroupID. This is sent right after the last object in the
> This is sent right after the last object

Can this be a MUST, at least for Forwarding Preference = Group?

2024-04-27 21:43 UTC, afrind reviewed
Individual Review

2024-04-28 15:29 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* Object Status: As enumeration used to indicated missing
```suggestion
* Object Status: As enumeration used to indicate missing
```

2024-04-28 15:37 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  objects and as an marker of the end of group or track.
```suggestion
  objects or mark the end of a group or track.
```

2024-04-28 15:38 UTC, ianswett commented on draft-ietf-moq-transport.md
> +The Object Status lets subscribers understand what objects will not be received
```suggestion
The Object Status informs subscribers what objects will not be received
```

2024-04-28 15:39 UTC, ianswett commented on draft-ietf-moq-transport.md
> +`Status` that can have following values:
```suggestion
`Status` can have following values:
```

2024-04-28 15:44 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* 0x0 := Normal object. The payload is array of bytes and can be empty.
SGTM

2024-04-28 15:50 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* 0x0 := Normal object. The payload is array of bytes and can be empty.
Ok, I created a separate section, I think this looks ok now.

2024-04-28 15:53 UTC, merged