SUBSCRIBE_UPDATE
moq-wg/moq-transport pull request #435
Opened 2024-04-18 01:38 UTC by ianswett

Replace #385 based on the simplified SUBSCRIBE.

Fixes #269
Closes #385

2024-04-21 22:22 UTC, fluffy approved these changes
What I like about this is we explicitly separate what can be setup in the initial subscription, and what can be changed about it later. I think that will make things easier to understand over the long run.

2024-04-21 22:30 UTC, kixelated approved these changes
Being able to increase the start group is a nice way for the subscriber to drop old content it doesn't care about. I like the simplicity.

2024-04-21 22:38 UTC, afrind commented on draft-ietf-moq-transport.md
> +start Object.  The end Object MUST NOT increase and when it decreases,
Do you mean "before the new start object" ?

2024-04-22 17:11 UTC, suhasHere requested changes
+1 on needing subscribe update. But not sure of the proposal on object/group Ids and what gets delivered

2024-04-22 17:11 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +* Subscribe ID: The subscription identifier that is unique within the session.
the subscribe Id must match an existing subscription or else its an error.

2024-04-22 17:11 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
I am bit confused on the requirements here. An update to an existing subscription updates the filter that the publisher looks at. A filter that is smaller than the original implies lesser objects than before.

2024-04-27 19:59 UTC, ianswett commented on draft-ietf-moq-transport.md
> +
I added text to clarify the intent, which is that one can only narrow a subscription, not widen it.

2024-04-29 17:02 UTC, afrind commented
Individual Comments:

Is there a response to a Subscribe Update?  For example, maybe the auth has changed and is no longer valid?

I think there is weirdness with respect to track and group forwarding preferences when you create a gap by moving start forward. I think we should require the publisher to close QUIC streams with objects that haven't been requested and open new ones.  eg:

-> Subscribe to a track with forward pref = track, start=0/0
<- Subscribe Ok
<- Open stream 1, sending objects starting from 0/0
-> Subscribe update, start=10/0
<- Close stream 1
<- Open stream 2, sending objects starting from 10/0

Alternately, should we only allow End to be modified by SUBSCRIBE_UPDATE?  This is should always succeed and doesn't have any hard edges.  To move start forward, or change parameters, end the current subscription and start a new one?

2024-04-29 17:40 UTC, ianswett commented on draft-ietf-moq-transport.md
> +there is no guarantee that a publisher will not have already sent Objects after
```suggestion
there is no guarantee that a publisher will not have already sent Objects before
```

2024-04-29 18:30 UTC, suhasHere approved these changes

2024-04-29 18:40 UTC, ianswett commented
I wasn't intending for there to be a response to SUBSCRIBE_UPDATE.  If auth fails, I think the right thing to do is terminate the subscription with an error.

Interesting point about forwarding preference.  Do we have to say anything about stream states/etc there?  This seems similar to the case when you have severe congestion and have to drop a bunch of Objects instead of delivering them.

I'd like to be able to modify start, because it is useful in live use cases, because it allows a client to tell the server 'stop sending content before this point'.

2024-04-29 19:07 UTC, afrind commented
Individual Comment:

> Interesting point about forwarding preference. Do we have to say anything about stream states/etc there? This seems similar to the case when you have severe congestion and have to drop a bunch of Objects instead of delivering them.

We're still spelling how this dropping works, but it seems like in those cases there will be OBJECT_DROPPED message or similar that explains the gap.

On the one hand, the publisher put a bunch of objects on a single stream for a reason,  so skipping over a bunch seems like it could break things.  On the other hand, it was the subscriber who asked for the gap, so it shouldn't be surprising.  I think we need some guidance about how to handle this, but I guess we can come back to it later as well.

2024-04-30 01:35 UTC, ianswett commented on draft-ietf-moq-transport.md
> +Unlike a new subscription, SUBSCRIBE_UPDATE does not cause an Object to be
```suggestion
Unlike a new subscription, SUBSCRIBE_UPDATE can not cause an Object to be
```

2024-04-30 01:36 UTC, merged