Exclusive SUBSCRIBE end range
moq-wg/moq-transport pull request #437
Opened 2024-04-19 17:30 UTC by kixelated

This removes the `N/latest` functionality which is super confusing. It's also just cleaner to use exclusive end ranges instead of the previously implied inclusive ranges.

Note that to receive a single group, you need to use:
```
    start_group=N  start_object=0
    end_group=N+1  end_object=0
```

Previously that was accomplished with:
```
    start_group=N  start_object=1
    end_group=N    end_object=0
```

2024-04-19 17:38 UTC, afrind commented
See related issue #436

2024-04-19 17:40 UTC, afrind commented on draft-ietf-moq-transport.md
> +* Start Object: The inclusive start Object ID. When Start Group is 0, this field is not present and defaults to 0.
Note: this changes the start group=0 from meaning latest/latest to meaning latest/0 and there is no way to express latest/latest after this change.

2024-04-19 18:18 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* Start Object: The inclusive start Object ID. When Start Group is 0, this field is not present and defaults to 0.
Well the meaning was `latest/undefined`. My intent was `latest/0` but I can see how it could be interpreted as `latest/latest`.

2024-04-20 00:33 UTC, afrind commented on draft-ietf-moq-transport.md
> +* End Group: The exclusive end Group ID, plus 1. A value of 0 means the subscription
The group is only exclusive when end object is 0.  I understand what you mean, but we should clarify the text. 

If I want to get up through g=7, o=5, I send end: g=7 (encoded 8) o=6.  If I want all of group 6 but none of group 7, I send start: g=6 (encoded 7), o=0, end: g=7 (encoded 8), o=0.

2024-04-20 00:40 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* End Group: The exclusive end Group ID, plus 1. A value of 0 means the subscription
Ah yeah, the tuple is exclusive.

2024-04-20 04:05 UTC, afrind commented on draft-ietf-moq-transport.md
> +  [ Start Object (i), ]
Suggestion to support both "latest/0" and "latest/latest": Start Object is always present, but when Start Group is 0, 0 means object 0, 1 means latest object and values >= 2 are illegal.

2024-04-21 22:47 UTC, fluffy requested changes
This PR is making things better and clarifying stuff so I am in favor of merging, just think there are a few things that could get fixed up before merging.

2024-04-21 22:47 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* Start Object: The inclusive start Object ID. When Start Group is 0, this field is not present and defaults to 0.
I think "inclusive" and "exclusive" are not as good as just using  ">="  and  "< ".  I'd have a slight preference for that.  I can certainly live with  "inclusive" and "exclusive" and no big deal.

2024-04-21 22:47 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* Start Group: The inclusive start Group ID, plus 1. A value of 0 means the latest Group ID.
The more I read this +1, the less I like it. I can easily live with using 0 as the special value, but as an alternative, what would you think of:

We add a boolean flag field call "latest(f)," and make start group optional and only included if latest is false. Similarly we add a field called "forever(f)," and make end group optional only included if forever was false. Then we could get rid of +1. Thoughts ? and to be clear, I can easily live with it like it is.

2024-04-21 22:47 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  [ Start Object (i), ]
The use cases for latest/latest are really weak - I think we could live without that for now.

2024-04-21 22:47 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* Start Object: The inclusive start Object ID. When Start Group is 0, this field is not present and defaults to 0.
We 100% need latest/0 so perhaps just some text to clear that up.

2024-04-22 18:28 UTC, suhasHere commented
Submitted https://github.com/moq-wg/moq-transport/pull/439 as another way to clarify some ambiguities.

2024-04-24 16:20 UTC, wilaw commented
This PR assumes the end_group N+1 exists. What about the case of an asset which only has groups from 1..10. If I want to subscribe to all of these, I have request 

 start_group=1  start_object=0
 end_group=11  end_object=0

This is semantically awkward to me, since it references an entity (group 11) which does not exist. It would be so much cleaner and more intuitive if the API allowed us to ask for what we want, via inclusive threshold. I would rename them to "first" and "last" to make their syntax clearer. So to subscribe to groups 1..10 I could do

first_group=1  start_object=0
last_group=10  end_object=0

I then receive receive exactly what I ask for.

2024-04-27 16:00 UTC, afrind commented
This spiritually merged into #439

2024-04-27 16:00 UTC, closed without merging