Add a priority field to subscriptions
moq-wg/moq-transport pull request #445
Opened 2024-05-02 01:51 UTC by ianswett

Fixes #403 

It seems like we need this, and I'm open to suggestions, but this feels quite straightforward.

2024-05-04 16:33 UTC, suhasHere requested changes

2024-05-04 16:33 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Priority (i),
Priority per subscritpion brings in few complications
- Subscriptions cannot be aggregated
- Upstream subscriptions between relays have to deal with ambiguities when conflicting priorities for the same track are requested.
- Original publisher's expectation cannot be mandated when it sets track/object priorities.

2024-05-26 19:57 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  Priority (i),
Why can't they be aggregated?  Clearly a relay will have to make a choice about what the upstream priority should be, but this at least gives it an ability to do that.

Priorities are within a track, why would one have priorities across tracks?  A subscriber may be subscribing to multiple different things at once, potentially from different namespaces, so having priorities apply between tracks is confusing.

2024-05-27 17:51 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Priority (i),
in general , a way for a subscriber to express priority does makes sense. I do have few thoughts \

On aggregation: if 2 subscribers for the same track ask different priorities to a relay, the relay has to do some sort of logic to determine which one to pick. The easiest way to resolve this is "the publisher priority wins in such a case" . Perhaps we should document that in the relay section ?? Also I think the priority field needs to be optional.

On priority and track relation: Subscription is per track and if a subscriber asks for video track and audio track, it would ask that with 2 different priorities and we should allow that. isn't that the case or am I missing something ?

2024-05-27 22:45 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Priority (i),
> I'm inclined not to say anything on aggregation.  CDNs and such deal with this today (HTTP priorities are similar to this) and I'm not sure being proscriptive helps.  This is very much intended as a property on a given subscription within a session, so I wouldn't expect it typically makes sense to go upstream, just like we don't act on HTTP priorities when coalescing upstream.
> 
> 
> 
> I'm fine with making it optional, but I have no idea what to make the default? This priority is purely relative, and there's no absolute meaning.

The default will be publisher set priority. 

+1 on not carrying over the priority upstream and thus applies to just the last mile. This allows for subscriptions aggregation. We should add a note to clarify this though.

2024-05-28 01:10 UTC, LPardue requested changes
This is, IMO, too ambiguous about what happens when the values are equal. One option would be to bandwidth share, another would be to tie break based on some other parameter like the session ID (I.e. in HTTP we prefer lower stream IDs because that indicates an earlier request, not sure that translates to MoQ).

I'm not a huge fan of the name `Priority` because that is so overloaded. It seems like this single value is precedence.

Do we really need 2^62 levels? All the feedback I heard in the HTTP priorities discussion said that too many options is confusing. Do we have any understanding of how many concurrent sessions a MoQ use case has? Imy crystal ball suggests we can probably drop this field to 16-bits and be totally fine.

2024-05-28 01:13 UTC, LPardue commented
I might suggest that we move scheduling guidance out of field definitions and into its own section. That will make future edits simpler, for example if we take on additional refinements once there's some experience.

2024-06-05 13:31 UTC, fluffy requested changes
I think we should talk about this at Seattle meeting. 

This needs to talk about how it interacts with other priorities. I need to talk about what happens upstream ( if anything ).  As it is written, I can't figure out if this works when the congested links is upstream of last relay.

2024-06-05 13:31 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  Priority (i),
To me, calling this something other than priority would make more sense if the goal was to combine this with other priorities.  If this was called "preference" and relays sent things with highest preference first and then if the preferences of two thing were equal, then looked at priority to decide which next or something like this.

2024-07-01 20:48 UTC, ianswett commented
Closing in favor of #470

2024-07-01 20:48 UTC, closed without merging