Add a Cache Duration (aka ttl) field to Objects
moq-wg/moq-transport pull request #446
Opened 2024-05-13 13:46 UTC by ianswett

Based on discussion last week and on slack, I believe this is where the WG is heading.

It is possible this could be a per-track or per-subscription value to save bytes on the wire, particularly for the Object per Stream or Object per Datagram modes.

Fixes #440

2024-05-13 14:24 UTC, wilaw commented on draft-ietf-moq-transport.md
> +has resided in the cache for longer than that time interval.
Does a value of 0 mean that the object should never be cached?

If so, how does a publisher indicate that they have no suggested cache duration to convey?

2024-05-13 15:15 UTC, ianswett commented on draft-ietf-moq-transport.md
> +has resided in the cache for longer than that time interval.
Good question.  Possibly 0 should indicate that there is no duration.  Which presumably means one can cache for however long it makes sense?

2024-05-13 15:47 UTC, wilaw commented on draft-ietf-moq-transport.md
> +has resided in the cache for longer than that time interval.
> Which presumably means one can cache for however long it makes sense?

There are two possible (and quite different) meanings of 0:
1. Do not cache the object at all (ie a cache duration of 0 which is consistent with the interpretation of all other non-zero values
2.  The publisher has no opinion, so cache for however long you want.

2024-05-13 15:52 UTC, ianswett commented on draft-ietf-moq-transport.md
> +has resided in the cache for longer than that time interval.
Thanks, and I agree.  In an ideal world, we'd make this optional and if it wasn't present, that would be case 2, but I don't see an easy way to allow for that.

2024-05-14 03:24 UTC, afrind reviewed
Individual review

2024-05-14 03:24 UTC, afrind commented on draft-ietf-moq-transport.md
> +has resided in the cache for longer than that time interval.
Encode as duration + 1, and 0 means "no opinion"?  It's not pretty but it gets the job done.

Why SHOULD NOT send vs MUST NOT send?

2024-05-14 07:45 UTC, alvestrand commented on draft-ietf-moq-transport.md
> +has resided in the cache for longer than that time interval.
https://www.rfc-editor.org/rfc/rfc9000#section-1.3 describes an optional field encoding. Why not use it?

2024-05-14 17:51 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Cache Duration (i),
This doesn't allow per object cache duration for stream per group /stream per track and excepts all the objects within a stream should have same expiry.

2024-05-14 17:57 UTC, suhasHere reviewed
This seems to be a good start and we should consider taking this forward. 
However,  I feel we need to have mechanisms to specify object duration applied to objects for multi-object transport stream mappings. 

May be something like (for stream per track)
```
STREAM_HEADER_TRACK Message {
  Subscribe ID (i)
  Track Alias (i),
  Object Send Order (i),
 Cache Duration (i)
}
{
  Group ID (i),
  Object ID (i),
  Object Payload Length (i),
  [Object Status (i)],
  [Cache Duration(i)],
  Object Payload (..),
}

The cache duration is considered iff payload_length > 0 && not available in STREAM_HEADER_TRACK message
```
or some better way to do so.

2024-05-14 17:57 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Cache Duration (i),
This doesn't allow per object cache duration for stream per group /stream per track and excepts all the objects within a stream should have same expiry.

2024-05-14 17:59 UTC, afrind commented on draft-ietf-moq-transport.md
> +has resided in the cache for longer than that time interval.
The RFC 9000 notation just states that field *is* present sometimes and not others, but doesn't include a mechanism for a receiver to determine whether the field is present or not.

2024-05-14 17:59 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Cache Duration (i),
@suhasHere : That is also how I read this.  Does your application require unique cache duration per object within a group-per-stream, and if so, can you explain the use case the drives it?

2024-05-15 03:20 UTC, VMatrix1900 commented
IIUC, this field is the TTL of per hop instead of end-to-end. The content origin can set the TTL to end-to-end [deadline](https://datatracker.ietf.org/doc/draft-ma-moq-relay-for-deadline/) and each hop decrease the value then pass it to the downstream relay. Is that correct?

2024-05-15 14:40 UTC, vasilvv commented
I'm not sure this PR solves either of the problems we're trying to solve with the cache TTL fields.

2024-05-15 17:02 UTC, fluffy approved these changes
I think this is good start and we should merge this. We need more things over time.  I am fine with 0 and 1 being special values for don't care , and don't cache.

2024-05-15 17:07 UTC, suhasHere submitted a review, later dismissed
LGTM

2024-05-22 06:00 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Cache Duration (i),
I feel object properties and stream mapping are being overloaded. Object property like duration is application scoped property that indicates how long a object is valid. Stream mapping OTOH is transport mechanism.

2024-05-22 15:30 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  Cache Duration (i),
That's absolutely the point. Introducing gaps in a QUIC stream is counterproductive.

2024-05-22 15:30 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  Cache Duration (i),
> This doesn't allow per object cache duration for stream per group /stream per track and excepts all the objects within a stream should have same expiry.

That's absolutely the point. The ability to introduce gaps in a QUIC stream is counterproductive, and the application is explicitly trying to use a QUIC stream to avoid these gaps.

2024-05-22 15:30 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  Cache Duration (i),
> I feel object property and stream mapping are being mixed

I agree, the object model and stream mapping are in direct conflict and it needs to be fixed. The entire point of the stream mapping is to inherit the properties of QUIC streams, but that's pointless if the object model vetoes it.

2024-05-22 15:48 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  Cache Duration (i),
I think the goal of the stream mapping is to efficiently provide the transport features the application needs.  In some cases, HoL blocking is a feature, and sometimes it's a bug/negative for example.

2024-05-22 17:01 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Cache Duration (i),
+1 to what @ianswett said

2024-05-23 03:39 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +does not cause a change in the 'Object Status'.
I am fine with this, but don't see if we need to advice on deducting the time spent each hop.

2024-05-23 20:01 UTC, ianswett commented on draft-ietf-moq-transport.md
> +has resided in the cache for longer than that time interval.
Changed to MUST NOT BTW

2024-05-23 20:03 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  Cache Duration (i),
Agreed.  I'd like to see if this is really necessary, since it adds more framing overhead and as I mentioned in the call, I think it might end up being better to use priorities to achieve what you're trying to achieve with TTL.

2024-05-23 20:05 UTC, ianswett commented on draft-ietf-moq-transport.md
> +does not cause a change in the 'Object Status'.
If we expect this to prevent an Object from being in cache for too long, I think we need to do the subtraction?

2024-05-29 16:59 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* Max Cache Duration: The maximum length of time in seconds a caching
I would prefer milli seconds to seconds.

2024-05-29 17:04 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* Max Cache Duration: The maximum length of time in seconds a caching
I changed it because HTTP MaxAge is in seconds, and In the Object per Stream or Object per Datagram cases, using seconds saves at least a byte.

But I can change it back to ms if we're fine with the extra byte+ of overhead.

2024-05-29 17:05 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +does not cause a change in the 'Object Status'.
agreed .. other than milliseconds vs seconds , this looks fine to me.

2024-05-29 17:11 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  Max Cache Duration (i),
I don't get how this will work with when combined with the removing the amount of time that has elapsed sitting in cache. Consider a stream per track mode where the timeout is set to 30 minutes from the use case Will had.  The first object I will call A is published at noon and a later object is polished at 15 minutes later at 12:15 and I will call this object B. 

Then a downstream relay subscribes 10 minutes after start to the track. It gets a stream header with a 20 minute time out since we are substracting the 10 min that track was sitting in ubstream realy. For object A, that is great, it will time out at 12:30. However, for object B, it seems it will time out 20 minutes after it was publshed, not 30 as request. So it will time out at 12:30 when it should be around will 12:40. 

Not sure I am explaining this well but hope you get idea.

2024-05-29 17:12 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  Max Cache Duration (i),
I am trying to say we need more clarity how the time is decrement for time in cache in the stream per track and stream per group modes. This problem only come up because the timeout is in the header not the object in those mode. Moving might be the easy fix.

2024-05-29 18:05 UTC, ianswett commented on draft-ietf-moq-transport.md
> +does not cause a change in the 'Object Status'.
I changed it back to ms.

2024-05-29 18:15 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  Max Cache Duration (i),
I think moving them to be per-Object may create some other weird circumstances, such as the first few Objects of a Group/Track expiring, but the ones that arrived later haven't, but they aren't useful without the start of the Group.

2024-05-29 22:48 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  Max Cache Duration (i),
I updates this PR with another paragraph, PTAL

2024-05-29 22:52 UTC, ianswett commented on draft-ietf-moq-transport.md
> +second Object.
```suggestion
second Object in the Group.
```

2024-06-04 11:19 UTC, vasilvv reviewed
It is still unclear to me which of many problems this specific field is trying to solve.

2024-06-04 11:19 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +second Object in the Group.
Does this imply that you can have the beginning of the group expire before the end of the group?

2024-06-04 14:44 UTC, fluffy requested changes
still want to talk about this some more - there has been many changes

2024-06-04 17:05 UTC, afrind commented
Individual Review:

I think this PR needs additional, probably normative, guidance about when a caching relay starts the expiration timer.  For example, if using stream-per-object and the object is large, does the timer start when placing the first or last byte of the object in cache.  The same is true of other forwarding modes.

2024-06-05 16:32 UTC, fluffy commented
Just for notes ... Mo raised key point on call that if we tail drop things in some priority mechanism, then we may never get the end of group marker. We probably need to adjust text to be very careful about how we detect we are never going to get any more data on this group or track

2024-06-05 16:37 UTC, fluffy commented
Victor had point that perhaps we should use the start of next group to start timer instead end of current group

2024-07-04 17:08 UTC, fluffy approved these changes

2024-07-25 17:59 UTC, ianswett commented
Closing this in favor of a newer PR, #469

2024-07-25 17:59 UTC, closed without merging