Add availability limits to MoQ subscriptions
moq-wg/moq-transport pull request #448
Opened 2024-05-20 14:52 UTC by vasilvv

Those are long-term limits on how long a relay can keep serving objects from cache, primarily meant to be used to enforce content-related policies, rather than be used as a technical measure for optimizing delivery.

2024-05-20 15:44 UTC, wilaw commented on draft-ietf-moq-transport.md
> +* AVAILABILITY_LIMIT_ABSOLUTE: an integer expressing an absolute time in the
This AVAILABILITY_LIMIT_ABSOLUTE is the same time for the whole subscription. What about the following use-cases:

1. A 24x7 live linear stream, in which the broadcaster wants users to have access to the last 24 hrs?
2. A sports game in which the allowed DVR window is 2 hrs. behind the live head?

In both these cases, the AVAILABILITY_LIMIT_ABSOLUTE varies depending on when the GROUP or OBJECT is published and is not a fixed property of the subscription. 

AVAILABILITY_LIMIT_RELATIVE can be a property of the subscription. I'd suggest leaving that in the PR and then moving the AVAILABILITY_LIMIT_ABSOLUTE to an Object (Group) property. It can be efficiently communicated via our Stream header if it is the same for all objects within a Group.

2024-05-21 21:20 UTC, fluffy requested changes
As a side note, I think do need an extension machoism such as the one you propose here and I hope you might make a PR with something like this for all the extension points.

2024-05-21 21:23 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* AVAILABILITY_LIMIT_ABSOLUTE: an integer expressing an absolute time in the
I can see how it make sense to have both a relative and absolute time limits in much the way you have desired here but for reasons I listed in the other PR. I do not think they can be an subscriber attributes. 

The specific use case Will brought forward required it to be be publisher based not subscriber.

2024-05-21 21:23 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* AVAILABILITY_LIMIT_RELATIVE: an integer expressing a number of seconds.  If
I think relative would need to be in mili seconds not seconds.

2024-05-21 21:30 UTC, afrind commented on draft-ietf-moq-transport.md
> +* AVAILABILITY_LIMIT_ABSOLUTE: an integer expressing an absolute time in the
@fluffy : the properties in the PR are transmitted by the publisher in the SUBSCRIBE OK, so I read them as being set by the publisher.

2024-05-21 21:47 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  since the object in question has been fully received.
small nit and not critical, but I think this would be better expresses as since the start or receiving the object.

2024-05-22 05:57 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +* AVAILABILITY_LIMIT_ABSOLUTE: an integer expressing an absolute time in the
I feel this property AVAILABILITY_LIMIT_RELATIVE and DeliveryTimeout are very similar and should be scoped per object in general and not subscription.

2024-05-22 09:08 UTC, VMatrix1900 commented on draft-ietf-moq-transport.md
>    Expires (i),
What is the difference between AVAILABILITY_LIMIT_ABSOLUTE and Expires? Can we use Expires to enforce the content policy? Or, use AUTHORIZATION INFO to carry a token with the lifetime?

2024-05-22 15:17 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* AVAILABILITY_LIMIT_ABSOLUTE: an integer expressing an absolute time in the
Yeah, conceptually these should be part of TRACK_INFO

2024-05-22 15:17 UTC, kixelated commented on draft-ietf-moq-transport.md
> +* AVAILABILITY_LIMIT_ABSOLUTE: an integer expressing an absolute time in the
I don't think there's a good use-case for absolute end times in a live streaming protocol. If you already know the total length of the broadcast ahead of time, you can set a relative limit too.

2024-06-12 15:07 UTC, fluffy commented
This is deeply in the case of what gets sent next which we said we would discuss at the interim. 

The problem in evaluating this is the questions of if this is the only mechanism but something added in addition to other approaches that solve the other use case. 

This needs more information about how relays handle it, how is it cached etc. We can discuss on call

2024-06-12 15:42 UTC, wilaw commented
I have been thinking about this problem and have changed my ind a bit since my original comment. I think we should add only cache duration limits to objects|groups|tracks. Once this cache limit has expired, the relay MUST go upstream to retrieve a fresh copy of the object. If the object is no longer available, then the origin will use our [Object Status](https://moq-wg.github.io/moq-transport/draft-ietf-moq-transport.html#name-object-status) flag to indicate that the object is no longer available. Relays may cache this response, just like we cache origin 404s today. This not-available response may itself carry a suggested cache duration.

2024-06-12 15:51 UTC, afrind commented
Individual Comment:

> This is deeply in the case of what gets sent next which we said we would discuss at the interim.

The next interim is about priorities, and I view this as related but orthogonal.

In my view, priorities help you decide what to send next when you have more than one thing to send.  Anything related to cache duration, availability or delivery timeouts can only change how many choices you have.

2024-07-25 18:00 UTC, ianswett commented
Closing this in favor of #469

2024-07-25 18:00 UTC, closed without merging