Max Cache Duration per Subscription
moq-wg/moq-transport pull request #450
Opened 2024-05-22 17:39 UTC by ianswett

A variant of #446 that is on a Subscription granularity, instead of Object duration.

Fixes #440

2024-05-23 03:41 UTC, suhasHere commented
Per my read of the room, i would prefer #446  as it is gives better flexibility for the application than enforcing it per subscription ( as it applies the same value to all the objects) . Also not sure if there are cases where this can change between the subscriptions  either

2024-05-23 14:28 UTC, VMatrix1900 commented
> Per my read of the room, i would prefer #446 as it is gives better flexibility for the application than enforcing it per subscription ( as it applies the same value to all the objects) . Also not sure if there are cases where this can change between the subscriptions either

+1, Cache Duration per object is more flexible.

2024-06-05 13:12 UTC, fluffy requested changes
I don't understand how the relay would know the answer to this at the time the subscribe happened, and I don't understand what use case the applications would need to get this from the relay instead of some other way like the manifest.

2024-07-04 16:59 UTC, fluffy requested changes
I think this was written before our current understanding of caching object not subscriptions so I have proposed a few updates but if it is meant to still be about refreshing subscriptions, then ignore all my comments.

2024-07-04 16:59 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  Max Cache Duration (i),
I think this might be slightly better as an optional parameter but clearly not a big deal either way

2024-07-04 16:59 UTC, fluffy commented on draft-ietf-moq-transport.md
> +relay MAY cache the subscription for.  A value of 0 indicates there is no limit.
It is the objects that are cached not the subscription so I think this needs to say "MAY cache the object for"

2024-07-04 16:59 UTC, fluffy commented on draft-ietf-moq-transport.md
> +it's older than Max Cache Duration. When a relay responds with SUBSCRIBE_OK,
Need to be clear the time starts at when the relay started to receive the object.

2024-07-04 16:59 UTC, fluffy commented on draft-ietf-moq-transport.md
> +subtracted when sending the Max Cache Duration.
This sentence does not make sense if we are caching objects not subscriptions. Would just remove it.

2024-07-25 18:00 UTC, ianswett commented
Closing this in favor of #469

2024-07-25 18:00 UTC, closed without merging