Delivery Order (aka Fetch lives)
moq-wg/moq-transport pull request #452
Opened 2024-05-27 18:42 UTC by ianswett

Takes an opinionated approach to adding 'Fetch' style functionality within the existing mechanisms.

Can be improved once various TTL/etc PRs land.  For example, we can add a 3rd mode where In Order is preferred within a client specified Delivery Timeout. (#449).

Pulls in concepts from #428 

Fixes #269
Fixes #326
Fixes #350

Closes #421

2024-05-27 20:51 UTC, ianswett commented on draft-ietf-moq-transport.md
> +specified a 'Delivery Order' of 'Strict In Order'. See ({{delivery-timeout}}) above.
```suggestion
requested a 'Delivery Order' of 'Strict In Order'. See ({{delivery-timeout}}) above.
```

2024-05-28 16:43 UTC, afrind reviewed
Individual Review

2024-05-28 16:43 UTC, afrind commented on draft-ietf-moq-transport.md
> +and start sending on a new one, with the same Subscribe ID.  Publishers MUST NOT
The MAY + MUST NOT is somewhat confusing. I think you are trying to say the publisher MAY continue to send objects that are no longer in the subscription, or reset the stream and open a new one in order to skip them?

2024-05-28 16:43 UTC, afrind commented on draft-ietf-moq-transport.md
> +send Objects with the 'End of Group' status to indicate the end of the Group.
Why do you say there is no explicit group id?  Don't the objects in Stream-per-track contain the group ID?

2024-05-28 16:43 UTC, afrind commented on draft-ietf-moq-transport.md
> +({{delivery-timeout}}) SHOULD be delivered in order.  Objects can be delivered
Can you clarify the expected behavior when a relay has a gap in their cache?  eg: The relay has object 1, 2 and 4.  

My read is that the relay MUST go upstream at least once to fill this gap, or get a tombstone for it.

2024-05-28 16:43 UTC, afrind commented on draft-ietf-moq-transport.md
> +'Latest' subscription would be delivering the same Objects, because Objects
What about subscribes behind the live head?  Wouldn't the two modes deliver the resources in opposite orders?

2024-06-04 11:15 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +and start sending on a new one, with the same Subscribe ID.  Publishers MUST NOT
Wonder why does this not apply for stream per group or stream per object cases.

2024-06-04 11:24 UTC, suhasHere requested changes
Thanks for the PR. I feel this PR is hitting some of the cases we need. 
I think this PR does need some more work to clarify few options - basically the interactions between priority across the delivery order options, what to do if there are gaps and cache duration. Relay upstreaming a subscription and what to pick or is it scoped to just last mile.

May be this is all some text clarification. But as-is I am not clear it addresses the issue completely.

2024-06-04 11:24 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +Latest In Order (0x2): Objects that have not exceeded the 'Delivery Timeout'
by "latest" do we mean, new groups will be prioritized before prior groups?

2024-06-04 11:24 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +Latest (0x3): Objects from the most recent Group SHOULD be delivered first,
Latest here is more clear compared to the previous option.

2024-06-04 17:11 UTC, afrind commented on draft-ietf-moq-transport.md
> +and start sending on a new one, with the same Subscribe ID.  Publishers MUST NOT
@suhasHere my read of this mode is that it overrides the publisher preference.  If subscriber asks for in-order, then the track is delivered in a single stream regardless.

2024-06-05 06:35 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +and start sending on a new one, with the same Subscribe ID.  Publishers MUST NOT
ah! makes sense .. I missed that.

2024-06-05 06:37 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +({{delivery-timeout}}) SHOULD be delivered in order.  Objects can be delivered
+1 to @afrind  . we need some text to explain when to go upstream vs when to deliver what is there ? May be its already there and I am not seeing it ( so apologies if that's the case)

2024-06-05 13:04 UTC, fluffy requested changes
I think we should talk about this at the Seattle interim starting with use cases we are trying to solve.

It is really hard to review a proposal like this without understanding if / how this propagates upstream.

2024-06-05 15:55 UTC, englishm commented on draft-ietf-moq-transport.md
> +'Latest' subscription would be delivering the same Objects, because Objects
To me, this is the key question, not just in this context, but re: caching expectations as a whole. 

What behavior do we expect when a relay is serving active subscribers at the live edge, but a new subscribe comes in so far behind the live edge that all of the delivery timeouts have expired and none of the objects are in cache any longer? Then, what about the case where _some_ objects haven't yet expired, but others have? Should that behavior be any different?

2024-06-17 17:13 UTC, wilaw commented on draft-ietf-moq-transport.md
> +Strict In Order (0x1): Delivers Objects in order of ascending Group Id and then
How can a relay implement this requirement that it deliver Groups in ascending order? Our group IDs are non-contiguous. As a consequence, if a relay receives group #10 and then group #12, should it wait for Group #11? It can never tell if 11 exists or not.

2024-07-04 17:23 UTC, fluffy requested changes
I think we need to step back from this PR and talk about use cases and requirements with some face to face time. Right now I am strongly against merging this for a few reasons. 

1. This eliminates the mode mode that is actually used the most in existing conferencing systems and the mode I think we need here

2. All the data I have see indicates that latest is not needed and performs worse that other approaches 

3. Strict In Order seems like it would be extremely memory intensive to try and implement and I do not see the need for it. We have to buffer somewhere, clear the receiving clients, not the high scale relays, are the place to do that.  This seems like it would introduce all kinds of DOS potential.  System that want things to be in order inside a group will use stream per group and get this but the relays do not need to enforce it.

2024-07-15 22:01 UTC, ianswett commented
Most of these changes are in other PRs, so closing this.

2024-07-15 22:01 UTC, closed without merging