Add Priority and Delivery Order to SUBSCRIBE, clarify Publisher Priority
moq-wg/moq-transport pull request #470
Opened 2024-06-22 16:35 UTC by ianswett

Adds a SUBSCRIBER_PRIORITY param that can be specified in SUBSCRIBE or SUBSCRIBE_UPDATE to indicate subscriber priority.  Adds Delivery Order to SUBSCRIBE to allow indicating Ascending or Descending.  Cleans up the existing priorities section and how Original Subscriber driven priorities are used.

Fixes #403

Closes #445

2024-06-22 19:56 UTC, ianswett commented on draft-ietf-moq-transport.md
> +More details on priorities are documented in {{}}
```suggestion
More details on priorities are documented in {{priorities}}
```

2024-06-22 20:03 UTC, ianswett commented on draft-ietf-moq-transport.md
> +Relays SHOULD NOT directly use SUBSCRIBER_PRIORITY or Delivery Order
```suggestion
Relays SHOULD NOT directly use SUBSCRIBER_PRIORITY or Delivery Order
```

2024-06-22 20:03 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* {{priority}} covers mechanisms for prioritizing subscriptions.
```suggestion
* {{priorities}} covers mechanisms for prioritizing subscriptions.
```

2024-06-22 20:25 UTC, ianswett commented on draft-ietf-moq-transport.md
> +In addition, the SUBSCRIBE specifies a Delivery Order of either
```suggestion
In addition, SUBSCRIBE specifies a Delivery Order of either
```

2024-06-22 23:46 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +indicates a higher priority, with 0 being the highest priority.
Should this also specify lowest priority and default?

2024-06-22 23:46 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +The publisher SHOULD respect the subscriber and original publisher's
Maybe call out relays specifically? This does not make sense for original publishers.

2024-06-22 23:46 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +content or policy.
How about "SHOULD specify blank priority by default, MAY prioritize based on popularity/etc"?

2024-06-22 23:46 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +  Delivery Order (8),
Would it make more sense to make those parameters? Since both of those have a reasonable default value.

2024-06-22 23:46 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +* Priority: An 8 bit integer indicating the publisher's priority for the Object
This field should probably be called "Publisher Priority".

2024-06-23 01:17 UTC, ianswett reviewed
In this PR, there isn't currently a default.  I realize there could be, but unless there's different behavior for it, I'd prefer to make it required because the behavior is clear.

2024-06-23 01:17 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  Delivery Order (8),
They do, but making people explicitly specify them is also ok.

2024-06-23 01:17 UTC, ianswett commented on draft-ietf-moq-transport.md
> +indicates a higher priority, with 0 being the highest priority.
In the current PR, there is no default, but I can add the lowest priority.

2024-06-23 01:17 UTC, ianswett commented on draft-ietf-moq-transport.md
> +The publisher SHOULD respect the subscriber and original publisher's
I can change it, though if one was using MoQ in a P2P application, wouldn't the subscriber's priority matter and the publlsher would be the original publisher?

2024-06-23 01:17 UTC, ianswett commented on draft-ietf-moq-transport.md
> +content or policy.
In this PR, there isn't any default, but I also don't think blank is inherently right.

2024-06-23 01:36 UTC, ianswett commented on draft-ietf-moq-transport.md
> +a number of factors specific to it, such as the populatity of the
```suggestion
a number of factors specific to it, such as the popularity of the
```

2024-06-23 04:23 UTC, suhasHere reviewed
This is coming along pretty well. thanks for the PR. I plan to give proper read next week, but overall shape of this is pretty good.

2024-06-23 04:42 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
I think we should make this optional or make a special value for "no preference, follow publisher prioirty"

2024-06-23 04:43 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
I think we need to make it optional or have a default of no-preference to follow original priority ?

2024-06-23 04:44 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +Values larger than 0x1 are a protocol error.
Ascending or Descending order of the group.

2024-06-23 07:38 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
My understanding of the mechanism at which we arrived at the interim is that if the subscriber does not care, it can set all priorities to the same value (e.g. `0x80`), and in that case, the publisher priorities take action.  The advantage of this approach is that if, for some reason, the subscriber decides later that it wants one track higher, it can set it to something like `0x70`, without having to reason about what priorities publisher assigned to its tracks.  It's also really easy to implement (`Final Priority = Subscriber Priority * 256 + Publisher Priority`).

2024-06-24 21:08 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
I am fine with it,  but I am not sure how to communicate not to set value of 0x1 implying the most important after the control stream for all the tracks, whereas the subscriber's intent was " i don't care, please follow publisher's priority" .
One way to make it is encode this field as optional and when missing follow publisher's priority for the track.

2024-06-24 21:12 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
Individual Comment:

> most important after the control stream for all the tracks

Should we just add explicit text that control stream always has priority over non-control? 

In that case, any value indicates "don't care, default to publisher" so long as the client sends the *same* value for all subscribes.

2024-06-24 21:41 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* Priority: An 8 bit integer indicating the publisher's priority for the Object
Done.

2024-06-24 21:44 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
Sure, I can add text about the control stream.

2024-06-24 21:45 UTC, ianswett commented on draft-ietf-moq-transport.md
> +Ascending (0x0) or Descending (0x1) order. See {{priorities}}.
```suggestion
Ascending (0x0) or Descending (0x1) order by group. See {{priorities}}.
```

2024-06-24 21:46 UTC, ianswett commented on draft-ietf-moq-transport.md
> +Values larger than 0x1 are a protocol error.
Good point, done.

2024-06-25 00:20 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
yes .. control stream should go with the most important priority and clarifying that will be good.

2024-06-25 02:06 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
I added a normative statement, PTAL

2024-06-25 19:19 UTC, suhasHere requested changes
Few nits and clarification. Overall looking good. Thanks for the PR

2024-06-25 19:19 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +content or policy.
I wonder if we should add the note  on publisher preference here too

2024-06-25 19:19 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
It would be good to say, if all the subscriber priorities are equal , publisher priorirty is followed for the objects correspnding to the subscribed tracks ?

2024-06-25 21:04 UTC, afrind commented on draft-ietf-moq-transport.md
> +content or policy.
@suhasHere : what's your suggestion?  Something like:

`In the absence of other specific reasons, relays SHOULD give all upstream subscriptions equal priority`

2024-06-25 21:04 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
Line 553-555 is *close* to what your are asking but could be clarified.

Current:

> The Subscriber Priority is considered first when selecting
a subscription to send data on within a given session. The original
publisher priority is considered next...

Maybe:

> The Subscriber Priority is considered first when selecting
a subscription to send data on within a given session. When two or more subscriptions have equal Subscriber Priority, the original
publisher priority is considered next...

2024-06-25 21:41 UTC, kixelated commented on draft-ietf-moq-transport.md
> +a subscription to send data on within a given session. The original
```suggestion
a subscription to send data on within a given session. When two subscriptions have the same priority, the original
```

2024-06-25 21:41 UTC, kixelated commented on draft-ietf-moq-transport.md
> +so subscriptions are prioritized based on the highest priority data
I think it's less confusing if you say publisher priority is per stream, instead of per track.

2024-06-25 21:41 UTC, kixelated commented on draft-ietf-moq-transport.md
> +The subscriber's priority can be changed via a SUBSCRIBE_UPDATE message.
Is this retroactive?

2024-06-25 21:41 UTC, kixelated commented on draft-ietf-moq-transport.md
> +higher Object Id, regardless of the specified Delivery Order.
A good reason to call it `Group Order` instead of `Delivery Order`; it doesn't apply to object ordering.

2024-06-25 21:41 UTC, kixelated commented on draft-ietf-moq-transport.md
> +considered first, so there is no incentive for the original publisher
A subscriber will often want to use the default publisher priority, so this isn't always true.

2024-06-25 21:41 UTC, kixelated commented on draft-ietf-moq-transport.md
> +within a single connection or on multiple connections can be used.
I don't think this will work in practice. There's too many use-cases where publishers are not coordinated because they're using different software or versions. 

ex. I want to show multiple Twitch streams on the same page. There's just no way that I can have OBS and ffmpeg agree to publish with the same priority scheme. It doesn't have to be malicious; one of the publishers is undoubtedly going to monopolize the connection.

Dialing a new connection is expensive and removes the ability to use subscriber priorities. I would totally agree with using multiple QUIC sessions if it had such a layer, but the alternative is WebTransport pooling...

And yes, you could use subscriber priorities only to avoid this issue, but that's a big limitation that could be easily solved by sandboxing namespaces. Relays can't use the subscriber's priority anyway and will have to sandbox namespaces if using MoQ over the backbone.

2024-06-25 21:41 UTC, kixelated commented on draft-ietf-moq-transport.md
> +Relays are not required to cache Objects, but relays need to have
A proxy is a relay too.

2024-06-25 21:41 UTC, kixelated commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
What about changing the group order too? It would be useful for toggling between reliable and unreliable playback.

2024-06-25 21:41 UTC, kixelated commented on draft-ietf-moq-transport.md
> +highest Group Id SHOULD be delivered first when multiple Groups are
This is only true when groups have the same priority, since we're allowing the publisher priority to change per stream.

2024-06-25 21:41 UTC, kixelated commented on draft-ietf-moq-transport.md
> +Relays SHOULD NOT directly use Subscriber Priority or Delivery Order
As briefly discussed at the interim, we also need the `Publisher Group Order` in SUBSCRIBE_OK and TRACK_STATUS. Relays should use that instead of the `Subscriber's Group Order`.

2024-06-26 16:24 UTC, janaiyengar reviewed
A few suggestions

2024-06-26 16:24 UTC, janaiyengar commented on draft-ietf-moq-transport.md
> +Values larger than 0x1 are a protocol error.
```suggestion
* Group Send Order: Requests that objects be picked from Groups in the
subscription in Ascending (0x0) or Descending (0x1) order. See {{priorities}}.
Values larger than 0x1 are a protocol error.
```

2024-06-26 22:05 UTC, ianswett reviewed
I made some updates, though I haven't clarified the text about priority changing between streams on a subscription.  PTAL

2024-06-26 22:41 UTC, afrind reviewed
Individual Review: 

You're still planning the publisher original group order bit in Subscribe OK too?

2024-06-26 22:41 UTC, afrind commented on draft-ietf-moq-transport.md
> +in every stream header.  As such, the subscriber's priority is a property
stream or datagram header

2024-06-26 22:41 UTC, afrind commented on draft-ietf-moq-transport.md
> +a subscription to send data on within a given session. The original
> When two or more tracks have equal subscriber priority, the original publisher priority is considered next

2024-06-26 22:41 UTC, afrind commented on draft-ietf-moq-transport.md
> +subscription are equal, send order is implementation-dependent, but the
It's not that `sub-pri == orig-pub-pri`, it's when `sub1.pri == sub2.pri` and `pub1.pri == pub2.pri`

> When the subscriber and original publisher priorities for two or more tracks are both equal

2024-06-26 22:41 UTC, afrind commented on draft-ietf-moq-transport.md
> +so subscriptions are prioritized based on the highest priority data
You will need to update this bit, since we agreed it's latest, not highest.

2024-06-26 22:41 UTC, afrind commented on draft-ietf-moq-transport.md
> +higher Object Id, regardless of the specified Group Order.
I think we should revisit this for stream-per-object and datagram.  Forcing these to be in object ID order seems like a restriction of functionality that is not strictly required.

2024-06-26 22:41 UTC, afrind commented on draft-ietf-moq-transport.md
> +Subscriber Priority for upstream subscriptions is based on
s/Subscriber Priority/priority fields/ ?

2024-06-26 22:41 UTC, afrind commented on draft-ietf-moq-transport.md
> +within a single connection or on multiple connections can be used.
I'd rather say that a relay shouldn't compare publisher priorities from uncoordinated publishers, but comparing them from coordinate publishers is fine.  Within a namespace, we can assert all tracks have coordinated priority, but between two namespaces, it would presently have to be implementation dependent.  That said, it shouldn't be hard to fix - break off part of namespace into another tuple field (application or something).

2024-06-26 22:41 UTC, afrind commented on draft-ietf-moq-transport.md
> +## Priority Algorithm
This section left intentionally blank?

2024-06-26 22:41 UTC, afrind commented on draft-ietf-moq-transport.md
> +Relays are not required to cache Objects, but relays need to have
Why can't a relay be a 1:1 relay?  I'd just chop the sentence at

> Relays are not required to cache Objects

The recently merged terminology says 

> Relay: An entitly that is both a Publisher and a Subscriber, but not the Original Publisher or End Subscriber.

2024-06-26 22:41 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
+1 add Group Order to Subscribe Update

2024-06-27 01:52 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
I worry that could create a number of edge cases.  A large benefit of SUBSCRIBE_UPDATE vs UNSUBSCRIBE/SUBSCRIBE is it avoids missing Objects or double-sending Objects.

But I'm not writing the code, so if you think it's useful and won't add unnecessary complexity, I'll add it.

2024-06-27 23:35 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +higher Object Id, regardless of the specified Group Order.
s/the same priority level/ the same object priority level

2024-06-28 00:18 UTC, afrind reviewed
Individual Comment

2024-06-28 00:18 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
Omitting this from subscribe update in favor of unsub/sub is ok, but you might want to add a note that it's intentional.

2024-06-28 05:18 UTC, englishm commented on draft-ietf-moq-transport.md
> +namespace.  Additionally, it is anticipated that when multiple namespaces
We may have a problem here. If we expect aggregating relays to not forward subscriber priority preferences, then, in fact, all middle hops are likely to fall to publisher priority and may incentivize priority inflation. On the other hand, relays are going to do what they're going to do, and, it's possible that publisher priorities may be ignored for middle hops in practice.

2024-06-28 05:25 UTC, englishm commented on draft-ietf-moq-transport.md
> +Relays are not required to cache Objects, but relays need to have
This gets a bit off topic, but I think the more important property of a relay is that it republishes tracks from an upstream publisher without modification. I think there may be another entity we could define which could consume one or more tracks from upstream publishers and act as the original publisher for some new tracks (e.g. in the case of "manifest manipulation" use cases at the edge), but I think that's something we should discuss separately.

2024-06-28 05:31 UTC, englishm commented on draft-ietf-moq-transport.md
> +Relays are not required to cache Objects, but relays need to have
As for this bit of text, I'm fine with it either way. To me, it makes explicit that relays may optionally be relatively stateless fan out nodes without any significant local caches, so long as they still allow downstream subscribers to subscribe to tracks from an upstream publisher.

2024-06-28 09:17 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +namespace.  Additionally, it is anticipated that when multiple namespaces
We don't want to end up in the case where the susbcriber gets different experience on each new subscriber joining with different priority  than what has sent upstream. I feel keeping subscriber priorities not go beyond is a good design principle

2024-06-28 14:49 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +* {{priorities}} covers mechanisms for prioritizing subscriptions.
s/prioritizing subscriptions/prioritizing subscriptions and publications.

2024-06-28 15:11 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +so subscriptions are prioritized based on the highest priority data
I feel this is right as it is worded ..

2024-06-28 15:41 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +## Priority Algorithm
+1 on filling this with the psuedo-code ..

2024-06-28 15:47 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +within a single connection or on multiple connections can be used.
I agree with Ian. it is tough to be prescriptive and the proposed text pretty much is well defined

2024-06-28 15:50 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
+1 to @ianswett

2024-06-28 15:51 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Group Order (8),
I don't think we need this in Subscribe_Update.

2024-06-28 15:54 UTC, fluffy approved these changes
Ian, I think this does an great job of covering what we agreed to the the interim. Thank you for the hard work on it. Few comments on things that I think could be a bit clearer and one small thing that seemed under specified.

2024-06-28 15:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +subscription are equal, send order is implementation-dependent, but the
given we use "send order" to talk about Ascending / Descending, I got confused when I read this. I think it could be less confusing to replace "send order" with "track selected to send next object" or something like that.

2024-06-28 15:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +so subscriptions are prioritized based on the highest priority data
We agreed on highest at this point, the latest is for other part. So I think this is correct as written here. Just to reason about this this, think about a track being send stream per object where publisher priorities changed. I don't think publisher priority is per stream - to start with it is for datagrams too.

2024-06-28 15:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +higher Object Id, regardless of the specified Group Order.
This seems correct as written and covers the case where the publisher priority is the same but we need to also cover the case where where publisher priorities are not the same in which  case publisher priority determines which is sent first. This may just be implied here but better to say.

2024-06-28 15:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +in every stream header.  As such, the subscriber's priority is a property
Agree with Alan

2024-06-28 15:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +The subscriber's priority can be changed via a SUBSCRIBE_UPDATE message.
I imagine lots of implementations would  not apply the new priority to data that had already been send or queued to the outgoing QUIC stream and certainly not to UDP datagrams already sent to the OS kernel.  So I think this is a quality of implementation and implementation choice.

2024-06-28 15:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +available to send.
This seems slightly under specified. If a last mile relay received two different values in both SUBSCRIBE and SUBSCRIBE_OK, we need to say which one takes priority.  We agreed on the end subscriber would take priority so this should have a bit more text to say value in SUBSCRIBE overrides in value in SUBSCRIBE_OK.

2024-06-28 15:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +Subscriber Priority for upstream subscriptions is based on
I like original text better because priority fields seems a bit undefined to me.

2024-06-28 15:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +namespace.  Additionally, it is anticipated that when multiple namespaces
I get what you are saying here but relays have to deal with a reasonable solution to this just to even be able to run lots of different applications on the same relay network even when application never have more than one namespace. I think there are two keys parts of this 1) we are not trying to specify how a relay network moves data around inside the relays and 2) relays will do what relays do. 

So thought relays could have if they don't think about this problem, I don't think we can say much more that this.

2024-06-28 15:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +within a single connection or on multiple connections can be used.
Alan, I don't think that would help, that just moves the same problem to the next layer and it would be turtles all the way down. The basic issue is when a content delivery network delivers content for lots of different applications/customers, it needs to decide how it will be "fair" between the application/customers and that is way more complicated that just use whatever the priority header asked for.

2024-06-28 15:54 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
Luke, I thought you were complaining about too many options :-)  I don't see the use case with this but at first glance does not seem like it would complicated the implementation too much so I am fine with it getting added.

2024-06-28 17:08 UTC, afrind reviewed
Individual Comments: 

Buried in here is a proposal for a different algorithm to resolve the priority of a track when it has multiple different priorities in flight.

2024-07-01 17:39 UTC, ianswett commented on draft-ietf-moq-transport.md
> +in every stream header.  As such, the subscriber's priority is a property
Good point, done

2024-07-01 17:43 UTC, ianswett commented on draft-ietf-moq-transport.md
> +## Priority Algorithm
Removed for now

2024-07-01 17:48 UTC, ianswett commented on draft-ietf-moq-transport.md
> +Relays are not required to cache Objects, but relays need to have
Based on the definition, I'll shorten this sentence and clarify some other text.

2024-07-01 19:21 UTC, ianswett reviewed
I tried to address most comments, PTAL

2024-07-01 19:21 UTC, ianswett commented on draft-ietf-moq-transport.md
> +higher Object Id, regardless of the specified Group Order.
True, I added a bit more text to clarify what happens when priority varies within a group.

2024-07-01 19:22 UTC, ianswett commented on draft-ietf-moq-transport.md
> +available to send.
Good point, I rewrote this paragraph to better match the current framing.

2024-07-01 19:33 UTC, ianswett commented on draft-ietf-moq-transport.md
> +content or policy.
I expanded the sentence a bit more to note that a relay can use a single Subscriber Priority value for all upstream subscriptions.

2024-07-01 19:44 UTC, ianswett commented on draft-ietf-moq-transport.md
> +considered first, so there is no incentive for the original publisher
Fair point, I changed this to text that points out the subscriber priority provides a mechanism to override.

2024-07-02 03:57 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +expectation is that all subscriptions will be able to send some data.
s/  send order is / the track whose object is being selected is /

2024-07-02 04:03 UTC, suhasHere approved these changes
@ianswett  the new changes look great. I have one change for removing the Group Order from the Subscribe Update message and define an error type when someone changes it in the update message.

2024-07-02 04:03 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +used. Values larger than 0x2 are a protocol error.
Line 580 indicates that group order cannot be changed via Subscribe update and I agree with that. We need to remove Group Order from the Update message though

2024-07-02 09:45 UTC, vasilvv approved these changes

2024-07-02 09:45 UTC, vasilvv commented on draft-ietf-moq-transport.md
> +Within the same Group, and the same priority level,
I'm confused, does this imply that a single group can have multiple priorities within it?

2024-07-02 13:59 UTC, ianswett commented on draft-ietf-moq-transport.md
> +used. Values larger than 0x2 are a protocol error.
Thanks for catching that, removed.

2024-07-02 13:59 UTC, ianswett commented on draft-ietf-moq-transport.md
> +Within the same Group, and the same priority level,
With Stream-per-Object, each Object can have a different priority in the current wire format.

2024-07-02 15:38 UTC, ianswett commented on draft-ietf-moq-transport.md
> +expectation is that all subscriptions will be able to send some data.
Good point, this text was a bit unclear.  I rewrote it to hopefully be more clear.

2024-07-02 17:42 UTC, afrind reviewed
Individual Comments:

2024-07-02 17:42 UTC, afrind commented on draft-ietf-moq-transport.md
> +within a single connection or on multiple connections can be used.
I am ok with merging the new language.  Long term, I don't plan to compare uncoordinated publisher priorities in my generic relay, and may make a proposal for how to avoid doing so.

2024-07-02 17:42 UTC, afrind commented on draft-ietf-moq-transport.md
> +  Subscriber Priority (8),
The new text looks good.

2024-07-03 19:34 UTC, merged