Peeps First Attempt
moq-wg/moq-transport pull request #494
Opened 2024-07-26 23:09 UTC by martinduke

I have foregone any premature optimization of the encodings here.

Asking @janaiyengar to take a first look.

2024-07-30 10:15 UTC, vasilvv commented
How does one close a peep? Currently, in our implementation, we rely in combination of delivery preference and object status for that.

2024-07-30 10:21 UTC, LPardue commented on draft-ietf-moq-transport.md
> +QUIC streams offer in-order reliable delivery, differentiation of priority in
QUIC streams as a transport feature don't really offer prioritization as described though

2024-07-30 17:00 UTC, martinduke commented
> How does one close a peep? Currently, in our implementation, we rely in combination of delivery preference and object status for that.

I think a Stream FIN would be sufficient.

2024-07-30 17:01 UTC, martinduke commented on draft-ietf-moq-transport.md
> +QUIC streams offer in-order reliable delivery, differentiation of priority in
I agree that it's not in 9000, but as you know it's a common feature of APIs, and streams are the lever by which QUIC can prioritize certain bits of data.

Is there a wording you would prefer?

2024-07-30 17:34 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +## Peeps {#model-peeps}
May be call it SubGroups :-) ?

2024-07-30 17:36 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +Every object belongs to exactly one Peep.
s/Every object/Every object within a group, to be more specific that peepId are scoped to a given group

2024-07-30 17:38 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
I think adding clarification that Peeps addresses the cases where a given MOQT group might need multiple streams  .. not sure of the exact wording though

2024-07-30 17:42 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
I wonder if we need to provide these recommendations at all . May be if we leave it to say 
"Original publishers assigned objects within a group to different peeps driven by the prioritization and dependency requirements between the objects. This in certain cases allow mutiple QUIC streams to transport the objects with in a single group".
Then add few non-normative examples for the same
- Say example for temporal scalability
- Example where all the objects are of same priority and hence has one Peep.

2024-07-31 14:28 UTC, ianswett commented on draft-ietf-moq-transport.md
> +A peep is a collection of one or more objects and is a sub-unit of a group
I believe order matters, so maybe sequence instead of collection?

```suggestion
A peep is a sequence of one or more objects and is a sub-unit of a group
```

2024-07-31 16:36 UTC, ianswett reviewed
This looks good overall, some comments/questions

2024-07-31 16:36 UTC, ianswett commented on draft-ietf-moq-transport.md
> +stream.
```suggestion
have a dependency and priority relationship benefitting from in-order delivery,
and sharing a QUIC stream.
```

2024-07-31 16:36 UTC, ianswett commented on draft-ietf-moq-transport.md
> +When a Track's forwarding preference (see {{object-fields}}) is "Track" or
Why not allow Peeps to be in "Datagram"?  If they fit, they fit?

Admittedly, the extra overhead of a Peep ID is unnecessary

2024-07-31 16:36 UTC, ianswett commented on draft-ietf-moq-transport.md
> +Original publishers assign each Peep a Peep ID, and do so as they see fit.
What's the scope of the Peep ID space, a Group?

2024-07-31 16:36 UTC, ianswett commented on draft-ietf-moq-transport.md
> +ideally have a lower priority than the one with two objects.
```suggestion
dependent on each other, the higher priority Object ought to be included in the same
peep as the lower object ID, and the other Object ought to be in a different peep.
```

2024-07-31 18:45 UTC, LPardue commented on draft-ietf-moq-transport.md
> +QUIC streams offer in-order reliable delivery, differentiation of priority in
I'd extract the priority part and put it in another sentence afterwards such as

"Furthermore, many implementations offer the ability to control the relative priority of streams, which allows control over the scheduling of sending data on active streams"

Or something like that

2024-08-01 18:20 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +Original publishers assign each Peep a Peep ID, and do so as they see fit.
+1 on making it explicit that Peeps are scoped to a given Group

2024-08-05 16:48 UTC, vasilvv commented
> > How does one close a peep? Currently, in our implementation, we rely in combination of delivery preference and object status for that.
> 
> I think a Stream FIN would be sufficient.

How am I supposed to know when to send a FIN?

2024-08-05 17:58 UTC, martinduke commented
> > > How does one close a peep? Currently, in our implementation, we rely in combination of delivery preference and object status for that.
> > 
> > 
> > I think a Stream FIN would be sufficient.
> 
> How am I supposed to know when to send a FIN?

The publisher sends a FIN when the Peep is done. The relay knows a Peep is complete when it receives the FIN from upstream.

2024-08-05 18:02 UTC, afrind commented
> The publisher sends a FIN when the Peep is done. The relay knows a Peep is complete when it receives the FIN from upstream.

Is there ever a case where a publisher needs to close a stream and ensure all data on it is delivered, but does not know that the peep is done, or knows it is not done.  For example - in response to an unsubscribe or graceful closure.

2024-08-06 08:27 UTC, vasilvv commented
> The publisher sends a FIN when the Peep is done. The relay knows a Peep is complete when it receives the FIN from upstream.

How is this represented in the cache?  Are FINs guaranteed to be always at the same position?

One scenario where the sender might FIN a peep earlier is if the next object in the peep is past subscription end, though I'm not sure how we'd hit this in practice.

2024-08-14 17:31 UTC, martinduke commented on draft-ietf-moq-transport.md
> +## Peeps {#model-peeps}
I invite you to start a discussion thread about naming; if there is consensus I am happy to adopt that name.

2024-08-14 17:44 UTC, martinduke commented on draft-ietf-moq-transport.md
> +
I don't think we want to make implementers figure out the implications of QUIC streams of their own. Is there harm in having a SHOULD here?

2024-08-14 17:47 UTC, martinduke commented on draft-ietf-moq-transport.md
> +When a Track's forwarding preference (see {{object-fields}}) is "Track" or
This would work, but IIUC we don't currently allow multiple objects in a Datagram, so this seems like a different discussion.

2024-08-14 18:08 UTC, martinduke commented
> > The publisher sends a FIN when the Peep is done. The relay knows a Peep is complete when it receives the FIN from upstream.
> 
> How is this represented in the cache? Are FINs guaranteed to be always at the same position?
> 
> One scenario where the sender might FIN a peep earlier is if the next object in the peep is past subscription end, though I'm not sure how we'd hit this in practice.

Good point, I've added an end of Peep object.

2024-08-14 18:39 UTC, martinduke commented
OK, I believe I've fully addressed all comments except for those I've left unresolved. @suhasHere @ianswett  If you are satisfied with my response, please resolve the comment.

2024-08-15 03:34 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
May be I wasn't clear in my above comment.  
Yes , each peep must maps to a QUIC Stream and making it explicit is good thing. 
All i was trying to say the conditions listed are examples and not conditions as such. If it was listed under non-normative example of few possible ways a group can have peeps in it , i think it would be more clearer.

2024-08-15 03:37 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +property of the Track and the Peeps it contains. In both cases, a lower
We should s/Peeps/Objects. 

Objects have priorities and the objects in a group that has same priority can be assigned to a given peep (since peep == stream).

2024-08-15 03:40 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +in peeps are sent in increasing Object Id order.
I don't think the new suggested changes are needed since the paragraph starts with "Within the same Group, and the same priority level," which implies if there were multiple peeps and differ in priorities, they are sent in the priority order.

2024-08-15 03:42 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +ID`.  All objects on the stream have the `Publisher Priority' specified in the
nit s/'/`

2024-08-15 03:45 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +ollowing fields.
type in word following

2024-08-15 03:48 UTC, suhasHere reviewed
thansk @martinduke for the new set of edits. I just had few nits/clarification points. PLease let me know your thoughts. 
I am liking the general direction.

2024-08-15 15:50 UTC, martinduke commented on draft-ietf-moq-transport.md
> +
No, I think I understand. You would prefer that there is no normative guidance, but that we provide an example of a separate mapping. I would prefer that we have a SHOULD with the recognition that there are reasons a publisher might choose a different mapping.

I'm not going to lie down in the road over this, but would like to hear the opinions of others. If most agree with you, I'm happy to make the change.

2024-08-15 15:52 UTC, martinduke commented on draft-ietf-moq-transport.md
> +property of the Track and the Peeps it contains. In both cases, a lower
I guess I don't follow. What would it mean for two objects in a peep to have different priorities? Object priorities make sense in the current document, because each object can be its own stream. But in this PR, that's just a case where each Peep is only one object.

2024-08-15 15:54 UTC, martinduke commented on draft-ietf-moq-transport.md
> +in peeps are sent in increasing Object Id order.
I agree that strictly speaking, the logic here is somewhat redundant. But I think the new text makes it clearer. Do you disagree?

2024-08-17 19:32 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +property of the Track and the Peeps it contains. In both cases, a lower
What i meant it  is , since peeps are priority grouping within a stream, all the objects with a same priority value belong to same peep. This enables delivering peep as a QUIC Stream.  Application sets priorities on objects and what is cached are objects.

2024-08-19 14:47 UTC, martinduke commented on draft-ietf-moq-transport.md
> +property of the Track and the Peeps it contains. In both cases, a lower
I understand what you mean now.

I had not envisioned that objects with the same priority must be in the same peep. For example, two objects could have the same priority but no dependency relationship. But if no one has a use case for that, I'm happy to make it impossible for two peeps to have the same priority: just make the Peep ID also be the priority (thus also shrinking the wire image).

2024-08-21 16:13 UTC, martinduke commented
No normative language, summarize what streams are.

2024-08-21 16:18 UTC, martinduke commented on draft-ietf-moq-transport.md
> +
Interim: Remove normative language, describe what streams do.

2024-08-21 16:22 UTC, martinduke commented on draft-ietf-moq-transport.md
> +
Increasing object ID is a MUST

2024-08-21 16:23 UTC, martinduke commented on draft-ietf-moq-transport.md
> +When a Track's forwarding preference (see {{object-fields}}) is "Track" or
Interim: Ian is OK with this

2024-08-21 16:41 UTC, martinduke commented on draft-ietf-moq-transport.md
> +property of the Track and the Peeps it contains. In both cases, a lower
Interim: people like all peeps having a different priority, but Alan may have a use case? We'll leave it as is for now.

2024-08-21 16:51 UTC, martinduke commented
@afrind wants to make a proposal, wait for that

2024-08-21 16:59 UTC, wilaw commented
For bikesheading on the name, I make these two proposals:
1. "Stream" - this correlates directly with the mapping to QUIC. Simple to comprehend and explain. 
2. "Block" - this denotes contiguity and avoids overloaded use of the term "stream".

2024-08-21 17:24 UTC, afrind commented on draft-ietf-moq-transport.md
> +in peeps are sent in increasing Object Id order.
The language is confusing because Peeps don't have priority, Objects do.  All objects in the same peep have the same priority, so you can call that the priority of the Peep, but the wording isn't totally clear.

Mandating increasing object ID within a peep is a good thing, but using object ID as the tie-breaker between peeps with equivalent object priority is not good.

Consider this case, where all objects have priority 128:

Peep/Stream 1:

Object 1, Object 3

Peep/Stream 2:

Object 2, Object 4

Let' assume all data has been written to the QUIC stack.  At the point when all the bytes of Object 1 are sent, the priority of Peep/Stream 2 needs to change to be higher than Peep/Stream 1.  This is way more complex than most implementers what to deal with.

So we can:

1. Make Peep ID the tie-breaker - with the same priority, lower peep ID goes first
2. Collapse Peep ID and Priority:
  2a. Use 62 bits - priority gets larger in kind of an ugly way
  2b. Use 8 bits - restricts maximum peeps per group, which probably breaks some object-per-stream cases
3. Leave the language as is, which is super hard to implement
4. Leave the wire image the same, but add a SHOULD NOT set two peeps to the same priority (but realizing that they will be the same when numPeeps > 256).
5. Something else?

2024-08-22 16:23 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +in peeps are sent in increasing Object Id order.
+1 on keeping priority as part of the Object and not a Peep's property. I think we need  to fix text to make sure that's reflected so. 
Also option 1 would be my choice

2024-08-22 22:04 UTC, martinduke commented on draft-ietf-moq-transport.md
> +in peeps are sent in increasing Object Id order.
@suhasHere, I have no idea how priority can meaningfully be an Object property? Priorities are implemented at the QUIC stream level, so how do two object in the same stream have different priority?

2024-08-22 22:05 UTC, martinduke commented
I have made all changes I know to do. I am awaiting @afrind making a concrete proposal on the question of whether or not two Peeps can have the same priority, and the wire image implications downstream from that.

2024-08-23 04:19 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +in peeps are sent in increasing Object Id order.
So a MOQ Application interfaces with moq object model and assigns priorities to the objects. The moq stack has a new object to send ( output of the priority decision algorithm), it looks at the object priority and does one of the following to match moq object priority to QUIC Stream.  
   - create a new stream , set the priority of the stream to match the priority of the object or
   - If there is already a stream created (as per first step) , pick that stream and send the object over that stream.
   
When relays receive the objects, the canonical object has priority saved as well. So relay for downstream can apply the similar logic.

2024-08-23 14:53 UTC, ianswett reviewed
Looks very good overall, some detailed suggestions.

2024-08-23 14:53 UTC, ianswett commented on draft-ietf-moq-transport.md
> +({{model-group}}). A peep consists of a set of objects within a Group that
```suggestion
A peep is a sequence of one or more objects from the same group
({{model-group}}) in ascending order by Object ID. Objects in a peep
```

2024-08-23 14:53 UTC, ianswett commented on draft-ietf-moq-transport.md
> +than one stream.
```suggestion
than one QUIC stream.
```

2024-08-23 14:53 UTC, ianswett commented on draft-ietf-moq-transport.md
> +description in the remainder of this section does not apply.
```suggestion
"Datagram", Objects are not sent in Peeps, no Peep IDs are assigned, and the
description in the remainder of this section does not apply.
```

2024-08-23 14:53 UTC, ianswett commented on draft-ietf-moq-transport.md
> +Every object within a Group belongs to exactly one Peep.
What if an Object appears in multiple Peeps?  Should the session be closed with a protocol error or something similar if it's detected?

2024-08-23 14:53 UTC, ianswett commented on draft-ietf-moq-transport.md
> +dependent on object B, then delivery of A can follow B, i.e. B and A can be
Nit: usually I see examples B following A in examples?

2024-08-23 14:53 UTC, ianswett commented on draft-ietf-moq-transport.md
> +possible, choose the composition that results in the fewest Peeps in a group.
This last point about minimizing the number of streams/peeps used could be important.  I wonder if that deserves a RECOMMENDED or SHOULD because it minimizes resource usage and the possibility of running out of available streams.

2024-08-23 14:53 UTC, ianswett commented on draft-ietf-moq-transport.md
> +optimal choice would depend on the dependencies of later objects.
```suggestion
```

I'm inclined to remove this example entirely.

2024-08-23 14:53 UTC, ianswett commented on draft-ietf-moq-transport.md
> +A group is a collection of one or more peeps and is a sub-unit of a track
```suggestion
A group is a collection of objects and is a sub-unit of a track
```
I think it makes more sense to keep the existing definition here.

2024-08-23 14:53 UTC, ianswett commented on draft-ietf-moq-transport.md
> +in peeps are sent in increasing Object Id order.
For now, I think making Peep ID the tiebreaker is probably best, but it does feel very duplicative to the priority then.

I also question whether a limit of 256 peeps in a Group is a problem?  I can't even think of a use case where one needs 8 peeps.

2024-08-23 14:53 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of Peep. Object ID is one greater than the largest
Do we need this?  I'd be inclined not to add it until we have a use case.

2024-08-23 16:04 UTC, martinduke commented on draft-ietf-moq-transport.md
> +Every object within a Group belongs to exactly one Peep.
I think this is the same as any other object that appears twice on the wire with different properties. If the sequences match but the payloads are different, what do we do?

2024-08-23 16:07 UTC, martinduke commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of Peep. Object ID is one greater than the largest
There was a long discussion up-thread where Victor asked for this. As a relay, I don't know when to close the stream until I see this. The alternative is to leave all streams open until the Group is done, which I suppose would work?

2024-08-23 16:09 UTC, martinduke commented on draft-ietf-moq-transport.md
> +possible, choose the composition that results in the fewest Peeps in a group.
I would be fine with that, but (1) I got pretty firm "no normative text" feedback, and more importantly (2) in the absence of any other normative guidance, I don't know how to write this. If there are no guidelines whatsoever for peep assignment except "minimize # of peeps", that collapses pretty quickly to stream-per-group.

2024-08-23 16:21 UTC, martinduke commented
Why have Peep ID be a tiebreaker if we also have priority? Just let the streams have the same priority!

2024-08-23 16:39 UTC, ianswett commented on draft-ietf-moq-transport.md
> +Every object within a Group belongs to exactly one Peep.
Fair, i was more thinking about the exact same Object being included in two different peeps.

2024-08-23 16:43 UTC, ianswett commented on draft-ietf-moq-transport.md
> +possible, choose the composition that results in the fewest Peeps in a group.
What you have now is fine as guidance, so given there was a lack of interest in normative text, let's keep it as is.

2024-08-23 16:44 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of Peep. Object ID is one greater than the largest
Interesting point.  I'm fine with adding it then.

2024-08-23 16:56 UTC, martinduke commented on draft-ietf-moq-transport.md
> +Every object within a Group belongs to exactly one Peep.
Every object has one peep ID on the wire. So if the same object is delivered twice with different Peep IDs, that's like any other case where the same objects arrives with different metadata or content.

Maybe the interesting error case is a QUIC stream that carries multiple peeps.

2024-08-23 17:09 UTC, martinduke commented on draft-ietf-moq-transport.md
> +Every object within a Group belongs to exactly one Peep.
Correction: a QUIC stream can't carry multiple peeps because the Peep ID is only expressed once in the stream.

2024-08-23 17:26 UTC, afrind commented on draft-ietf-moq-transport.md
> +Object ID order.
Individual Comment: 

We had stream-per-object and object ID was the tie breaker.  To get the same functionality with stream-per-peep, you need peep ID as a tie breaker.  You might need > 256 peeps per group when you are using object-per-peep (eg: stream-per-object).

2024-08-23 18:06 UTC, ianswett approved these changes

2024-08-23 18:11 UTC, ianswett commented on draft-ietf-moq-transport.md
> +possible, choose the composition that results in the fewest Peeps in a group.
```suggestion
possible, choose the composition that results in the fewest Peeps in a group
to minimize the number of QUIC streams used.
```

2024-08-23 22:03 UTC, fluffy requested changes
Conceptually agree with the big picture here but bunch of details I think need to be sorted out before we merge.

2024-08-23 22:03 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of Peep. Object ID is one greater than the largest
I think how we indicate end of group /  end of peep deservers it own discussion and PR. I think I like this but see it as separable issue.

2024-08-23 22:03 UTC, fluffy commented on draft-ietf-moq-transport.md
> +equal to a previously sent Object ID with the same Group ID.
I think we should add a note here that there could be other streams with older objects. This is going to happen in reconnect corner cases.

2024-08-23 22:09 UTC, martinduke commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of Peep. Object ID is one greater than the largest
do you want me to revert this change?

2024-08-23 22:12 UTC, martinduke commented on draft-ietf-moq-transport.md
> +## Peeps {#model-peep}
I am happy to change it once someone identifies a consensus, but don't want to hold it up over a bikeshed

2024-08-23 22:14 UTC, martinduke commented on draft-ietf-moq-transport.md
> +property of the Track and the Peeps it contains. In both cases, a lower
this seems like semantics? the wire image only allows you to send one priority per peep, so whatever metaphysical priority the application assigns to objects has no discernible effect inside MoQT.

2024-08-23 22:18 UTC, martinduke commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of Peep. Object ID is one greater than the largest
FYI there was a discussion on this point up thread.

2024-08-23 22:31 UTC, afrind reviewed
Individual Comments

2024-08-23 22:31 UTC, afrind commented on draft-ietf-moq-transport.md
> +## Peeps {#model-peep}
> we are not at the point

I assume you meant to say "we *are* at the point"?

2024-08-23 22:31 UTC, afrind commented on draft-ietf-moq-transport.md
> +property of the Track and the Peeps it contains. In both cases, a lower
> We should jut say all the objects in the same group with the same peep-id MUST have the same publisher priority.

This is necessarily true from our wire encoding, which I think everyone is happy with, so we're only talking about how best to convey the concepts.

2024-08-23 22:31 UTC, afrind commented on draft-ietf-moq-transport.md
> +priority of two Peeps in a Group are equal, the lower Peep ID has priority.
This is preserving what is in the current draft for stream-per-object - there was never a way to fair share objects in this mode, because Object ID was the tiebreaker.  

Adding Peeps opens the question of if we want to be able to fair share peeps.  In the interim I argued for a use case, but after consulting with the originators of said use case, I decided that a strict ordering is probably what they want.  I propose we advance this PR keeping as close to the existing behavior (Peep ID tiebreakers), and revisit fair-sharing them separately.

2024-08-23 22:31 UTC, afrind commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of Peep. Object ID is one greater than the largest
Reverting this change will break my relay, so I don't want you to revert it.  However, I'm ok with switching it to "PeepContinues" and if a Peep ends without it, the stream FIN indicates end-of-peep.

2024-08-23 22:31 UTC, afrind commented on draft-ietf-moq-transport.md
> +equal to a previously sent Object ID with the same Group ID.
Let's add that in the batch of PRs that deal with reconnect, etc.

2024-08-23 22:57 UTC, fluffy commented on draft-ietf-moq-transport.md
> +## Peeps {#model-peep}
oops yes - sorry - i did mean we are at the point we should pick a good name.

2024-08-23 23:08 UTC, fluffy commented on draft-ietf-moq-transport.md
> +property of the Track and the Peeps it contains. In both cases, a lower
Martin, I think you are missing the key point of what a moq priority is. Imagine QUIC had no priorities at all and at the QUIC layer things acted in the way QUIC would if the priorities were all set to the same thing.  In this case, MoQ priorities are still super useful and help the application decide which object gets sent next to the QUIC stack. And for implementations that don't send stuff to the QUIC stack until the congestion window opens up for the stream, this allows them moq level to get a wide range of priorities behavior to happen. The reason real time stuff is implemented this way is because once you put something on the QUIC stack, a huge limitation of QUIC APIs is there is no way to remove it, so if it expires before it is sent, you use up the bandwidth anyways. 

So what I am trying to say is priorities in MoQ are much more than just telling the quic stream what priority to use. They change the oder of what gets put into the quic stack.

2024-08-23 23:32 UTC, ianswett commented on draft-ietf-moq-transport.md
> +Every object within a Group belongs to exactly one Peep.
From an Object model perspective, I think that's a good direction, @fluffy 

The wire format as proposed allows one to violate that Object model, which is where I was going with my normative suggestion.  It also allows Object ID to decrease, which we might want to fix in a follow-up PR.

2024-08-24 02:50 UTC, fluffy commented on draft-ietf-moq-transport.md
> +equal to a previously sent Object ID with the same Group ID.
Fair enough - that makes sense to deal with it then

2024-08-24 02:58 UTC, fluffy commented on draft-ietf-moq-transport.md
> +## Peeps {#model-peep}
What would you think of instead of PeepID, calling it StreamAlias. Define it as things with different StreamAlias MUST NOT be on the same QUIC stream and things with the same StreamAlias inside the same group SHOULD be on the same QUIC stream. 

I'm not sure I love this name but I'm just trying to provide some sort of constructive suggestions.

2024-08-24 03:04 UTC, fluffy commented on draft-ietf-moq-transport.md
> +priority of two Peeps in a Group are equal, the lower Peep ID has priority.
this seems just less flexible than the alternative I can't see why we would do that

2024-08-24 03:06 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of Peep. Object ID is one greater than the largest
oh, it was marked resolved so I missed it. I will go comment on it

2024-08-24 03:14 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of Peep. Object ID is one greater than the largest
So this is basically the tombstone approach and I am a fan of that. However, I think we need to do this the same way end a group and end a track and this. Given we took the "last flag" approach to end of group and end track. I think we should stay consistent here and do this the same way. 

So my proposal is basically we put an "End of Peep" marker in the Object Status. I would restructure the Object Status to have bit 0 indicate End of Peep, bit 1 indicate End of Group, bit 2 indicate End of Track.  While we are at it, having a non optional Object Status in every Object would probably use less bandwidth than making it optional. 

Thoughts on this approach ?

2024-08-25 01:34 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of Peep. Object ID is one greater than the largest
I'm ok with that, but I think I'd rather do it in a separate PR.

Also, I realize that I'm not sure what the difference is between "Group does not exist" and "End of Group" with am Object ID of 0?  A related qustion is what the Object ID should be for "Group does not exist"?  I'm starting to think "Group does not exist" and it's the only one where Object ID has a meaningless value.

2024-08-25 01:53 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of Peep. Object ID is one greater than the largest
https://github.com/moq-wg/moq-transport/pull/509

2024-08-25 12:47 UTC, ianswett commented
> For bikesheading on the name, I make these two proposals:
> 
> 1. "Stream" - this correlates directly with the mapping to QUIC. Simple to comprehend and explain.
> 2. "Block" - this denotes contiguity and avoids overloaded use of the term "stream".

Block and Stream work for me.

I was going to say that I prefer "QUIC Stream", but given this might be over WebTransport, technically it'd be a WebTransport stream, so defining the term "Stream" at the top of the document should make that clear.

2024-08-25 12:52 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of Peep. Object ID is one greater than the largest
Reflecting on whether we need this, I think a stream FIN means the Peep is closed.  Otherwise someone could split a multi-object Peep into single Object streams, which is definitely not the intent and maybe could be used as an attack (thinking segment smack, etc)?

Session migration is important, but in that case I think streams should be reset or the session just suddenly goes away to indicate there is more data that couldn't be sent.  This is a reminder that writing up session migration could be really helpful for understanding how streams and MoQ interact.

But happy to bikeshed this issue afterwards.

2024-08-26 18:02 UTC, martinduke commented on draft-ietf-moq-transport.md
> +property of the Track and the Peeps it contains. In both cases, a lower
Offline: Alan is fine with peep ID = priority, meaning that two Peeps can't have the same priority. Text is updated, closing this comment.

2024-08-26 18:03 UTC, martinduke commented on draft-ietf-moq-transport.md
> +in peeps are sent in increasing Object Id order.
Text now has Peep ID = tiebreaker, @afrind is OK with it. Closing this comment, though Cullen has complaints downthread. Further discussion there.

2024-08-26 18:05 UTC, martinduke commented on draft-ietf-moq-transport.md
> +property of the Track and the Peeps it contains. In both cases, a lower
This only works for the first hop for the publisher; relays will only be able to use the priority expressed on the wire, which is Peep-level.

That said, I'm happy to rewrite this to talk about what's on the wire and avoid any metaphysical discussion of object priority or telling MoQT what API to present here.

2024-08-27 21:40 UTC, martinduke commented on draft-ietf-moq-transport.md
> +## Peeps {#model-peep}
Cullen's use case: the relay might have received packets out of order, possibly because it's non-MoQT upstream. In this case, the only choices are drop it, send out of order in the stream, or open new stream. third choice is best.

2024-08-27 21:45 UTC, fluffy commented on draft-ietf-moq-transport.md
> +## Peeps {#model-peep}
QuicStreamIndicator as name ?

2024-08-27 21:57 UTC, martinduke commented on draft-ietf-moq-transport.md
> +priority of two Peeps in a Group are equal, the lower Peep ID has priority.
Cullen makes the point that the current algorithm works, if one views objects as the thing that holds priority. Within the group, the most important objects (peeps) will go first.

2024-08-27 22:09 UTC, fluffy commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of Peep. Object ID is one greater than the largest
Martin convinced me this was fine and I was confused. And the more I thought about, we don't get many gains by closing the streams before the end of group so I would be fine with this as is and also fine with we just use end of group.

2024-08-27 22:14 UTC, suhasHere commented
One more name suggestion : SubGroup

2024-08-27 23:29 UTC, martinduke commented on draft-ietf-moq-transport.md
> +## Peeps {#model-peep}
took the normative text (ish), closing although the naming bikeshed continues.

2024-08-27 23:30 UTC, martinduke commented on draft-ietf-moq-transport.md
> +Every object within a Group belongs to exactly one Peep.
I don't understand how this allows Object ID to decrease, unless you mean that a higher object ID from one Peep could come before a lower one in a different peep. But that's a feature not a bug.

2024-08-28 16:49 UTC, martinduke commented on draft-ietf-moq-transport.md
> +* 0x5 := Indicates end of Peep. Object ID is one greater than the largest
Talking offline to @fluffy, he is now fine with the end of Peep object, though we agreed that the publisher MAY use an end of Group object to implicitly close all open Peeps.

2024-08-28 16:52 UTC, martinduke commented on draft-ietf-moq-transport.md
> +priority of two Peeps in a Group are equal, the lower Peep ID has priority.
@afrind makes the point that it's hard to implement this because you'd have to change stream priorities mid-stream as the object IDs change, which QUIC APIs are generally bad it.

I'm not deeply concerned either way, as priorities are somewhat advisories. I'd just like these two to come to some agreement.

2024-08-28 17:51 UTC, ianswett commented on draft-ietf-moq-transport.md
> +Every object within a Group belongs to exactly one Peep.
Sorry, I think my comments were confusing, please disregard them for now.

2024-08-28 17:54 UTC, ianswett approved these changes

2024-08-29 14:29 UTC, ianswett commented
Merging with the understanding that we'll continue to discuss how prioritization should work.

2024-08-29 14:29 UTC, merged