Adding an Extensible Object Header
moq-wg/moq-transport pull request #502
Opened 2024-08-06 13:38 UTC by wilaw

This PR adds an extensible header to Objects, as well as updating the SETUP parameters to allow negotiation of required extension header parameters. Extensible headers have types which are IANA registered. A new Extensible header is defined and reserved with type 0x0, allowing name/value data to be passed in a manner compatible with HTTP headers.  A new example is added showing serialization of an Object with an extensible header. 

Fixes: #433

2024-08-06 16:01 UTC, afrind commented
Individual Comment:

This seems generally ok.  Perhaps there's an optimization where Object encodings don't carry even the count field unless at least one extension is negotiated.

The wider problem I see with this design is that extension negotiation is hop-by-hop (HTTP has similar problems with SETTINGS).  What happens when, say, the publisher and relay negotiate use of an extension, but one of the subscribers to the relay does not?

2024-08-06 22:05 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Headers are present.
I think this should allow actual extensions too not just the count. isn't it?  This will be needed especially when serving object from the cache, then those extensions needs to be sent along

2024-08-06 22:09 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +MUST be parsed by relays. Extension headers not specified via the
I understand the MUST. But I wonder if we should add a indicator in each extension to include if it needs to be forwarded as well.  These extension headers must not be modified by the relays either to be complete. Since some of the extensions are useful to downstream.

2024-08-06 22:12 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +##### Extension Header type 0 {#extension-header-zero}
I don't think we need this defined ? Can you please share your thoughts on why we need this ?

2024-08-06 22:13 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Header Value (..)
Header Value should be opaque bytes.

2024-08-06 22:14 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  'MOQ Extension Headers'. See {{iana}}.
I think we are missing iana section. 
At a high level, the iana registration must have
 - extension type, reference to rfc that defines the extenson
 -  this needs to be specification required

2024-08-06 22:15 UTC, suhasHere reviewed
Thanks @wilaw  for this PR. I like the direction of this PR and have few clarification questions/nits.

2024-08-07 09:36 UTC, wilaw commented on draft-ietf-moq-transport.md
> +MUST be parsed by relays. Extension headers not specified via the
The assumption is that these extensions headers must always be forwarded and must not be modified by any relay. I could add language stating that explicitly?

2024-08-07 09:41 UTC, wilaw commented on draft-ietf-moq-transport.md
> +##### Extension Header type 0 {#extension-header-zero}
This default extension header provides a simple way to add ad-hoc name/value pairs to any object. This is similar to the ability of clients and servers to define custom request and response headers in HTTP-land. That functionality has proven extremely useful and efficient in enabling rapid development, testing and deployment of solutions without having to go to IANA registries or revise specifications. I'd like a similar capability within MOQT hence Extension Header Type Zero.

2024-08-07 09:48 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  'MOQ Extension Headers'. See {{iana}}.
Yes, the [IANA section ](https://moq-wg.github.io/moq-transport/draft-ietf-moq-transport.html#name-iana-considerations)of the whole MOQT document is a big todo. I added the requirement to define the MOQ extension Headers table to Section 8. I figure the editors plan to handle all the IANA stuff towards the end. It will be specifications required etc once it is defined.

2024-08-07 09:49 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  Header Value (..)
Clarification - opaque to whom - the relays?  Object headers values are not opaque to relays and nor are Extension Header values. If an application wants to hide content from a relay then it needs to place it in the Object payload (which is opaque) and not the headers.

2024-08-07 09:51 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  Headers are present.
I was thinking that Extension headers are immutable. If the publisher adds them, then any relay forwarding that object must preserve them. The object would be cached along with any extension headers it was carrying.

2024-08-07 11:34 UTC, mengelbart commented on draft-ietf-moq-transport.md
> +parameter is optional. Multiple of these parameters may be sent in a
This contradicts [section 6.1](https://moq-wg.github.io/moq-transport/draft-ietf-moq-transport.html#section-6.1), which states that there MUST NOT be duplicate parameters. I'm fine with lifting that restriction, though. If necessary, I think we could add this restriction to individual parameters that can't be duplicated.

```suggestion
parameter is optional. Multiple of these parameters MAY be sent in a
```

2024-08-07 11:34 UTC, mengelbart commented on draft-ietf-moq-transport.md
> +  Headers are present.
I think @suhasHere meant that the actual object extensions should be included as a canonical field, not just the count.

2024-08-07 11:34 UTC, mengelbart commented on draft-ietf-moq-transport.md
> +MUST be parsed by relays. Extension headers not specified via the
I think explicit language to state that extensions must be forwarded would be useful. Maybe it's enough to replace "MUST be parsed" with "MUST be forwarded"?

2024-08-07 17:16 UTC, ianswett commented on draft-ietf-moq-transport.md
> +MUST be parsed by relays. Extension headers not specified via the
I think we should say that headers MUST be forwarded and MUST NOT be modified if that's what we intend.

I'd like to have these authenticated when using MoQ per-object encryption, but that's a different draft.

2024-08-07 21:27 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +MUST be parsed by relays. Extension headers not specified via the
agree with @ianswett  and @mengelbart  .. Making it explicit is good in these cases.

I see GroupId, ObjectId and Extension Header can fall in to this category. 

Secure objects uses ObjectId and GroupId to be authenticated and encrypted end to end, for example.

I am sure there will some use-cases that would have extensions whose scope is hop by hop too. I will be totally ok to have an scope field in the extension that identifies if it is between original-publisher and end-subscriber or not.

2024-08-07 21:28 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +##### Extension Header type 0 {#extension-header-zero}
Thanks for the context.  Still i don't see if this adds much value in end to end context.

2024-08-07 21:30 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  Header Value (..)
If a relay supports an extension, it can parse it.  We know that from setup message that if a relay supports an extension or not, isn't it.

2024-08-07 21:30 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  'MOQ Extension Headers'. See {{iana}}.
+1 .. makes sense. thanks

2024-08-08 08:55 UTC, wilaw commented on draft-ietf-moq-transport.md
> +parameter is optional. Multiple of these parameters may be sent in a
@mengelbart  - good point. We either 
1. redefine section 6.1 to indicate that no duplicate parameters are allowed except for Required-Extension, which may be duplicated. 
2. Or we change the serialization of the VALUE of the REQUIRED-EXTENSION parameter. Since each extension type is a varint, and the length of the parameter is specified, the parser can just keep reading varints until it reaches the length. In this way, multiple extension types can be communicated in a single REQUIRED-EXTENSION parameter and we can retain the existing requirement that parameters MUST NOT be duplicated. 

Preference?

2024-08-22 14:29 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  Headers are present.
I have updated the coanonical fields definitions to inlcude both fields, as shown below. 

> * Object Extension Count: The number of Object Extensions present. A value of 0
>   indicates that no Object Extension Headers are present.
>   
> * Object Extensions : an optional concatenation of Object Extension Headers. See
>   {{object-extensions}} below.

2024-08-22 14:36 UTC, wilaw commented on draft-ietf-moq-transport.md
> +MUST be parsed by relays. Extension headers not specified via the
Given that we have no means, as Alan has pointed out, of propagating header requirements beyond the immediate hop, it means that if any relay wants to use the extension header then all relays must forward them and not modify them. I have therefore modified  the language to read that 

> Extension headers MUST be forwarded and MUST NOT be modified by relays.

2024-08-22 14:38 UTC, wilaw commented on draft-ietf-moq-transport.md
> +parameter is optional. Multiple of these parameters may be sent in a
I went with option 2. Now there is only a single Required Extension parameter key. It's value can hold a concatenation of multiple Extension Header numerical types

2024-08-23 15:31 UTC, ianswett reviewed
One comment about the negotiation approach, and I also am unsure of how to best use this, given it's negotiated hop-by-hop.

2024-08-23 15:31 UTC, ianswett commented on draft-ietf-moq-transport.md
> +The REQUIRED-EXTENSION parameter (key 0x02) allows the client to specify
This is a potentially painful way to negotiate extensions.  What about making it REQUESTED-EXTENSION and then the server responds with the ones it supports of the requested set?  At that point, if the client wants to close the connection because the server doesn't support a required extension, then it can.

2024-08-23 21:21 UTC, fluffy requested changes
I basically like this but I think some parts that need some discution and some parts I think would be better as separate draft.

2024-08-23 21:21 UTC, fluffy commented on draft-ietf-moq-transport.md
> +#### REQUIRED-EXTENSION parameter {#required-extensions}
I don't think it makes sense to negotiate object extensions with the relay. This would be like negotiating HTTP header extensions with a socks proxy. Other types of extensions we need too negotiate with server but not these.   I think we can just remove this part of the PR.

2024-08-23 21:21 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  {{object-extensions}} below.
I'd like to talk about ideas to bit pack the extension indictors to save space but conceptually good with this.

2024-08-23 21:21 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  'MOQ Extension Headers'. See {{iana}}.
I think we need to make sure that small numbers are reserved for thing where space is issue, medium size numbers are for things that are standards, and large numbers are totally first come first serve and super easy to get and use any way you want.

2024-08-23 21:21 UTC, fluffy commented on draft-ietf-moq-transport.md
> +This specification defines a utility extension header. The value of this header
I think this whole extension should be moved to a separate draft that helps illustrate how to define an extension and show that we got things defined in a way where a separate draft can define an extension. 

I'm not a huge fan of it, I would rather that it was easy to get a number code point for "fluffy-idea-of-perfectp-trace-id" rather than put strings in the protocol that would better in an IANA table but I agree with a low friction way of getting customer extensions.

2024-08-23 21:29 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +not support a requested REQUIRED-EXTENSION, then it MUST close the connection.
I don't think closing the connection is right here. If a relay don't need to understand the extension, it just forwards it .

2024-09-06 08:10 UTC, RichLogan reviewed
Should we also update the structures shown in the `Multi-Object Groups` section to show extension count + extensions in the track and group forwarding preference structures? 

**Track**:

https://github.com/moq-wg/moq-transport/blob/358c5d75d93b28c63a955fc2eda17bfdcb839e5e/draft-ietf-moq-transport.md?plain=1#L1735-L1741

**Group**:

https://github.com/moq-wg/moq-transport/blob/358c5d75d93b28c63a955fc2eda17bfdcb839e5e/draft-ietf-moq-transport.md?plain=1#L1777-L1782

2024-09-10 12:57 UTC, wilaw commented on draft-ietf-moq-transport.md
> +The REQUIRED-EXTENSION parameter (key 0x02) allows the client to specify
@ianswett  - I have modified the PR with this [commit ](https://github.com/moq-wg/moq-transport/pull/502/commits/ab407f75b8954c445f6dd1efef919631f93b58d2) to modify the extension negotiation and to rename the parameter to REQUESTED_EXTENSION

> The REQUESTED-EXTENSION parameter (key 0x02) allows the client to request
> the server to acknowledge support for  multiple Extension Header types
> {{object-extensions}} which are required for operation. The value is a
> concatenation of varints, each describing a 32-bit extension header type.
> This parameter is optional. If this parameter is present in the
> CLIENT_SETUP message, then the server MUST respond with a
> REQUESTED-EXTENSION parameter in its SERVER_SETUP message. This parameter
> MUST list the subset of those extensions previously requested by the client
> which the server supports. If the server does not support any of the
> requested extensions, then it MUST respond with a parameter value length of 0.
> The client can then choose to continue or disconnect the session, at its
> discretion.

2024-09-10 13:40 UTC, wilaw commented on draft-ietf-moq-transport.md
> +not support a requested REQUIRED-EXTENSION, then it MUST close the connection.
This has now changed. It is now a REQUESTED-EXTENSION parameter list from client to server with a response from the server. The client may then choose whether it wants to continue or disconnect.

2024-09-10 13:41 UTC, wilaw commented on draft-ietf-moq-transport.md
> +not support a requested REQUIRED-EXTENSION, then it MUST close the connection.
Additionally, all relays MUST forward and not modify all extensions.

2024-09-10 13:47 UTC, wilaw commented on draft-ietf-moq-transport.md
> +#### REQUIRED-EXTENSION parameter {#required-extensions}
This negotiation has now changed slightly. The clients uses the revised REQUESTED-EXTENSION parameter to indicate which extensions it would like and the server responds with the sub-set of those that it does support. The client may then chose to continue or disconnect. 

Since we have separate rules that relays MUST always forward all headers and MUST NOT modify them, any negotiation is practically only going to happen at the final hop. I agree that its utility is limited. I would like to remove it, but first I want agreement from those who wanted it in there in the first place.

2024-09-10 13:50 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  'MOQ Extension Headers'. See {{iana}}.
With this [commit](https://github.com/moq-wg/moq-transport/pull/502/commits/3759564cffa9a066349de4d018aba601f9c117d3) I have added guidance language for the IANA registration of the extension header types. 

>  MOQ Extension headers - we wish to reserve extension types 0-127 for
>   standards utilization where space is a premium, 128 - 16383 for
>   standards utilization where space is less of a concern, and 16384 and
>   above for first-come-first-served non-standardization usage.

These ranges correspond to 1-bye, 2 bytes and 3 bytes and beyond with varint encoding.

2024-09-13 11:34 UTC, fluffy commented on draft-ietf-moq-transport.md
> +Extension Header {
A very common use case if an extension that caries a single integer - for example in voice applications the audio level specified in RFC6464. For some voice only applications this can be critical to keep the overall bandwidth very small. For these very special uses cases, I would like a shorter encoding so here is my proposed change

For type values above 20, it looks just like how you have it. But for type values less than that, it becomes just the type followed by  value which is a varint. Removing a byte out of every audio packet does make a real difference to some applications.

2024-09-13 11:35 UTC, fluffy commented on draft-ietf-moq-transport.md
> +Extension Header {
Glad to send a PR to your PR if this sounds reasonable to you

2024-11-12 20:27 UTC, tianji-sdo commented
**A 5G use case to justify the support of the PR (Problem description & Requirements on MoQT per-object metadata header extension)**:
========
As we have presented in the IETF-121 MoQ session @ Dublin, the 3GPP 5G has standardized the solution of applying the MoQT to address the transmission of encrypted XRM media streams between MoQ server(s) and client(s) via MoQ relay. A MoQ relay is deployed in the 5G UPF. The corresponding 3GPP 5G specifications are TS 23.501 and TS 26.522. In the MoQT-based solution, there is per-object (or so-named per-PDU in 5G term) related metadata that is used to identify the PDU-set (i.e., a set of PDUs) related metadata information to 5G system. These PDU-set meta-info is identified and marked at a 5G UPF (i.e., where a MoQ replay runs) for RAN-based resource scheduling and optimization. Our IETF draft (https://datatracker.ietf.org/doc/draft-defoy-moq-relay-network-handling/)  has clearly explained the mechanism.  

Because an XRM media stream is encrypted (and so is the RTP header extension associated with an XRM PDU), the PDU-set metadata has to be mapped to the MoQT metadata field in an object header. The MoQ-based solution (as in 3GPP TS 23.501) is repurposing those object header fields, which leads to two problems: mapping accuracy and future extensibility.
 
Based on the discussions & rough consensus from the IETF-121 MoQ session, we think that the logics as specified in PR#502 , targeting at providing the OBJECT Extension Header, can address exactly the XRM ciphered stream challenges with a new revision of the MoQT draft. 

Those logics include REQUESTED-EXTENSION parameter, Object Extensions, as well as {{IANA}} part, and possibly more, in the current PR.

2024-11-20 15:48 UTC, gloinul commented on draft-ietf-moq-transport.md
> +  above for first-come-first-served non-standardization usage.
Should this space be greased or any particular picking algorithm?

2024-11-20 15:48 UTC, gloinul commented on draft-ietf-moq-transport.md
> +This specification defines a utility extension header. The value of this header
If this is kept in, it purpose needs to be clarified. But it feels like this is creating an additional extension space.

2024-11-20 15:48 UTC, gloinul commented on draft-ietf-moq-transport.md
> +An Object Extension is a concatenation of optional Extension Headers. These
I am bit worried by the usage of word Optional here? What exactly is optional? Looking below I get the impression that Extension header handling are depending on role of the node but in no case are they truly optional, other than it comes to the publisher including them. 

A Relay must forward and not modify
A client must be capable of receiving and ignoring them.

2024-11-20 15:48 UTC, gloinul commented on draft-ietf-moq-transport.md
> +The REQUESTED-EXTENSION parameter (key 0x02) allows the client to request
I struggle to understand how this header is useful unless all relay's in the chain forward it upstream towards the publisher for those that are related to the media content. 

Are we envisioning both next hop extension as well as whole chain extensions?

2024-11-20 15:53 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +MUST be parsed by relays. Extension headers not specified via the
I am fine with this as a starting place. If we may decide to support a way to indicate HBH vs E2E extensions, then we can address how to best solve it. 

Starting with MoQ Relays forwarding extensions as-is seems fine to get some implementation experience. 

Also https://datatracker.ietf.org/doc/draft-mzanaty-moq-loc/ and https://datatracker.ietf.org/doc/html/draft-jennings-moq-secure-objects-01 defines extensions that might be more than hbh scoped for example.

2024-11-20 16:14 UTC, LPardue commented on draft-ietf-moq-transport.md
> +  above for first-come-first-served non-standardization usage.
+1 on greasing - let's get these reserved now and people adding them in their implementation from day one

2024-11-22 20:36 UTC, afrind reviewed
Individual Review:

1. This needs a rebase because it doesn't include subgroups yet
2. I think we also might want a way to specify an extension per subgroup rather than per object (eg: an extension sent once at the beginning of the stream that applies to all objects that follow).

2024-11-29 12:51 UTC, wilaw commented on draft-ietf-moq-transport.md
> +##### Extension Header type 0 {#extension-header-zero}
Based on your and others feedback, I have removed (via  commit https://github.com/moq-wg/moq-transport/pull/502/commits/e1764972a4dc1be7fac8e1777462c560df6d6385) the Extension header type 0 definition. It can be added back in the future if necessary.

2024-11-29 12:52 UTC, wilaw commented on draft-ietf-moq-transport.md
> +This specification defines a utility extension header. The value of this header
Based on your and others feedback, I have removed (via commit https://github.com/moq-wg/moq-transport/commit/e1764972a4dc1be7fac8e1777462c560df6d6385) the Extension header type 0 definition. It can be added back in the future if necessary.

2024-11-29 13:30 UTC, wilaw commented on draft-ietf-moq-transport.md
> +Extension Header {
@fluffy  - this seems like a reasonable improvement.  I updated the PR with commit https://github.com/moq-wg/moq-transport/pull/502/commits/6f31642317f2fbddbc151db2f8994bf0fd10818b to reflect this improved compression scheme for extension types <=0x20

2024-11-29 13:36 UTC, wilaw commented on draft-ietf-moq-transport.md
> +This specification defines a utility extension header. The value of this header
Based on your and others comments, I removed (via commit https://github.com/moq-wg/moq-transport/commit/e1764972a4dc1be7fac8e1777462c560df6d6385) the Extension header type 0 definition. It can be added back in the future if necessary.

2024-12-03 13:24 UTC, wilaw commented
@RichLogan 
> Should we also update the structures shown in the `Multi-Object Groups` section to show extension count + extensions in the track and group forwarding preference structures?

Yes. Commit https://github.com/moq-wg/moq-transport/pull/502/commits/ae714067b66e38ccc47d126ba9ea079e3976549c fixes this.

2024-12-04 06:19 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
I am not too sure of the purpose of this parameter.
I am struggling understand what it means to say "server supports" .

2024-12-04 06:28 UTC, suhasHere requested changes
This is coming to be pretty close to finishing. I would like to see the PR based off the main branch to make sure of the encodings

2024-12-04 06:28 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
I am not too sure of the purpose of this parameter.
I am struggling understand what it means to say "server supports" .

2024-12-04 06:28 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  {{object-extensions}} below.
Like to understand what do we mean by concatenation here ?

2024-12-04 06:28 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +Headers is to facilitate the future evolution of the transport protocol.
I don't see the last sentence here is needed.

2024-12-04 06:28 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +  [Extension headers (...)],
Updating to latest changes will get rid of most of the changes that follow

2024-12-04 10:50 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  {{object-extensions}} below.
Meaning a series of Object Extension headers, serialized in sequence without any delimiters between them.

2024-12-04 10:52 UTC, wilaw commented on draft-ietf-moq-transport.md
> +
Imagine in the future we introduce a new header which signals to a relay that it should transmit this object in its own QUIC stream (for whatever reason). By "supporting" this header, the publisher is signalling that it is aware of any relay processing rules which that header may invoke.

2024-12-04 10:53 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  [Extension headers (...)],
Rebased as of 20min ago.

2024-12-05 09:14 UTC, wilaw commented
Based on feedback in yesterday's interim meeting, I added Commit https://github.com/moq-wg/moq-transport/pull/502/commits/f2fba0c8ae0d31767f3dad058c3b949b5a3c080d which relaxes the constraints on relays having to always forward and not modify extension headers. New language reads as 

> Object Extension Headers are visible to relays. Extension Headers SHOULD be forwarded and SHOULD NOT be modified by relays.

This allows for the identified use cases in which a) an edge relay wishes to remove watermarking infomration before it reaches the final subscriber and b) relays may add data to tracing extensions as the Object moves through the distribution network.

2024-12-06 06:41 UTC, wilaw commented
A request was made by chairs to collate use-cases for extension headers. Documented use-cases are listed below. 

1. 5G XR - as per https://github.com/moq-wg/moq-transport/pull/502/#issuecomment-2471516973 and  https://github.com/moq-wg/moq-transport/pull/502/#issuecomment-2479800594 
2. Tracing - https://opentelemetry.io/docs/concepts/signals/traces/ 
3. LOC - https://datatracker.ietf.org/doc/draft-mzanaty-moq-loc/

If there are more use-cases, please add them.

2024-12-18 05:31 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +
How about we have something along the lines in the core transport ( below formulation ,may be, exactly what you have, but i am writing it down in a single place to see if we all can agree)

### Relay Extension Processing Rules
1. If a relay understands an extension, it follows the rules as described by the specification that defines the extension, when processing such an extension. Such rules may be to  modify the extension ( by updating or by removing it), for example.
2. If the extension specification requires a given relay to understand an extension but relay doesn't support such an extension, it is treated as protocol violation.
3.  Else  the  MUST forwards the received extension as-is to downstream relays/subscribers.

Now on the point on  how to know if a relay understands an extension or not , there are couple of options
1. Reserve code points for such extensions OR
2. Use setup parameters to identify extensions

Extensions are per object property. I am not totally sure if we need stream level extensions at the moq layer though.

2025-01-31 16:03 UTC, ianswett commented on draft-ietf-moq-transport.md
> +requested extensions, then it MUST respond with a parameter value length of 0.
Omitting the parameter also seems ok, but that's a detail?

2025-01-31 16:40 UTC, ianswett reviewed
Thanks for all the updates Will, this is looking good, but I had some questions and suggestions.

2025-01-31 16:40 UTC, ianswett commented on draft-ietf-moq-transport.md
> +The REQUESTED-EXTENSION parameter (key 0x03) allows the client to request
This extension mechanism I believe means any extension is available to both client and server?  Alternatively, in QUIC extensions like Ack Frequency can be negotiated separately in each direction.

I can see the pros and cons of either, but if my understanding is correct, I think it's worth stating that explicitly.

2025-01-31 16:40 UTC, ianswett commented on draft-ietf-moq-transport.md
> +REQUESTED-EXTENSION parameter in its SERVER_SETUP message. This parameter
See comment above, but I think it should be different if we want to allow for asymmetric negotiation?

2025-01-31 16:40 UTC, ianswett commented on draft-ietf-moq-transport.md
> +* Object Extensions : an optional concatenation of Object Extension Headers. See
How about just "A sequence of ..."?

```suggestion
* Object Extensions : A sequence of Object Extension Headers. See
```

2025-01-31 16:40 UTC, ianswett commented on draft-ietf-moq-transport.md
> +    { Type = 0
I think this example needs to be updated?  I think types below a certain value are all varints?

2025-01-31 16:40 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  0x00 - 0x20 inclusive are followed by a single varint encoded value. Header
This is very similar to 'Parameters'.  It might make sense to use the same encoding for both?

I understand the interest in optimizing for varints, but in both case we could have odd types always be a single varint and even be length+value if we wanted?

2025-01-31 16:40 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  above for first-come-first-served non-standardization usage.
There's an issue filed for GREASING, FYI: https://github.com/moq-wg/moq-transport/issues/416

2025-01-31 17:26 UTC, wilaw commented on draft-ietf-moq-transport.md
> +The REQUESTED-EXTENSION parameter (key 0x03) allows the client to request
This is an Object header, and Objects flow from Publisher to Subscriber. The publisher would be writing the extension header and the subscriber would be reading and/or forwarding it. A "client' and "server" can fulfill either one, or both, of those roles. Not sure therefore that we need to state that the extension is available to be read by a subscriber, as that is a de facto property of all the Object headers.

2025-02-03 10:51 UTC, wilaw commented on draft-ietf-moq-transport.md
> +concatenation of varints, each describing an integer extension header type.
Draft text has now changed to ".. a sequence of"

2025-02-03 11:15 UTC, ianswett commented on draft-ietf-moq-transport.md
> +The REQUESTED-EXTENSION parameter (key 0x03) allows the client to request
I understand the reasoning that if you understand the header, you understand the header.  But I'm unsure what the purpose of negotiation is in that context?  Is it to negotiate optimizations to headers or content, such as compression?

2025-02-03 13:24 UTC, wilaw commented on draft-ietf-moq-transport.md
> +The REQUESTED-EXTENSION parameter (key 0x03) allows the client to request
Negotiation was introduced to support the enforcement of a a required per-hop object encoding between publisher and subscriber behavior. For example, imagine a hypothetical log tracing extension, carrying a log trace. The client may want to indicate that it does not want a connection to the server if the server doesn't support logging by way of the specified extension. 

However, after our first interim call on this subject, we agree to loosen the constraints for extensions to "Extension Headers SHOULD be forwarded and SHOULD NOT be modified by relays". This considerably weakens any attempt to enforce an end-to-end behavior across a delivery chain.

So one of the key questions to resolve this week is "Do we need to negotiate extensions at all?" We could leave them on a best-efforts basis for now and then get some implementation experience around whether or not we require negotiation and whether or not that negotiation should be bi-directional.

2025-02-03 15:10 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  0x00 - 0x20 inclusive are followed by a single varint encoded value. Header
The same count+TLV encoding is already used for both Parameters and Extension Headers (modulo the varint optimization for extension types 0..20). Is your proposal that we don't call them Extension Headers and instead use Parameters? That would require migrating the varint version to Parameters which complicates things. Over the wire the bits are identical, so I'm inclined to leave the definition as it is.

2025-02-03 21:51 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  0x00 - 0x20 inclusive are followed by a single varint encoded value. Header
I think calling them Extension Headers is good, but I'd rather the wire format be described as being identical to Parameters.  It's close today, but as you point out, not quite identical.

In the past, someone, possibly @martinduke proposed making all even parameter values encoded as varints and odd encoded as variable length binary values.  I think that proposal may make sense for both extension headers and parameters.

2025-02-03 21:54 UTC, ianswett commented on draft-ietf-moq-transport.md
> +The REQUESTED-EXTENSION parameter (key 0x03) allows the client to request
I'd be happy to not negotiate them for now and reconsider that later if it turns out to be useful.

2025-02-05 16:56 UTC, fluffy requested changes
I would like to change so that relays can change extentions

2025-02-05 16:56 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  above for first-come-first-served non-standardization usage.
This seems like about the right approach to IANA registrations

2025-02-06 11:53 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  {{object-extensions}} below.
We can look at bit packing once we have some implementation experience. Resolving for this draft.

2025-02-06 11:55 UTC, wilaw commented on draft-ietf-moq-transport.md
> +MUST be parsed by relays. Extension headers not specified via the
Following agreement at yesterday's interim meeting, I updated the language to be 

> Extension Headers are defined in external specifications and registered in an IANA table {{iana}}. These specifications define the type and value of the header, along with any rules concerning processing, modification, caching and forwarding. A relay which is coded to implement these rules is said to "support" the extension.
> 
> If unsupported by the relay, Extension Headers MUST NOT be modified, MUST be cached as part of the Object and MUST be forwarded by relays
> 
> If supported by the relay and subject to the processing rules specified in the definition of the extension, Extension Headers MAY be modified, MAY be cached and MAY be forwarded.

2025-02-06 11:57 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  Header Value (..)
With yesterday's interim, resolved with agreed language

> Extension Headers are defined in external specifications and registered in an IANA table {{iana}}. These specifications define the type and value of the header, along with any rules concerning processing, modification, caching and forwarding. A relay which is coded to implement these rules is said to "support" the extension.
> 
> If unsupported by the relay, Extension Headers MUST NOT be modified, MUST be cached as part of the Object and MUST be forwarded by relays
> 
> If supported by the relay and subject to the processing rules specified in the definition of the extension, Extension Headers MAY be modified, MAY be cached and MAY be forwarded.

2025-02-06 11:58 UTC, wilaw commented on draft-ietf-moq-transport.md
> +#### REQUIRED-EXTENSION parameter {#required-extensions}
Negotiation was removed with the latest commit, following discussion at the interim.

2025-02-06 12:01 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  above for first-come-first-served non-standardization usage.
I added a simple greasing scheme. 

> Header values: even types are followed by a single varint encoded value. Odd types are followed by a varint encoded length and then the header value. Every integer multiple of 17 or 18 is a reserved greasing value. These types MUST be treated as unsupported by a relay. Header types are registered in the IANA table 'MOQ Extension Headers'. See {{iana}}.

2025-02-06 12:03 UTC, wilaw commented on draft-ietf-moq-transport.md
> +An Object Extension is a concatenation of optional Extension Headers. These
This text was replaced along with the processing rules. 

> Object Extensions : A sequence of Object Extension Headers. See {{object-extensions}} below.

> Object Extension Headers are visible to relays and allow the transmission of future metadata relevant to MOQT Object distribution. Extension Headers MUST NOT carry metadata bound to the Object payload. Such metadata should instead be serialized into the payload.

2025-02-06 12:05 UTC, wilaw commented on draft-ietf-moq-transport.md
> +MUST NOT be modified by relays. The purpose of Extension Headers is to
Following the interim, we added new processing rules for relays and removed negotiation during setup.

2025-02-06 12:06 UTC, wilaw commented on draft-ietf-moq-transport.md
> +allow the transmission of application-specific data as well as future
Language changed to 

> Object Extension Headers are visible to relays and allow the transmission of future metadata relevant to MOQT Object distribution. Extension Headers MUST NOT carry metadata bound to the Object payload. Such metadata should instead be serialized into the payload.
> 
> Extension Headers are defined in external specifications and registered in an IANA table {{iana}}. These specifications define the type and value of the header, along with any rules concerning processing, modification, caching and forwarding. A relay which is coded to implement these rules is said to "support" the extension.
> 
> If unsupported by the relay, Extension Headers MUST NOT be modified, MUST be cached as part of the Object and MUST be forwarded by relays
> 
> If supported by the relay and subject to the processing rules specified in the definition of the extension, Extension Headers MAY be modified, MAY be cached and MAY be forwarded.

2025-02-06 12:07 UTC, wilaw commented on draft-ietf-moq-transport.md
> +evolution of the transport protocol. Object Extensions are serialized as
I went with 

> Object Extension Headers are visible to relays and allow the transmission of future metadata relevant to MOQT Object distribution.

2025-02-06 12:35 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  Extension Count (i),
We can merge with the 1byte for now, but then I have opened a new issue #666  to capture this and other proposals for bit-packing the extension count.

2025-02-06 12:36 UTC, wilaw commented on draft-ietf-moq-transport.md
> +Headers is to facilitate the future evolution of the transport protocol.
I removed that sentence with latest commit.

2025-02-06 12:37 UTC, wilaw commented on draft-ietf-moq-transport.md
> +requested extensions, then it MUST respond with a parameter value length of 0.
We have now removed negotiation entirely.

2025-02-06 12:37 UTC, wilaw commented on draft-ietf-moq-transport.md
> +The REQUESTED-EXTENSION parameter (key 0x03) allows the client to request
Agreed. Negotiation has been removed with latest commit.

2025-02-06 12:40 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  0x00 - 0x20 inclusive are followed by a single varint encoded value. Header
Based on yesterday's interim discussion, I modified the serialization to use the even|varint, odd|TLV scheme. 

> Header values: even types are followed by a single varint encoded value. Odd types are followed by a varint encoded length and then the header value. Every integer multiple of 17 or 18 is a reserved greasing value. These types MUST be treated as unsupported by a relay. Header types are registered in the IANA table 'MOQ Extension Headers'. See {{iana}}.

In a future edit, if parameters also adopt the even/odd scheme, then we can update Extensions to refer to the parameters serialization.

2025-02-06 12:41 UTC, wilaw commented on draft-ietf-moq-transport.md
> +forwarded and SHOULD NOT be modified by relays. The purpose of Extension
We now say

> Extension Headers are defined in external specifications and registered in an IANA table {{iana}}. These specifications define the type and value of the header, along with any rules concerning processing, modification, caching and forwarding. A relay which is coded to implement these rules is said to "support" the extension.
> 
> If unsupported by the relay, Extension Headers MUST NOT be modified, MUST be cached as part of the Object and MUST be forwarded by relays
> 
> If supported by the relay and subject to the processing rules specified in the definition of the extension, Extension Headers MAY be modified, MAY be cached and MAY be forwarded.

2025-02-06 12:42 UTC, wilaw commented on draft-ietf-moq-transport.md
> +Object Extension Headers are visible to relays. Extension Headers SHOULD be
Relays can now modify extensions which they "support". 

> Extension Headers are defined in external specifications and registered in an IANA table {{iana}}. These specifications define the type and value of the header, along with any rules concerning processing, modification, caching and forwarding. A relay which is coded to implement these rules is said to "support" the extension.
> 
> If supported by the relay and subject to the processing rules specified in the definition of the extension, Extension Headers MAY be modified, MAY be cached and MAY be forwarded.

2025-02-06 19:11 UTC, fluffy requested changes
Most my stuff is just comments that could be ignored but on the topic of can this be used for for meta data about stuff in payload, I feel very strongly we don't have consensus to merge this with MUST NOT. I thought the consensus from call was this was allowed. 

Other than that one point, looks great and thanks Will for fast turn around on thisl

2025-02-07 19:13 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  every integer multiple of 17 or 18 is a reserved greasing value and MUST
I agree that I'd prefer to do greasing of everything in a separate PR, and I don't think we have to use any of the 1 byte codepoints.  Those are the ones I'm pretty sure will work.

2025-02-08 01:30 UTC, ianswett reviewed
Thanks for the fast update.  I made a suggestion for text on extension headers and Object metadata and I agree with Cullen that I'd rather do greasing of everything in a separate PR.

2025-02-08 01:30 UTC, ianswett commented on draft-ietf-moq-transport.md
> +  Every integer multiple of 17 or 18 is a reserved greasing value. These types
I think in the Wednesday virtual interim we decided to do greasing as a separate PR?

2025-02-08 10:27 UTC, wilaw commented on draft-ietf-moq-transport.md
> +carry metadata bound to the Object payload. Such metadata should instead
Modified text as suggested with commit https://github.com/moq-wg/moq-transport/pull/502/commits/10298c40d680d350282d4ad699f1b992034461f3

2025-02-08 10:28 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  every integer multiple of 17 or 18 is a reserved greasing value and MUST
Removed greasing with https://github.com/moq-wg/moq-transport/pull/502/commits/10298c40d680d350282d4ad699f1b992034461f3

2025-02-08 10:28 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  Every integer multiple of 17 or 18 is a reserved greasing value. These types
Removed greasing with https://github.com/moq-wg/moq-transport/pull/502/commits/10298c40d680d350282d4ad699f1b992034461f3

2025-02-08 10:31 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  standards utilization where space is a premium, 128 - 16383 for
Isn't 1 byte max 127 ?

> 1 Byte (7 bits for data)
> Largest decimal integer: 127
> 
> 2 Bytes (14 bits for data)
> Largest decimal integer: 16,383
> 
> 3 Bytes (21 bits for data)
> Largest decimal integer: 2,097,151

2025-02-08 10:33 UTC, wilaw commented
Commit https://github.com/moq-wg/moq-transport/pull/502/commits/10298c40d680d350282d4ad699f1b992034461f3 addressed the open rerquests of @fluffy and @ianswett .

2025-02-08 16:13 UTC, afrind reviewed
Individual Review: lgtm.  I see we don't have any language about how relays treat receipt of the same object with different extensions.  I'm ok leaving that out here, and clarifying in a follow up too.

2025-02-08 16:13 UTC, afrind commented on draft-ietf-moq-transport.md
> +an extension header.
minor: s/part of the Object/part of the Object payload/

I can live with SHOULD here; perhaps RECOMMENDED is also ok?  My reasoning is that if the transport will never look at the extension, it shouldn't waste any time parsing out the fields.  However, as Suhas pointed out, it's unenforceable, and a relay cannot distinguish between an unsupported extension and payload.

2025-02-08 18:45 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  standards utilization where space is a premium, 128 - 16383 for
@wilaw - I think that MoQ should be changed to work the way you think it works (see https://github.com/moq-wg/moq-transport/issues/549)  but it does not

Right now the encoding is defined in section 16 of RFC 9000
https://www.rfc-editor.org/rfc/rfc9000#section-16

And for 1 byte, you only get 6 bits of data not 7.

2025-02-08 19:12 UTC, fluffy requested changes

2025-02-08 19:12 UTC, fluffy commented on draft-ietf-moq-transport.md
> +an extension header.
The problem with serializing in the object is that the object will be end to end encrypted in many cases and thus the rely can not read it. Take the example of capture timestamp for media. Relay can look at this timestamp to figure out how much lag. Then  metrics dashboard can take differences of lag to figure out the latency between two relays. This type of operational information is supper useful on running real systems. SRTP which we are trying to replace with MoQ is explicitly designed to keep that type of timing information in the readable hops along the media path. I feel very strongly we need the same sort of thing here. 

We could introduce two types of option , relay options, and client options so that the relay did not need to parse the client options. Or another design could be to introduce object headers that were not end to end encrypted.  But all of these options end up using another byte even if there are no headers and that is a big impact for audio only applications. 

I don't buy the parsing time problem. Anything reasonable relay is going to be able to parse to the level to check if it is interested in any of the extensions on single core at a rate that greatly exceeds whatever networking technology it uses and probably exceeds the bandwidth to non cached memory so you can probably parse this as fast as you can memcpy it. Either way, I just don't see any performance problem. 

I could live with this saying 

"Any metadata which will not be read or logged by any relay ever including use for operational or diagnostic reasons, 
 SHOULD NOT be sent in an extension header."

2025-02-10 03:09 UTC, afrind commented on draft-ietf-moq-transport.md
> +an extension header.
Individual Comment:

Let me start at the end, because I think we agree:

> "Any metadata which will not be read or logged by any relay ever including use for operational or diagnostic reasons, SHOULD NOT be sent in an extension header."

This is what I was trying to express.

The current text is:

> Any Object metadata not used by the transport SHOULD be serialized as part of the Object and not as an extension header.

Maybe just amending it to 

> Any Object metadata _never accessed_ by the transport _or relays_ SHOULD be serialized as part of the Object payload and not as an extension header.

?

2025-02-10 18:37 UTC, ianswett approved these changes
This LG, but I don't think we should remove the "Extension Negotiation" text towards the beginning of the document, because that's different from extension headers.

2025-02-10 18:37 UTC, ianswett commented on draft-ietf-moq-transport.md
> -## Version and Extension Negotiation {#version-negotiation}
I don't think we want to remove this text yet.  There could be extensions that aren't extension headers we may want to negotiate?

2025-02-10 19:08 UTC, wilaw commented on draft-ietf-moq-transport.md
> +an extension header.
I'm ok with below text in the interests of advancing the spec. perhaps @ianswett can edit when merging or do you want me to make another commit?

> Any Object metadata never accessed by the transport or relays SHOULD be serialized as part of the Object payload and not as an extension header.

At Denver interim, I'd like to debate the use case where we add timing data to extensions. While it appears useful, it binds the protocol to the payload, which I ardently believe we should strive to avoid. Media flows will want timestamps, gaming systems will want 3D coordinates, vehicle tracking systems will wants GPS coordinates etc. Do we add all of these use cases to the core transport, or do we try to architect a more generic "index" which can be exposed to relays and provide similar utility without the payload binding?

2025-02-10 20:08 UTC, ianswett commented on draft-ietf-moq-transport.md
> +an extension header.
```suggestion
future metadata relevant to MOQT Object distribution. Any Object metadata never accessed by the transport or relays SHOULD be serialized as part of the Object
payload and not as an extension header.
```

2025-02-11 01:41 UTC, ianswett commented on draft-ietf-moq-transport.md
> -## Version and Extension Negotiation {#version-negotiation}
I agree with your intuition, but I'd like to minimize the size of this change, so I'm going to leave this text for now.

2025-02-11 01:42 UTC, ianswett commented on draft-ietf-moq-transport.md
> +## Version Negotiation and Extension Negotiation {#version-negotiation}
```suggestion
## Version and Extension Negotiation {#version-negotiation}
```

2025-02-11 01:46 UTC, ianswett commented on draft-ietf-moq-transport.md
> +future metadata relevant to MOQT Object distribution. Any Object metadata never accessed by the transport or relays SHOULD be serialized as part of the Object
```suggestion
future metadata relevant to MOQT Object distribution. Any Object metadata never
accessed by the transport or relays SHOULD be serialized as part of the Object
```

2025-02-11 02:27 UTC, afrind approved these changes

2025-02-11 03:04 UTC, merged