Remove track per stream
moq-wg/moq-transport pull request #516
Opened 2024-08-29 22:34 UTC by ianswett

And allow implementations to send multiple Peeps sequentially on a single stream if they want.

Fixes #480
May fix #490
May fix #476

2024-08-30 14:50 UTC, kixelated commented
IMO multiple peeps per stream is even worse than a stream per track. You inherit all of the problems (priorities, head-of-line blocking, inability to reset) but now it's implicit rather than explicit.

Even worse, the text doesn't require that peeps share the same track/subscription.

I don't think MAX_STREAMS is an issue worth degrading the protocol. Make implementations raise the limit rather than impose unnecessary HoLB.

So IMO just delete a track per stream and offer no replacement. Make a stream for each group, and if you're blocked by MAX_STREAMS before MAX_DATA then the limit needs to be raised.

2024-08-30 17:16 UTC, suhasHere commented
I think we just landed a PR saying a PEEP == Stream. I am bit confused on the wording of multiple peeps per stream. 
Also I am not too sure removing stream per track solves some of the issues raised and they do exist regardless. Some are fetch related and some as Luke pointed out are on the point.

I am not saying we definitely need Stream per Track or not, but I think it has its use. However I tend to disagree that it makes implementation complicated.

2024-08-31 19:52 UTC, ianswett commented
> IMO multiple peeps per stream is even worse than a stream per track. You inherit all of the problems (priorities, head-of-line blocking, inability to reset) but now it's implicit rather than explicit.

The intent is that you'd only use this when it's beneficial.

> 
> Even worse, the text doesn't require that peeps share the same track/subscription.

I clarified that, but the intent was always that they're Peeps from the same subscription.
> 
> I don't think MAX_STREAMS is an issue worth degrading the protocol. Make implementations raise the limit rather than impose unnecessary HoLB.

I'm a lot less concerned about MAX_STREAMS and more concerned about memory usage and buffering when a subscriber requests a large amount of Data/Objects from the past (aka Fetch) and there is a real need for backpressure/flow control of some sort.  Inventing a new mechanism in MoQ to do that is complex, but caching HTTP proxies deal with this today quite well for large requests. 

> 
> So IMO just delete a track per stream and offer no replacement. Make a stream for each group, and if you're blocked by MAX_STREAMS before MAX_DATA then the limit needs to be raised.

I'm fine with just deleting track per stream as well, and we can limit this PR to only that if people prefer.

2024-09-03 13:34 UTC, vasilvv commented
I'm not sure falling back from multi-stream to single-stream is a good idea: there is no good reason for the server to have large per-stream buffers but small total limit on streams, so I think the preferred approach here would be to buffer outgoing peeps until the credits appears.

Otherwise this looks good, though you might need to remove Track as a forwarding preference from other places in the spec.

2024-09-03 14:53 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +Multiple Peeps from a single subscription MAY be sent on the same stream if a
This conflicts with the current definition of Peeps.

2024-09-03 15:08 UTC, vasilvv commented
Another problem is that if we ever assign semantics to closing a peep via a FIN, or require resetting a stream upon certain events (e.g. timeouts), "multiple peeps in a single stream" completely breaks that.

2024-09-03 16:45 UTC, kixelated commented
I definitely don't want a relay converting N streams into 1 stream by coalescing peeps, introducing HoLB in the process. The reverse is probably fine but it's still extremely situational; the broadcaster is trying to send more concurrent peeps than the QUIC connection allows?

But in general this just seems extremely fishy. We're worried about too many streams so we invent our own stream within a stream abstraction. Use fewer peeps or raise MAX_STREAMS.

2024-09-09 01:30 UTC, suhasHere commented
I am proposing to hold off merging this PR until fetch discussions are complete. Since the issues are related to flow control/range requests and  not specific to  forwarding mode preference. 
Having said that I am not in favor or against the stream-per-track mode, but hoping we come to a decision once we have spent some time figuring out range requests in general.

2024-09-13 11:21 UTC, fluffy requested changes
There is a bunch of stuff in here about peeps that I don't think works.

2024-09-13 11:21 UTC, fluffy commented on draft-ietf-moq-transport.md
The following paragraph seem about peeps not removing stream per track so I think it should be in a seperate PR.

2024-09-13 11:21 UTC, fluffy commented on draft-ietf-moq-transport.md
> +Multiple Peeps from a single subscription MAY be sent on the same stream if a
I do't think we should allow multiple peeps over the sam stream.  It is a fringe case that will not happen most the time and will not be tested. It will be hard to test and many receivers will fail when it happens. It will get very complicated to decide how to prioritize things. It will mean we need to communicate the information in each object instead of just the stream header.

If a publisher runs out of streams its needs to close the subscription with some sort of not enough streams error.

2024-09-13 11:21 UTC, fluffy commented on draft-ietf-moq-transport.md
> +control is valuable. This can happen when a subscriber requests a range of
I think this is just a good example to show why FETCH should go over a single stream even if it has many groups and peeps worth of data.

2024-09-13 11:21 UTC, fluffy commented on draft-ietf-moq-transport.md
> +or other resource limits. For a given Group ID, the Peep ID MUST increase with
I don't think requiring this to increment will work. Even if the original publisher sent things in order of 1,2,3 an prioritization at an intermediate relay could result in things being sent in the order 1,3,2 so from the downstream point of view things are not in order.

2024-09-13 11:21 UTC, fluffy commented on draft-ietf-moq-transport.md
> +Group Order requested by the subscriber.
with remove of stream per track I don't think you can have more than one group in a stream so I am not following this. If this is for multiple groups in a single stream then does the the relay have to buffer all future groups waiting for the last object in the first group.

2024-09-26 03:17 UTC, ianswett commented
I think we'll end up removing track per stream, but let's do so after we resolve the conversation about Fetch.

2024-10-18 02:19 UTC, merged