Clarify subscribe / annouce interaction
moq-wg/moq-transport pull request #525
Opened 2024-09-13 01:05 UTC by fluffy

Fixes #362 #267 #227 #225 #79

2024-09-13 17:14 UTC, afrind reviewed
Individual Review

This is really helpful clarification as I didn't necessarily think it had to work this way.

You have a number of random typos etc but just giving high-level feedback.

2024-09-13 17:14 UTC, afrind commented on draft-ietf-moq-transport.md
> +  agreement).
We should offer a default behavior, like 

> relays MAY have pre-negotiated mechanisms of handling authorization on behalf of publishers.  In the absence of such mechanisms, relays MUST forward SUBSCRIBE requests containing non-empty Auth Info parameters to the original publisher.

2024-09-13 17:14 UTC, afrind commented on draft-ietf-moq-transport.md
> +from a single publisher for a given tracknamespace.
Can relays limit the number of publishers for a given namespace?  It seems like for DoS reasons they can.  Maybe we should specify a minimum: "Relays MUST support at least X publishers announcing the same namespace"

2024-09-13 17:14 UTC, afrind commented on draft-ietf-moq-transport.md
> +to that publisher for the full track name in the incoming SUBSCRIBE.
What about cases where the relay can fill from cache?

2024-09-13 17:14 UTC, afrind commented on draft-ietf-moq-transport.md
> +object ID, in its cache.
Caching and non-caching relays also need to drop (rather than forward) duplicate objects, right?

```
Pub A ---+
         +---> Relay ---> Sub
Pub B ---+
```

I think relays can figure out the best algorithms to do this, we just need to say that the subscriber only receives one copy.

Might want to add an example of why this is useful (graceful failover, redundant publishers, etc)

2024-09-14 15:12 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  agreement).
I don't think CDNs are going forward any traffic unless it is both clear who is paying for it and who is responsible for it from a DDoS point of view. We definitely need to get a better handle on that as part of the overall all issue. Glad to remove this sentence if that makes it better but just to talk about it a bit. It seems that if the CDN can look at the track name and say, yep, this is one that I bill for either by policy of by an authenticated annouce for that trackname, then it will likely forward, but if just gets a request for some random track name from some random users, seems very unlikely that it would forward that. 

At the other end of the spectrum from CDNs, a relay running in my home AP gets a a request from the local WAN side it make make complete sense for it to forward that.

2024-09-14 15:15 UTC, fluffy commented on draft-ietf-moq-transport.md
> +from a single publisher for a given tracknamespace.
well ... I suspect this is going to fall in policy for relays region. Lets say you have 10 million viewers of a Taylor Swift livestream that can all publish text comments to various chat tracks. You OK with the number of max publishers on the same namespace being in the millions ?  It seems that different relays will want very different limits here.

2024-09-14 15:17 UTC, fluffy commented on draft-ietf-moq-transport.md
> +to that publisher for the full track name in the incoming SUBSCRIBE.
You mean a fetch of things that are all in the cache ? In this case definitely no subscription needed at all but I assumed that would be handled by the whatever PR eventually deals with fetch.

2024-09-14 15:31 UTC, fluffy commented on draft-ietf-moq-transport.md
> +object ID, in its cache.
Lets say we had just one publisher, one high available relay, and one subscriber. I don't know how to make an HA Relay that will guarantee to never deliver the same object exactly once even during failures with any reasonable QUIC stack I have today. I think subscribers are going to have to deal with rare events. I don't think we can ask non caching relays to keep track of ever object they have forwarded to stop duplicates. 

What we certainly can do is make sure that most duplicates could be suppress particularly if the duplicated happened within the MAX_CACHE_DURATION for the object. 

I'm pretty on the fence on what to say about non caching relay. The problem really comes down to how much storage space they will use for this ( for both caching and non caching ). Clearly at some point they will free up storage and an that point any MUST is probably going to fail in some cases.   If we proposed the relay MUST cache this for at least MAX_CACHE_DURATION, I am pretty sure CDN implementers will tell us they are not going to do that 100% of the time and it should be a SHOULD. 

This is a long rambling way to get to, yah, you are right. I should have something more here. But I am thinking it will be a SHOULD level recommendation. That work for you ?

2024-09-14 15:32 UTC, fluffy commented
> Individual Review
> 
> This is really helpful clarification as I didn't necessarily think it had to work this way.
> 
> You have a number of random typos etc but just giving high-level feedback.

Many thanks on review and any help of fixing all the small stuff (point me too it, or PR on the PR, anything) much appreciated.

2024-09-14 20:33 UTC, afrind reviewed
Individual Comments

2024-09-14 20:33 UTC, afrind commented on draft-ietf-moq-transport.md
> +object ID, in its cache.
I think a SHOULD will probably work?  Keeping state of everything sent to every client is not scalable, but in some common cases it should be pretty easy (eg within a peep, if you see the same object ID or it goes backwards from the most recent, just drop it).  Implementation experience will help us see what's possible.

I'm thinking of a make-befrore-break case, during the point when the publisher has 2 connections to the relay, it would be nice if the relay is deduplicating as much as it can as it forwards.

2024-09-14 20:33 UTC, afrind commented on draft-ietf-moq-transport.md
> +  agreement).
My concern is that without a normative default for what to do, there's very little interoperability.  The only other normative behavior I can think of is "MUST reject any subscribe with authorization info", but that seems less functional.

I 100% agree that CDNs are going to have policies and such that govern this and we should acknowledge that, but it should also work "out of the box".

We will likely revisit some of this when we tackle auth in more detail too.

2024-09-14 20:33 UTC, afrind commented on draft-ietf-moq-transport.md
> +from a single publisher for a given tracknamespace.
I was hoping SUBSCRIBE_NAMESPACE would solve some of that problem -- all 10M viewers have their own namespace `tswift/chat/unique_id`.  We may need to indicate here what limits are likely to exist, because it influences how higher level protocols will use moqt in terms of namespace and track naming.

Agreed the max will be different, but is there a min that we need to specify to get basic interop, eg: for make-before-break, min=2.

2024-09-14 20:33 UTC, afrind commented on draft-ietf-moq-transport.md
> +to that publisher for the full track name in the incoming SUBSCRIBE.
I mean, 2 publishers have announced track T, and published some objects into the cache.  A subscriber issue a subscribe for track T but whatever is specified as the start and/or end is already in cache - there's no need to forward subscribe.  Maybe you can reword this to say - if you would send a subscribe to pub 1, you MUST send it to all N.

2024-09-16 17:32 UTC, wilaw commented on draft-ietf-moq-transport.md
> +object ID, in its cache.
Rather than drop the later arriving object, I would rather that it overwrite the item existing in cache (i.e latest wins). This allows updating caches and purging corrupt content by overwriting. If we go with the proposal that the original write always wins, then we have no method for publishers to flush content from upstream caches other than waiting for its cache duration to expire.

2024-09-16 17:36 UTC, wilaw commented on draft-ietf-moq-transport.md
> +  agreement).
In the absence of such mechanisms, relays MUST forward SUBSCRIBE requests containing non-empty Auth Info parameters to the original publisher.

How is that expected to work if a thousand clients make the same subscription with different auth info to an edge? Normally we would want the edge to coalesce these requests and make a single upstream subscription. But it would now have to make 1000 upstream subscriptions? I don't think that is practical. I think Cullen's proposed text is fine.

2024-09-16 18:33 UTC, afrind commented on draft-ietf-moq-transport.md
> +  agreement).
> How is that expected to work if a thousand clients make the same subscription with different auth info to an edge?
 
 I see three possibilities:
 
 1.  pre-negotiated scheme for relay to perform auth
 2. forward the auth credentials to OP for validation 
 3. subscribe error (no way to auth)
 
If we dig into 2, right now, only SUBSCRIBE carries the auth field, so you'd end up blowing up your coalescing, unless you UNSUBSCRIBE duplicates immediately I guess.  An alternate would be to add a new message like AUTH which would perform the auth at the OP but not initiate the actual subscription.   This retains the coalescing while also providing a way for generic relays to do auth.  Maybe we can defer this to a later PR.

2024-09-16 22:31 UTC, ianswett reviewed
This looks great, and clarifies a lot about how one might use ANNOUNCE.  I have one normative comment, which is that I think some of the MUSTs should be a SHOULD.

2024-09-18 16:10 UTC, suhasHere approved these changes
This clarifies lot of ambiguities on implementing make before break use-cases.
LGTM

2024-09-18 16:29 UTC, martinduke requested changes

2024-09-18 16:29 UTC, martinduke commented on draft-ietf-moq-transport.md
> +subscription with a SUBSCRIBE_DONE (see {{message-subscribe-done}}). A
or UNSUBSCRIBE? Or is there a SUBSCRIBE_DONE in reply?

2024-09-18 16:29 UTC, martinduke commented on draft-ietf-moq-transport.md
> +The annouce allows the relays to know which publisher to forward a
```suggestion
The announce allows the relays to know which publisher to forward a
```

2024-09-18 16:29 UTC, martinduke commented on draft-ietf-moq-transport.md
> +SUBSCRIBE to that publisher unless it already has an active subscription
Unless the entire range is already cached?

2024-09-18 16:29 UTC, martinduke commented on draft-ietf-moq-transport.md
> +SUBSCRIBE to that publisher that send the ANNOUCE.
```suggestion
SUBSCRIBE to that publisher that send the ANNOUNCE.
```

2024-09-18 16:29 UTC, martinduke commented on draft-ietf-moq-transport.md
> +each publisher that has announced that namespace, the relay MUST send a
+1

2024-09-18 16:40 UTC, fluffy commented on draft-ietf-moq-transport.md
> +  agreement).
Going to leave the auth stuff for a later work on auth for the whole draft

2024-09-18 17:33 UTC, fluffy commented on draft-ietf-moq-transport.md
> +SUBSCRIBE to that publisher unless it already has an active subscription
yah .... let me see what to put here. A bunch of this changes depending on how subscribe is also fetch or if they are separate.

2024-09-18 18:27 UTC, fluffy commented on draft-ietf-moq-transport.md
> +SUBSCRIBE to that publisher unless it already has an active subscription
I think the text now deals with that

2024-09-18 18:37 UTC, fluffy commented on draft-ietf-moq-transport.md
> +subscription with a SUBSCRIBE_DONE (see {{message-subscribe-done}}). A
I'm adding "or all the downstream subscriptions are ended". I started with just SUBSCRIBE_DONE  but there are also all the timeout and connection close things that can end a subscription. The draft overall is a bit light on all the clean up and timeouts of things and I can't fix that in this PR.

2024-09-18 18:42 UTC, fluffy commented on draft-ietf-moq-transport.md
>  namespace it previously responded ANNOUNCE_OK to by sending an
I've got no idea :-) We need an error to ANNOUNCE for auth errors, so it makes sense to have an OK just to know there was no error. But I have no idea why we need CANCEL

2024-09-18 18:43 UTC, fluffy commented on draft-ietf-moq-transport.md
> +to that publisher for the full track name in the incoming SUBSCRIBE.
I like that - added in as you sugesteed.

2024-09-18 18:45 UTC, fluffy commented
@martinduke - thanks for review. I think I fixed all the stuff you raised. Can you take another look 

@ianswett - handing the baton to you on this one. Thanks you

2024-09-18 19:40 UTC, martinduke commented on draft-ietf-moq-transport.md
> +or all the downstream subscriptions are ended. A
The "publisher" is a term local to the session, unless you mean "original publisher." So a subscription ends when the publisher sends SUBSCRIBE_DONE or when the subscriber sends UNSUBSCRIBE. Downstream subscriptions don't enter into it.

2024-09-18 19:40 UTC, martinduke commented on draft-ietf-moq-transport.md
> +When a subscriber receives the GOAWAY message, it starts of the process
```suggestion
When a subscriber receives the GOAWAY message, it starts the process
```

2024-09-18 19:40 UTC, martinduke commented on draft-ietf-moq-transport.md
> +publishers, in the same way as it would responds when processing ANNOUNCE
```suggestion
publishers, in the same way as it would respond when processing ANNOUNCE
```

2024-09-18 19:40 UTC, martinduke commented on draft-ietf-moq-transport.md
> +publishers, in the same way as it would responds when processing ANNOUNCE
alternately, "it responds"

2024-09-18 19:40 UTC, martinduke commented on draft-ietf-moq-transport.md
> +to that publisher for the Full Track Name in the incoming SUBSCRIBE.
s/for the Full Track Name/for the objects in the specified range

2024-09-18 19:40 UTC, martinduke commented on draft-ietf-moq-transport.md
> +SUBSCRIBE to that publisher that send the ANNOUNCE.
I think this means that if there is an ANNOUNCE for a track where a relay has N incoming subscriptions, it should send N SUBSCRIBEs. That seems to negate the whole purpose of relays?

I hope you actually mean the relay should send *one* SUBSCRIBE assuming the ranges are the same. If not, we are not on the same page at all.

2024-09-18 22:06 UTC, afrind commented on draft-ietf-moq-transport.md
> +SUBSCRIBE to that publisher unless it already has an active subscription
meta.ai suggests:

When a relay receives an incoming SUBSCRIBE request for a given namespace that would trigger an upstream subscription, it SHOULD send a SUBSCRIBE request to each publisher that has announced that namespace, unless it already has an active subscription to that publisher for the Full Track Name specified in the incoming SUBSCRIBE request.

2024-09-18 22:06 UTC, afrind commented on draft-ietf-moq-transport.md
> +SUBSCRIBE to that publisher that send the ANNOUNCE.
Maybe "each active *upstream* subscription" would help clarify?  

I think some of this language will need a second pass once we sort fetch and ranges.

2024-09-18 22:23 UTC, ianswett commented on draft-ietf-moq-transport.md
> +each active subscription that matches that namespace, it SHOULD send a
```suggestion
each active upstream subscription that matches that namespace, it SHOULD send a
```

2024-09-18 22:23 UTC, ianswett commented on draft-ietf-moq-transport.md
> +SUBSCRIBE to that publisher that send the ANNOUNCE.
I added upstream.

2024-09-18 22:30 UTC, ianswett approved these changes

2024-09-19 00:11 UTC, suhasHere commented on draft-ietf-moq-transport.md
>  namespace it previously responded ANNOUNCE_OK to by sending an
ANNOUNCE_CANCEL  is used in the below flow IIYC

```mermaid
sequenceDiagram
    Publisher->>Relay(Subscriber): Announce
    Relay(Subscriber)->>Publisher: Announce Ok
    Relay(Subscriber)->>Publisher: Subscribe
    Publisher->>Relay(Subscriber): Subscribe OK
    Publisher->Relay(Subscriber): Objects Flow
    Note right of Relay(Subscriber):  Relays is unable to support new subscriptions 
    Relay(Subscriber)->>Publisher: Announce Cancel 
```

Existing subscriptions will still get served, but new subscriptions will not be sent to the publisher anymore.

2024-09-19 00:48 UTC, fluffy commented on draft-ietf-moq-transport.md
> +SUBSCRIBE to that publisher that send the ANNOUNCE.
Thanks - yes, upstream

2024-09-20 01:59 UTC, merged