Do something useful with SUBSCRIBE_DONE
moq-wg/moq-transport pull request #609
Opened 2024-11-07 21:21 UTC by martinduke

Fixes #424, #456, #465.

Comes up with some rules on when to send SUBSCRIBE_DONE, and what to do with it.

Deletes the ContentExists and Final Group/Object fields, because there is nothing the receiver does with it.

2024-11-07 21:23 UTC, martinduke commented
Note: Another design would not use a timer at the receiver. Instead, it would require that all reset streams use RESET_STREAM_AT with at least the track alias delivered reliably, and the SUBSCRIBE_DONE would indicate how many streams were opened over the life of the subscription.

2024-11-07 22:26 UTC, afrind reviewed
Individual Review:

I can live with using a timer, but I prefer putting an opened stream count in SUBSCRIBE_DONE and requiring any reset streams to use RELIABLE_RESET_STREAM with an offset >= the stream header.

2024-11-07 22:26 UTC, afrind commented on draft-ietf-moq-transport.md
> +additional streams for a subscription. When all streams for the subscription are
Or send additional datagrams

2024-11-07 22:26 UTC, afrind commented on draft-ietf-moq-transport.md
> +ever open for a subscription. After sending SUBSCRIBE_DONE, MoQT can immediately
s/MoQT/a sender (or publisher?)/

2024-11-07 22:26 UTC, afrind commented on draft-ietf-moq-transport.md
> +closing of the stream on the wire.
```suggestion
destroy subscription state, even though the underlying transport might not have 
finished closing the associated streams.
```

2024-11-07 22:26 UTC, afrind commented on draft-ietf-moq-transport.md
> +closing of the stream on the wire.
Also do we need to say something about datagrams?

2024-11-07 22:26 UTC, afrind commented on draft-ietf-moq-transport.md
> +in case some unopened streams are still inbound due to prioritization or packet
streams or datagrams

2024-11-07 22:42 UTC, afrind commented on draft-ietf-moq-transport.md
> +A receiver that receives SUBSCRIBE_DONE SHOULD set a timer of at least 2 seconds
Should there be an exception if the SUBSCRIBE_DONE has code UNSUBSCRIBED (eg: the subscriber already expressed disinterest)?

2024-11-08 15:06 UTC, martinduke commented on draft-ietf-moq-transport.md
> +additional streams for a subscription. When all streams for the subscription are
Done. #downwithdatagrams

2024-11-08 15:09 UTC, martinduke commented on draft-ietf-moq-transport.md
> +A receiver that receives SUBSCRIBE_DONE SHOULD set a timer of at least 2 seconds
As the text says, the receiver MAY delete early if the application has lost interest in the data.

I don't think we need special language for that.

2024-11-10 17:09 UTC, ianswett reviewed
Overall looks good, but I'm curious why you removed the Final Group and Final Object?

2024-11-10 17:09 UTC, ianswett commented on draft-ietf-moq-transport.md
> +ever open, and has no pending datagrams, for a subscription. After sending
```suggestion
ever open, and has no unsent datagrams, for a subscription. After sending
```

2024-11-10 17:09 UTC, ianswett commented on draft-ietf-moq-transport.md
> +SUBSCRIBE_DONE, the sender  can immediately destroy subscription state, although
```suggestion
SUBSCRIBE_DONE, the sender can immediately destroy subscription state, although
```

2024-11-10 17:09 UTC, ianswett commented on draft-ietf-moq-transport.md
> +A receiver that receives SUBSCRIBE_DONE SHOULD set a timer of at least 2 seconds
```suggestion
A subscriber that receives SUBSCRIBE_DONE SHOULD set a timer of at least 2 seconds
```

2024-11-10 17:09 UTC, ianswett commented on draft-ietf-moq-transport.md
> +A receiver that receives SUBSCRIBE_DONE SHOULD set a timer of at least 2 seconds
2 seconds seems arbitrary.  Can we use 3 * PTO or leave it open to implementations?

2024-11-10 17:09 UTC, ianswett commented on draft-ietf-moq-transport.md
> +delivering some late objects to the application.
```suggestion
subscription state once all open streams for the subscription have closed. A
subscriber MAY discard subscription state earlier, at the cost of potentially not
delivering some late objects to the application.
```

2024-11-10 17:09 UTC, ianswett commented on draft-ietf-moq-transport.md
> -  [Final Object (i)],
Was this removed because it was difficult, or because you think it's useless or ?

2024-11-10 20:20 UTC, ianswett approved these changes

2024-11-10 20:20 UTC, ianswett requested changes
Oops, I forgot I would like to change the 2 second constant before merging this.

2024-11-11 00:41 UTC, martinduke commented on draft-ietf-moq-transport.md
> +A receiver that receives SUBSCRIBE_DONE SHOULD set a timer of at least 2 seconds
It is totally arbitrary. The MoQ application is unlikely to have an API for the PTO, but there's no number I'd be unhappy with.

2024-11-11 00:42 UTC, martinduke commented on draft-ietf-moq-transport.md
> +ever open, and has no pending datagrams, for a subscription. After sending
IIUC Datagrams can't be pending at the application level. If QUIC can't take them, they just drop on the floor?

2024-11-11 00:43 UTC, martinduke commented on draft-ietf-moq-transport.md
> -  [Final Object (i)],
As the description above says, I couldn't think of anything the receiver could do with it. This also clears the issue about if it's the final object of the track or the subscription.

2024-11-11 00:45 UTC, martinduke commented
I thought of a third way this could work:

If we got WebTransport APIs to expose the QUIC Stream ID of a stream, we could include the largest stream ID opened on behalf of a subscription. If all unidirectional sender-opened streams up to that ID have been observed, it's safe to destroy the state.

2024-11-11 17:16 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +streams for the subscription are fully closed, each endpoint can destroy its
by the phrase "fully closed" , do you mean stream fin or does it cover stream reset cases too ?

2024-11-11 17:17 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +Note that some objects in the subscribed groups might never be delivered,
s/subscribed groups/subscribed tracks

2024-11-11 17:19 UTC, suhasHere commented on draft-ietf-moq-transport.md
> +subscription state once all open streams for the subscription have closed. A
"Once the timer has expired, the receiver can cleanup its subscription state" 

I don't think we need to have "once al open streams for the subscriptions have closed".

2024-11-11 17:21 UTC, suhasHere commented on draft-ietf-moq-transport.md
> -  [Final Object (i)],
i tend to agree with @martinduke  .. a receiver knows the last object it received before it cleans up its subscription state and adding more info in subscribe_done is not that helpful.

2024-11-11 21:16 UTC, martinduke commented on draft-ietf-moq-transport.md
> +streams for the subscription are fully closed, each endpoint can destroy its
It covers Reset -- I'm not sure how it could work just on FIN

2024-11-12 02:50 UTC, fluffy commented on draft-ietf-moq-transport.md
> +ever open, and has no pending datagrams, for a subscription. After sending
The quicr relay queues datagram packets at the applications layer and only passing them to QUIC layer when there is space in the CWIN for them. This allows the relay to control the times outs and priorities for object sent with datagram. I think that will deliver a much better user experience than something that just drops them on the floor (thought both implementations are valid spec compliant AFAIC )

2024-11-12 03:03 UTC, fluffy requested changes
I don't think this would work.

2024-11-12 03:03 UTC, fluffy commented on draft-ietf-moq-transport.md
> +additional streams or send any more datagrams for a subscription. When all
So lets say I have a track with a single group and single sub group and a million objects in the group. (this might be a common patter for deliver software updates or AI models updates. This new text say the DONE would be sent as soon as the subscribe was received. This seems very wrong and will cause weird race conditions when the DONE was sent after the publisher opened the last stream, but the subscriber got the DONE before they new stream had been opened.

2024-11-12 03:03 UTC, fluffy commented on draft-ietf-moq-transport.md
> +A subscriber that receives SUBSCRIBE_DONE SHOULD set a timer of at least 2 seconds
2 seconds sounds insanely fragile.

2024-11-12 04:09 UTC, martinduke commented on draft-ietf-moq-transport.md
> -  [Final Object (i)],
@fluffy is it your contention that the Final Object field refers to the final object in the track, or the subscription? If the subscription, is it the final one that was delivered, or the final one that was in range (because those are not the same thing).

> I don't see how this works to remove this. If client A does a subscribe of group 10 to 20, will the relay cache that 20 is the end of track ? I just don't see much connection between end of subscription and end of track.

Why would a relay cache an end of track at all in that case? It is perfectly normal for a cache to not know the end of a track.

> I'm even more baffled how, for a group that is not the last group in the track, this allows the client to figure out when it has got all the objects in the group.

Final Object doesn't ensure that. If a stream is never opened by the sender due to delivery timeout, or the track uses DATAGRAM, the receiver has no idea if those Object IDs were dropped or never minted in the first place.

2024-11-12 04:11 UTC, martinduke commented on draft-ietf-moq-transport.md
> +A subscriber that receives SUBSCRIBE_DONE SHOULD set a timer of at least 2 seconds
Would you like to suggest a different timeout, or one of the other proposals discussed in this thread? I'm open to any of them but was reluctant to impose more requirements on the QUIC/WebTransport stack.

2024-11-12 04:15 UTC, martinduke commented on draft-ietf-moq-transport.md
> +additional streams or send any more datagrams for a subscription. When all
That is not what it says at all. A few paragraphs down, it says:

"A sender MUST NOT send SUBSCRIBE_DONE until it has closed all streams it will
ever open, and has no pending datagrams, for a subscription."

Race conditions are inevitable, even with that rule, because we can't guarantee the order in which QUIC will deliver things. That's why there has to be either a timer or a careful accounting of what streams have been opened.

2024-11-12 04:29 UTC, fluffy commented on draft-ietf-moq-transport.md
> -  [Final Object (i)],
Sorry - in the diff I missed you were removing from the subscribe done only not the dataplane. I don't really case what is there

2024-11-12 04:35 UTC, fluffy commented on draft-ietf-moq-transport.md
> +additional streams or send any more datagrams for a subscription. When all
So 

> "A sender MUST NOT send SUBSCRIBE_DONE until it has closed all streams it will
> ever open, and has no pending datagrams, for a subscription."

and 

> "A publisher sends a `SUBSCRIBE_DONE` message to indicate it will not open any
> additional streams or send any more datagrams for a subscription."

Seem to contradict each other about when DONE is sent.

2024-11-12 15:24 UTC, martinduke commented on draft-ietf-moq-transport.md
> +additional streams or send any more datagrams for a subscription. When all
I agree that this is confusing and I'll fix it.

What I'm getting at is this: we don't need a FETCH_DONE because it's all on one stream, so the FIN/RESET is adequate to communicate the end of the FETCH. If the subscriber somehow knew for sure how many streams would open for a SUBSCRIBE, then stream FIN/RESETs would be adequate to know when to destroy subscription state.

SUBSCRIBE_DONE is only needed because it doesn't know for sure; the sender has to tell it that it's done opening streams, so once the current crop of streams is closed it's safe to tear down.

Unfortunately, it is quite likely that SUBSCRIBE_DONE outraces the last stream openings. So either there has to be a timer, or there has to be some indication of how many streams there were (which would levy new requirements on QUIC/WebTransport)

2024-11-12 15:25 UTC, martinduke commented on draft-ietf-moq-transport.md
> +A subscriber that receives SUBSCRIBE_DONE SHOULD set a timer of at least 2 seconds
The effect of the timer expiring early is that some objects may be dropped on the floor instead of delivered to the  application.

If the receiver is interested in objects beyond that, it should set a longer timer.

2024-11-12 16:05 UTC, martinduke commented
I went with the timer design because I thought it would be easy to write. But it turns out it's confusing to people, so I'm starting to think that we either require RESET_STREAM_AT or expose QUIC stream IDs to the application, and get rid of the timer.

2024-11-12 17:21 UTC, ianswett commented on draft-ietf-moq-transport.md
> -  [Final Object (i)],
I'm fine with removing this.

2024-11-12 17:21 UTC, ianswett commented
I'm fine with this design, minus explicitly specifying a timeout.

2024-11-12 17:43 UTC, mengelbart commented
I think RESET_STREAM_AT might work for QUIC, but if I understand WebTransport correctly, it doesn't expose it to the application and only uses it for the WebTransport session IDs. Referencing the highest stream ID sounds cleaner to me than setting an arbitrary timeout, but if that is hard for some QUIC APIs, I'm fine with a timeout.

Another option I could think of is to send SUBSCRIBE_DONE on a separate last stream which must not be reset. But that would mean we no longer send all control messages on the control stream...

2024-11-12 17:44 UTC, mengelbart commented
oh and the separate stream also requires exposing the stream ID...

2024-11-12 17:50 UTC, martinduke commented
> Another option I could think of is to send SUBSCRIBE_DONE on a separate last stream which must not be reset. But that would mean we no longer send all control messages on the control stream...

Even if that stream has a very low priority, I don't think we can guarantee that it arrives after any object streams that are sent around the same time.

2024-11-12 17:52 UTC, martinduke commented
> I think RESET_STREAM_AT might work for QUIC, but if I understand WebTransport correctly, it doesn't expose it to the application and only uses it for the WebTransport session IDs.

It's not clear to me if WebTransport is specifying the APIs, but to me this is less of an IETF question and more a "what are WebTransport implementers willing to do" question.

2024-11-12 20:10 UTC, martinduke commented
@vasilvv points out that the Webtrans API has a signal when the stream FIN has been ACKed. This makes everything way easier.

2024-11-12 22:57 UTC, afrind commented
Individual Comment:

I don't like using FIN-ACK:

1. It moves the waiting period from the subscriber to the publisher.  The high-scale/long wait cases are likely when relays publish fan-out to client subscribers, and the relay is the one with reason to free up resources faster.  The publisher otherwise has no reason to keep this state around but the subscriber might.
2. Receiving a FIN-ACK does not mean the MoQ layer has received the stream, only the QUIC stack, which could be in the peer's kernel (or someday, NIC).  The SUBSCRIBE_DONE could still be racing delivery of the QUIC data and result in missed objects.  HTTP/3 explicitly chose *not* to use QUIC signals in QPACK for these reasons.
3. The subscriber doesn't have to wait around after SUBSCRIBE_DONE if it is uninterested in remaining data, but by withholding the signal, it doesn't get a choice.

I still prefer using RESET_STREAM_AT -- the downside from my perspective is pushing WebTransport to include this surface, which I think they should anyway, and perhaps that raw QUIC implementations MUST negotiate this extension.  Timers are inelegant and a waste when everything was already received.

2024-11-13 15:06 UTC, martinduke commented
> LGTM. I assume this works with existing WebTransport APIs?

It's in both the spec and our implementation.

2024-11-13 23:45 UTC, TimEvens reviewed
Minor comments... but I'm unclear on how `SUBSCRIBE_DONE` is to be used with `Object Status` type **0x4** which indicates end of track.  If the publisher sends end of track object status, isn't that the same as `SUBSCRIBE_DONE`?

2024-11-13 23:45 UTC, TimEvens commented on draft-ietf-moq-transport.md
> +SUBSCRIBE_DONE to acknowledge the unsubscribe was successful.
Seems weird to me that it's named `SUBSCRIBE_DONE` for what is defined as `UNSUBSCRIBE_ACK`

2024-11-13 23:45 UTC, TimEvens commented on draft-ietf-moq-transport.md
> +2. All data streams have either been reset, or the stream API has provided a
Is stream API clarified? Suggest rewording as that makes an assumption of an API.

2024-11-13 23:45 UTC, TimEvens commented on draft-ietf-moq-transport.md
> +the stream API that the reliable size has been acknowledged.
Same regarding using "stream API". It suggests an implementation that this protocol doesn't appear to define.

2024-11-13 23:49 UTC, martinduke commented
> Minor comments... but I'm unclear on how `SUBSCRIBE_DONE` is to be used with `Object Status` type **0x4** which indicates end of track. If the publisher sends end of track object status, isn't that the same as `SUBSCRIBE_DONE`?

No. If the EndOfTrack object is delivered, there might still be other streams out there that are open and delivering earlier objects, or even streams that haven't been opened yet.

2024-11-13 23:50 UTC, martinduke commented on draft-ietf-moq-transport.md
> +SUBSCRIBE_DONE to acknowledge the unsubscribe was successful.
It's not just an UNSUBSCRIBE_ACK. It's also used when the SUBSCRIBE reaches its end.

2024-11-13 23:51 UTC, martinduke commented on draft-ietf-moq-transport.md
> +2. All data streams have either been reset, or the stream API has provided a
How would you reword it?

2024-11-14 00:12 UTC, TimEvens commented on draft-ietf-moq-transport.md
> +SUBSCRIBE_DONE to acknowledge the unsubscribe was successful.
isn't that redundant with object status 0x4/end of track?

2024-11-14 00:21 UTC, TimEvens commented on draft-ietf-moq-transport.md
> +SUBSCRIBE_DONE to acknowledge the unsubscribe was successful.
TBH, I don't believe it adds much value to ack unsubscribe.  It should be assumed that it was successful as it was transferred over a reliable control stream, which had to be processed by the remote otherwise the control stream would be invalidated.  If the remote doesn't do anything with the unsubscribe (e.g., noop the message) and continues to publish data, the relay should then respond with error.  I don't recommend using protocol violation in this case as that would close a connection causing a potential large impact that spans more than one track. This is a track error and should, IMHO, only affect that track.  With QUIC,  either side can reset a stream regardless of being bidir or unidir, right?  I would suggest that we need a track level error message that is followed by a RESET of the incoming stream. RESET of stream could indicate error code as well.

Out of scope for this PR but keep in mind as it relates, what happens when an app sends end of track or end of group object status and continues to send data that would violate that status???

2024-11-14 00:31 UTC, TimEvens commented
> > Minor comments... but I'm unclear on how `SUBSCRIBE_DONE` is to be used with `Object Status` type **0x4** which indicates end of track. If the publisher sends end of track object status, isn't that the same as `SUBSCRIBE_DONE`?
> 
> No. If the EndOfTrack object is delivered, there might still be other streams out there that are open and delivering earlier objects, or even streams that haven't been opened yet.

@martinduke , that needs to be clarified as that's unclear as described. If I understand your statement above, would it be correct to rephrase it as:

> "End of track" (EoT) indicates that this group, subgroup, and object id indicates the last in the track. The track alias **cannot be reused** after this status. Any group, subgroup, object id that is greater than what was indicated at the time of EoT are invalid and would result in a track error. Relays that receive EoT should mark the track as done, but linger it for some period of time to allow for missing/gap data that is inflight and as mentioned in #587?  If by chance the relay or receiving client is tracking gaps and detect no gaps upon receiving EoT, they can immediately close the track without having to wait a linger period for inflight groups/subgroups pending.

2024-11-14 19:12 UTC, TimEvens commented on draft-ietf-moq-transport.md
> +2. All data streams have either been reset, or the stream API has provided a
I believe the context here is the QUIC transport stack/API, correct?  If so, I would recommend "QUIC transport" instead of "stream API"

2024-11-20 18:39 UTC, martinduke commented on draft-ietf-moq-transport.md
> +SUBSCRIBE_DONE to acknowledge the unsubscribe was successful.
It is not redundant to end of track, as other objects could be delivered later and out of order, and sometimes the subscribe ends before the track does

2024-11-21 16:42 UTC, martinduke commented
After more thought, I really think #628 (Alan's stream-counting PR) is a superior approach, as it gives the option for the client to short-cut its timer. Some were concerned about messing up counting; worst case is it falls back to using the timer, which is this proposal.

2024-12-11 18:02 UTC, merged